Repository TileDB-Inc/TileDB, pull requests merged in 2018-07, with the labels that each got.

#787 Add non-buildtype imported location for TBB, and import as unknown.
  cmake/Modules/FindTBB_EP.cmake
Labels: build

#788 Doc additions
  doc/source/figures/map.graffle
  doc/source/figures/map.png
  doc/source/futher-reading/key-value-store.rst
  doc/source/futher-reading/object-management.rst
  doc/source/futher-reading/virtual-filesystem.rst
  doc/source/gensidebar.py
  doc/source/kv.rst
  doc/source/object.rst
  doc/source/vfs.rst
  doc/source/working-with-s3.rst
  examples/cpp_api/map.cc
  examples/cpp_api/object.cc
  examples/cpp_api/vfs.cc
Labels: docs

#789 More docs
  doc/source/dense-image-data.rst
  doc/source/gensidebar.py
  doc/source/sparse-geospatial-data.rst
Labels: docs

#792 Make sure Curl EP configure script is executable. Closes #790.
  cmake/Modules/FindCurl_EP.cmake
Labels: build

#793 Null tile extents for dimensions of dense arrays get assigned the dimension domain range
  test/src/unit-capi-array_schema.cc
  test/src/unit-cppapi-schema.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/tiledb.h
Labels: enhancement, internals

#795 Add C++ utils API documentation. Closes #783.
  test/src/unit-cppapi-util.cc
  tiledb/sm/cpp_api/utils.h
Labels: C++ API, docs

#794 Made a pass on Performance tutorials in docs.
  doc/source/futher-reading/language-bindings.rst
  doc/source/futher-reading/storage-backends.rst
  doc/source/gensidebar.py
  doc/source/performance/introduction.rst
  doc/source/performance/performance-factors.rst
  doc/source/performance/using-tiledb-statistics.rst
  doc/source/tutorials/performance-factors.rst
  doc/source/tutorials/tiling-dense-1.png
  doc/source/tutorials/tiling-dense-2.png
  doc/source/tutorials/tiling-dense-3.png
  doc/source/tutorials/tiling-dense-4.png
  doc/source/tutorials/tiling-expanded-1.png
  doc/source/tutorials/tiling-ordering-1.png
  doc/source/tutorials/tiling-ordering-2.png
  doc/source/tutorials/tiling-sparse-1.png
  doc/source/tutorials/tiling-sparse-2.png
  doc/source/tutorials/tiling-sparse-3.png
  doc/source/tutorials/tiling-sparse-4.png
  doc/source/tutorials/tiling-sparse-5.png
  doc/source/tutorials/tiling-sparse-6.png
  doc/source/tutorials/tiling-sparse-7.png
  doc/source/tutorials/tutorial-tiling-figures.svg
Labels: docs

#802 Exposed function for checking if the array is open. Closes #800
  HISTORY.md
  test/src/unit-capi-dense_array.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
Labels: API Addition, C API, C++ API

#803 small change to enable parallel sort of listed vfs paths
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/misc/parallel_functions.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: enhancement, performance

#804 Array/KV schema getters should return a copy in the C/C++ API
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-kv.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/storage_manager/consolidator.cc
Labels: C API, C++ API, bug, enhancement

#805 Add Python to Installation and Quickstart docs.
  doc/source/conf.py
  doc/source/installation.rst
  doc/source/quickstart.rst
  doc/source/usage.rst
Labels: docs

#806 Renaming an example for consistency.
  doc/source/tutorials/writing-sparse.rst
  examples/cpp_api/writing_sparse_multiple.cc
Labels: docs

#808 A small but important optimization for global writes
  tiledb/sm/query/writer.cc
Labels: enhancement, internals, performance

#817 Doc language tabs switch all tabs on the same page.
  doc/source/_static/custom.js
  doc/source/conf.py
Labels: docs

#815 Added Python code snippets and performed edits in docs
  doc/local-build.sh
  doc/source/figures/cpp.png
  doc/source/figures/python.png
  doc/source/figures/writing_sparse_multiple.graffle
  doc/source/figures/writing_sparse_multiple.png
  doc/source/gensidebar.py
  doc/source/performance/introduction.rst
  doc/source/tutorials/async.rst
  doc/source/tutorials/compression.rst
  doc/source/tutorials/concurrency-consistency.rst
  doc/source/tutorials/config.rst
  doc/source/tutorials/errors.rst
  doc/source/tutorials/object.rst
  doc/source/tutorials/reading.rst
  doc/source/tutorials/tiling-dense.rst
  doc/source/tutorials/tiling-sparse.rst
  doc/source/tutorials/vfs.rst
  doc/source/tutorials/working-with-hdfs.rst
  doc/source/tutorials/working-with-s3.rst
  doc/source/tutorials/writing-dense.rst
  doc/source/tutorials/writing-sparse.rst
Labels: docs

#819 Add more Python code to tutorials; add stats example program.
  doc/source/performance/using-tiledb-statistics.rst
  doc/source/quickstart.rst
  doc/source/tutorials/dense-arrays.rst
  doc/source/tutorials/fragments-consolidation.rst
  doc/source/tutorials/kv.rst
  doc/source/tutorials/multi-attribute-arrays.rst
  doc/source/tutorials/sparse-arrays.rst
  doc/source/tutorials/variable-length-attributes.rst
  examples/cpp_api/using_tiledb_stats.cc
Labels: docs

#820 Reorganize tutorial ToC; remove broken link.
  doc/source/gensidebar.py
  doc/source/tutorials/async.rst
  doc/source/tutorials/sparse-arrays.rst
Labels: docs

#823 Minor doc changes
  doc/source/conf.py
  doc/source/figures/golang.png
  doc/source/figures/r.png
  doc/source/quickstart.rst
  examples/c_api/object.c
Labels: docs

#827 small fix to compile on gcc 4.8.2
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/misc/stats.h
Labels: build

#829 Reword readme and fix quickstart link.
  README.md
Labels: docs

#831 small fix to compile with llvm version 3.5 on osx
  tiledb/sm/filesystem/vfs.cc
Labels: backport

#836 Add CMake variable to allow disabling building the test suite
  CMakeLists.txt
  bootstrap
  bootstrap.ps1
  cmake/TileDB-Superbuild.cmake
  doc/source/installation.rst
Labels: build, cmake, tests

#838 Add query get attributes list support
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: internals

#843 Added checks when setting the subarray in sparse writes. Closes #812
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/query/writer.cc
Labels: missing check

#858 Add TILEDB_INSTALL_LIBDIR CMake option.
  CMakeLists.txt
  cmake/TileDB-Superbuild.cmake
  tiledb/CMakeLists.txt
Labels: backport, build
