Repository TileDB-Inc/TileDB, pull requests merged in 2018-08, with the labels that each got.

#860 Cleaned up unused code and refactored utils.cc. Closes #43.
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-vfs.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/filesystem/hdfs_filesystem.cc
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/win.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/uri.cc
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: internals, refactor

#861 Return Ok when consolidating empty arrays.
  test/src/unit-cppapi-array.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
Labels: bug

#863 Add LRU cache invalidation function and test.
  test/src/unit-lru_cache.cc
  tiledb/sm/cache/lru_cache.cc
  tiledb/sm/cache/lru_cache.h
  tiledb/sm/misc/stats_counters.h
Labels: backport, internals

#866 Tile extent should be greater than zero. Closes #865
  test/src/unit-capi-array_schema.cc
  tiledb/sm/array_schema/dimension.cc
Labels: backport, missing check

#871 Remove TILEDB_USE_STATIC_* cmake variables in favor of better searching.
  cmake/Modules/FindBlosc_EP.cmake
  cmake/Modules/FindBzip2_EP.cmake
  cmake/Modules/FindLZ4_EP.cmake
  cmake/Modules/FindZstd_EP.cmake
Labels: backport, build

#873 don't fail on hdfs initialization if libhdfs does not exist
  tiledb/sm/filesystem/hdfs_filesystem.cc
  tiledb/sm/filesystem/hdfs_filesystem.h
  tiledb/sm/filesystem/vfs.cc
Labels: backport

#869 Bug fix in the read algorithm
  test/src/unit-capi-dense_array.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: backport, bug

#882 Invalidate cached max buffer sizes when the subarray changes
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/c_api/tiledb.cc
Labels: backport, bug

#889 Add simple benchmark programs and benchmark script.
  .travis.yml
  test/benchmarking/README.md
  test/benchmarking/benchmark.py
  test/benchmarking/src/CMakeLists.txt
  test/benchmarking/src/bench_dense_read_large_tile.cc
  test/benchmarking/src/bench_dense_read_small_tile.cc
  test/benchmarking/src/bench_dense_write_large_tile.cc
  test/benchmarking/src/bench_dense_write_small_tile.cc
  test/benchmarking/src/bench_sparse_read_large_tile.cc
  test/benchmarking/src/bench_sparse_read_small_tile.cc
  test/benchmarking/src/bench_sparse_write_large_tile.cc
  test/benchmarking/src/bench_sparse_write_small_tile.cc
  test/benchmarking/src/benchmark.cc
  test/benchmarking/src/benchmark.h
Labels: benchmark

#885 Appropriate changes towards supporting negative and real domains
  HISTORY.md
  doc/source/figures/neg_domain.graffle
  doc/source/figures/neg_domain.png
  doc/source/figures/real_domain.graffle
  doc/source/figures/real_domain.png
  doc/source/gensidebar.py
  doc/source/tutorials/neg-real.rst
  test/CMakeLists.txt
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-dense_neg.cc
  test/src/unit-capi-sparse_neg.cc
  test/src/unit-capi-sparse_real.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/dense_cell_range_iter.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
Labels: bug, docs, missing test

#906 FragmentMetadata tile size function now returns persisted size
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/query/reader.cc
Labels: internals

#911 Add Buffer::swap and fix realloc size tracking.
  test/src/unit-buffer.cc
  tiledb/sm/buffer/buffer.cc
  tiledb/sm/buffer/buffer.h
Labels: bug, internals

#912 Implement filter pipeline framework
  test/CMakeLists.txt
  test/src/unit-filter-buffer.cc
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/compression_filter.h
  tiledb/sm/filter/filter.cc
  tiledb/sm/filter/filter.h
  tiledb/sm/filter/filter_buffer.cc
  tiledb/sm/filter/filter_buffer.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/filter/filter_storage.cc
  tiledb/sm/filter/filter_storage.h
  tiledb/sm/misc/stats.cc
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: filters, internals

#915 Update HISTORY.md, and change dev version to 1.4.0.
  HISTORY.md
  tiledb/sm/c_api/tiledb_version.h
Labels: docs

#916 Separate IO from filtering (compression).
  HISTORY.md
  doc/source/performance/performance-factors.rst
  doc/source/tutorials/config.rst
  doc/source/tutorials/parallelism.rst
  test/src/unit-capi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
Labels: config param, internals

#917 Remove compression fields from Tile class.
  test/src/unit-filter-pipeline.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/sm/tile/tile_io.cc
Labels: internals

#921 Remove unnecessary null pointer checks. Closes #892
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv_item.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/consolidator.cc
Labels: internals

#924 Change filter C API to use explicit "filter list" object.
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-filter.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
Labels: C API, filters

#925 Several filter fixes
  test/src/unit-filter-buffer.cc
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/filter_buffer.cc
  tiledb/sm/filter/filter_buffer.h
  tiledb/sm/filter/filter_pipeline.cc
Labels: filters
