Repository TileDB-Inc/TileDB, pull requests merged in 2018-03, with the labels that each got.

#406 Update install-deps.ps1
  scripts/install-deps.ps1
Labels: Windows, build

#411 Only build Appveyor artifacts on dev and master.
  .appveyor.yml
Labels: build

#412 Fix TileDB library dynamic linking problem for C++ API.
  .appveyor.yml
  .travis.yml
  CMakeLists.txt
  HISTORY.md
  examples/c_api/CMakeLists.txt
  examples/cpp_api/CMakeLists.txt
  examples/cpp_api/tiledb_map_write.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/attribute.h
  tiledb/sm/cpp_api/compressor.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/config_iter.h
  tiledb/sm/cpp_api/context.h
  tiledb/sm/cpp_api/core_interface.h
  tiledb/sm/cpp_api/deleter.h
  tiledb/sm/cpp_api/dimension.h
  tiledb/sm/cpp_api/domain.h
  tiledb/sm/cpp_api/filebuf.h
  tiledb/sm/cpp_api/group.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/map_item.h
  tiledb/sm/cpp_api/map_iter.h
  tiledb/sm/cpp_api/map_proxy.h
  tiledb/sm/cpp_api/map_schema.h
  tiledb/sm/cpp_api/object.h
  tiledb/sm/cpp_api/object_iter.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/cpp_api/schema_base.h
  tiledb/sm/cpp_api/version.h
  tiledb/sm/cpp_api/vfs.h
Labels: C++ API

#422 Documentation sidebar fixes.
  doc/source/gensidebar.py
Labels: docs

#423 [ci skip] Update README.md
  README.md
Labels: docs

#424 Fix VS2015 build errors; add it to Appveyor config.
  .appveyor.yml
  CMakeLists.txt
Labels: CI, Windows, build

#425 Slight edits to docs
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/introduction.rst
Labels: docs

#429 Added dimension domain/tile extent checks. Closes #317
  test/src/unit-capi-array_schema.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
Labels: backport

#434 Bug fix in the sparse case. Closes #433.
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/read_state.cc
Labels: backport

#438 Bug fix for 1D vector query layout. Closes #437
  tiledb/sm/query/query.cc
Labels: backport

#444 Add simple stats framework, only used by VFS currently.
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/misc/stats.cc
  tiledb/sm/misc/stats.h
  tiledb/sm/misc/stats_counters.h
Labels: API Addition, C API

#449 add brew upgrade when installing dependencies
  .travis.yml
  scripts/install-deps.sh
  scripts/install-hadoop.sh
Labels: backport, build

#446 Added `ANY` datatype. Closes #399
  HISTORY.md
  test/src/unit-capi-any.cc
  test/src/unit-capi-string.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/compressors/dd_compressor.cc
  tiledb/sm/cpp_api/core_interface.h
  tiledb/sm/cpp_api/dimension.cc
  tiledb/sm/cpp_api/domain.cc
  tiledb/sm/enums/datatype.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/query/array_ordered_write_state.cc
  tiledb/sm/query/array_read_state.cc
  tiledb/sm/query/query.cc
Labels: API Addition, C API

#455 Change S3 default config. Closes #451
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-s3.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/storage_manager/config.h
Labels: C API, backport

#457 Add generic counters to stats reporting, used in two VFS locations.
  doc/source/c-api.rst
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/misc/stats.cc
  tiledb/sm/misc/stats.h
  tiledb/sm/misc/stats_counters.h
Labels: C API

#458 Added some S3 documentation. Closes #442
  doc/local-build.sh
  doc/source/conf.py
  doc/source/gensidebar.py
  doc/source/tiledb101/s3.rst
Labels: backport, docs

#461 [ci skip] Add sphinx-tabs to conda-env
  doc/source/conda-env.yml
Labels: backport, docs

#463 [ci skip] Modification to conda-env for RTD (integration with sphinx_tabs)
  doc/source/conda-env.yml
Labels: backport, docs

#462 S3 fixes
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/fragment/read_state.cc
  tiledb/sm/fragment/read_state.h
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/query/query.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: backport, enhancement, s3, vfs

#465 [ci skip] Reconciled release history
  HISTORY.md
Labels: backport

#467 Fix POSIX read/write bug for large operations
  tiledb/sm/filesystem/posix_filesystem.cc
Labels: backport

#472 Memory error handling and proper realloc usage
  HISTORY.md
  tiledb/sm/buffer/buffer.cc
  tiledb/sm/fragment/fragment.cc
  tiledb/sm/fragment/read_state.cc
  tiledb/sm/fragment/read_state.h
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/fragment/write_state.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/sm/tile/tile_io.cc
Labels: backport, bug

#473 Tune S3 connect parameters through config. Closes #441
  test/src/unit-capi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: backport, enhancement

#474 Added new function `tiledb_query_finalize` and made `tiledb_query_free` stateless.
  HISTORY.md
  examples/c_api/tiledb_dense_read_async.c
  examples/c_api/tiledb_dense_read_global.c
  examples/c_api/tiledb_dense_read_ordered_subarray.c
  examples/c_api/tiledb_dense_read_subset_incomplete.c
  examples/c_api/tiledb_dense_write_async.c
  examples/c_api/tiledb_dense_write_global_1.c
  examples/c_api/tiledb_dense_write_global_2.c
  examples/c_api/tiledb_dense_write_global_subarray.c
  examples/c_api/tiledb_dense_write_ordered_subarray.c
  examples/c_api/tiledb_dense_write_unordered.c
  examples/c_api/tiledb_sparse_read_global.c
  examples/c_api/tiledb_sparse_read_ordered_subarray.c
  examples/c_api/tiledb_sparse_read_subset_incomplete.c
  examples/c_api/tiledb_sparse_write_global_1.c
  examples/c_api/tiledb_sparse_write_global_2.c
  examples/c_api/tiledb_sparse_write_unordered_1.c
  examples/c_api/tiledb_sparse_write_unordered_2.c
  test/src/unit-capi-any.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-string.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/deleter.cc
Labels: C API

#476 Added function tiledb_vfs_get_config. Closes #452
  HISTORY.md
  test/src/unit-capi-vfs.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: C API

#480 Modified `Array::max_buffer_sizes` to return pairs of sizes in bytes
  HISTORY.md
  examples/cpp_api/tiledb_dense_read_async.cc
  examples/cpp_api/tiledb_dense_read_global.cc
  examples/cpp_api/tiledb_dense_read_ordered_subarray.cc
  examples/cpp_api/tiledb_sparse_read_global.cc
  examples/cpp_api/tiledb_sparse_read_ordered_subarray.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/query.h
Labels: C++ API

#475 Handle non-existent config param in C++ API. Closes #439
  HISTORY.md
  test/src/unit-cppapi-config.cc
  test/src/unit-cppapi-util.cc
  tiledb/sm/cpp_api/config.cc
Labels: C++ API, backport, bug

#481 Reconciled HISTORY and fixed error in C++ examples. Follow-up from PR #480.
  HISTORY.md
  examples/cpp_api/tiledb_dense_read_subset_incomplete.cc
  examples/cpp_api/tiledb_sparse_read_global.cc
  examples/cpp_api/tiledb_sparse_read_ordered_subarray.cc
  examples/cpp_api/tiledb_sparse_read_subset_incomplete.cc
Labels: C++ API, bug

#485 Bug fix when a read query overflows
  tiledb/sm/query/array_ordered_read_state.cc
Labels: backport, bug

#487 Add C++ API usage docs
  doc/source/usage.rst
Labels: docs

#489 Add script to linkify PR refs in markdown files
  scripts/markdown-link-prs.sh
Labels: scripts

#490 Add type_to_tiledb in tiledb::impl
  tiledb/sm/cpp_api/type.h
Labels: API Addition, C++ API

#492 Got rid of S3 special directories, slight C/C++ API changes for move functions.
  HISTORY.md
  doc/source/c-api.rst
  doc/source/tiledb101/storage-backends.rst
  examples/c_api/tiledb_error.c
  examples/c_api/tiledb_object_move.c
  examples/c_api/tiledb_vfs.c
  examples/cpp_api/tiledb_object_move.cc
  examples/cpp_api/tiledb_vfs.cc
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-hdfs-filesystem.cc
  test/src/unit-s3.cc
  test/src/unit-win-filesystem.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/object.cc
  tiledb/sm/cpp_api/object.h
  tiledb/sm/cpp_api/vfs.cc
  tiledb/sm/cpp_api/vfs.h
  tiledb/sm/filesystem/hdfs_filesystem.cc
  tiledb/sm/filesystem/hdfs_filesystem.h
  tiledb/sm/filesystem/posix_filesystem.cc
  tiledb/sm/filesystem/posix_filesystem.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/filesystem/win_filesystem.cc
  tiledb/sm/filesystem/win_filesystem.h
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/fragment/write_state.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/query/query.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, API Breakage, enhancement, s3, vfs

#493 Update c++-api.rst
  doc/source/c++-api.rst
Labels: docs

#494 Remove docs about fp domains being unsupported in the C++ api
  test/src/unit-cppapi-schema.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/cpp_api/domain.h
Labels: C++ API, backport, docs

#497 add raw pointer setters for set_subarray, set_coords, set_buffer
  test/src/unit-cppapi-array.cc
  tiledb/sm/cpp_api/query.h
Labels: API Addition, C++ API

#499 Add ability to parallelize VFS read operations.
  HISTORY.md
  test/src/unit-capi-config.cc
  test/src/unit-capi-vfs.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: vfs
