Repository TileDB-Inc/TileDB, pull requests merged in 2018-11, with the labels that each got.

#1049 Fix error building with newer S3 SDK versions.
  tiledb/sm/filesystem/s3.cc
Labels: build, s3

#1051 Fix typo in return status for building without TBB
  .travis.yml
  tiledb/sm/global_state/tbb_state.cc
Labels: backport

#1054 Always split coordinate tiles. Closes #1053.
  HISTORY.md
  doc/source/tutorials/format-description.rst
  test/inputs/arrays/non_split_coords_v1_4_0/__5dc2cc9cce204a189f825fd4919d0c55_1541540586869/__coords.tdb
  test/inputs/arrays/non_split_coords_v1_4_0/__5dc2cc9cce204a189f825fd4919d0c55_1541540586869/__fragment_metadata.tdb
  test/inputs/arrays/non_split_coords_v1_4_0/__5dc2cc9cce204a189f825fd4919d0c55_1541540586869/a.tdb
  test/inputs/arrays/non_split_coords_v1_4_0/__array_schema.tdb
  test/inputs/arrays/non_split_coords_v1_4_0/__lock.tdb
  test/src/unit-backwards_compat.cc
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/sm/tile/tile_io.cc
Labels: backport, backwards-compatibility, disk format, filters

#1056 Fixed bug with incomplete queries returning zero results. Closes #1055
  HISTORY.md
  test/src/unit-capi-array.cc
  test/src/unit-capi-incomplete.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: backport, bug, internals

#1058 Fix link errors against static TileDB on Windows.
  .appveyor.yml
  HISTORY.md
  examples/cmake_project/CMakeLists.txt
  tiledb/CMakeLists.txt
Labels: Windows, backport, build

#1061 Add PNG ingestion program from tutorials to source tree.
  .travis.yml
  doc/source/real-world-examples/dense-image-data.rst
  examples/png_ingestion/CMakeLists.txt
  examples/png_ingestion/README.md
  examples/png_ingestion/src/main.cc
Labels: backport, docs

#1062 Add typesafe filter option methods to C++ API.
  HISTORY.md
  test/src/unit-cppapi-filter.cc
  tiledb/sm/cpp_api/filter.h
Labels: API Addition, C++ API, backport, filters

#1065 Fix unnecessary tile copy in global order write finalize.
  HISTORY.md
  tiledb/sm/query/writer.cc
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
Labels: backport, internals, performance

#1072 Add missing aws key config documentation
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/storage_manager/config.h
Labels: docs

#1074 Fix double-delta bug in case where data could not be compressed.
  HISTORY.md
  test/src/unit-compression-dd.cc
  tiledb/sm/buffer/const_buffer.cc
  tiledb/sm/buffer/const_buffer.h
  tiledb/sm/compressors/dd_compressor.cc
Labels: backport, bug, compressors

#1078 Added VFS API for listing directories and getting the directory size.
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/unit-capi-vfs.cc
  test/src/unit-cppapi-vfs.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/object_iter.h
  tiledb/sm/cpp_api/vfs.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
Labels: API Addition, vfs
