Repository TileDB-Inc/TileDB, pull requests merged in 2018-06, with the labels that each got.

#676 Disable static TileDB build by default.
  .appveyor.yml
  .gitignore
  .travis.yml
  CMakeLists.txt
  bootstrap
  bootstrap.ps1
  cmake/Modules/FindAWSSDK_EP.cmake
  cmake/Modules/FindBlosc_EP.cmake
  cmake/Modules/FindBzip2_EP.cmake
  cmake/Modules/FindCurl_EP.cmake
  cmake/Modules/FindLZ4_EP.cmake
  cmake/Modules/FindOpenSSL_EP.cmake
  cmake/Modules/FindTBB_EP.cmake
  cmake/Modules/FindZlib_EP.cmake
  cmake/Modules/FindZstd_EP.cmake
  cmake/Modules/TileDBCommon.cmake
  cmake/TileDB-Superbuild.cmake
  cmake/inputs/Config.cmake.in
  doc/source/installation.rst
  doc/source/usage.rst
  examples/cmake_project/CMakeLists.txt
  examples/cmake_project/README.md
  examples/cmake_project/src/main.cc
  test/CMakeLists.txt
  tiledb/CMakeLists.txt
  tiledb/sm/fragment/fragment_metadata.h
Labels: build

#679 Check offset validity on writes.
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
Labels: C API, missing check

#680 Make fragment metadata consistent with multiprocess read/writes.
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: bug

#681 Fix several error messages.
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/cpp_api/utils.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: error message

#686 Fixed consistency issues with opening arrays. Closes #677.
  test/CMakeLists.txt
  test/src/unit-capi-consistency.cc
  test/src/unit-capi-consolidation.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: consistency

#692 Addressed various KV/Map issues
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-kv.cc
  test/src/unit-cppapi-map.cc
  tiledb/sm/cpp_api/map.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_item.cc
  tiledb/sm/kv/kv_item.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, C API, C++ API, enhancement, error message, missing check

#694 Closes #690
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/query/reader.cc
Labels: bug

#695 Fix anonymous attributes and add tests. Closes #688.
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: bug, internals

#696 C API additions/changes
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-array.cc
  test/src/unit-cppapi-map.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/map_schema.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/kv/kv_iter.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: API Addition, C API, C++ API

#700 C API changes and clean-up of KV class. Closes #608.
  HISTORY.md
  doc/source/c-api.rst
  examples/c_api/tiledb_dense_read_async.c
  examples/c_api/tiledb_dense_read_global.c
  examples/c_api/tiledb_dense_read_ordered_subarray.c
  examples/c_api/tiledb_sparse_read_global.c
  examples/c_api/tiledb_sparse_read_ordered_subarray.c
  test/src/unit-capi-any.cc
  test/src/unit-capi-async.cc
  test/src/unit-capi-consistency.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-string.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, API Breakage, C API, C++ API

#701 ArraySchema cleanup. Closes #525.
  test/src/unit-capi-dense_vector.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: bug, internals

#702 Reset query state when resetting the subarray. Closes #691
  test/src/unit-capi-dense_array.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: bug

#703 Fixed consistency issue in consolidator and optimized locking
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: bug, performance

#704 Do not calibrate subarray in next read query submission.
  test/src/unit-capi-incomplete.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: bug

#712 Add several new tutorials.
  doc/source/gensidebar.py
  doc/source/tutorials/dense-arrays.rst
  doc/source/tutorials/dense-data-ingestion.rst
  doc/source/tutorials/multi-attribute-arrays.rst
  doc/source/tutorials/sparse-arrays.rst
  doc/source/tutorials/tiles.rst
  doc/source/tutorials/tiling-dense-1.png
  doc/source/tutorials/tiling-dense-2.png
  doc/source/tutorials/tiling-dense-3.png
  doc/source/tutorials/tiling-dense-4.png
  doc/source/tutorials/tiling-expanded-1.png
  doc/source/tutorials/tiling-ordering-1.png
  doc/source/tutorials/tiling-ordering-2.png
  doc/source/tutorials/tiling-sparse-1.png
  doc/source/tutorials/tiling-sparse-2.png
  doc/source/tutorials/tiling-sparse-3.png
  doc/source/tutorials/tiling-sparse-4.png
  doc/source/tutorials/tiling-sparse-5.png
  doc/source/tutorials/tiling-sparse-6.png
  doc/source/tutorials/tiling-sparse-7.png
  doc/source/tutorials/tutorial-tiling-figures.svg
  doc/source/tutorials/variable-length-attributes.rst
  doc/source/tutorials/working-with-s3.rst
Labels: docs

#713 First pass on Quickstart in docs
  doc/source/conf.py
  doc/source/figures/intro_architecture.graffle/data.plist
  doc/source/figures/intro_architecture.graffle/image1.png
  doc/source/figures/intro_architecture.graffle/image10.png
  doc/source/figures/intro_architecture.graffle/image12.png
  doc/source/figures/intro_architecture.graffle/image13.png
  doc/source/figures/intro_architecture.graffle/image2.png
  doc/source/figures/intro_architecture.graffle/image3.png
  doc/source/figures/intro_architecture.graffle/image4.png
  doc/source/figures/intro_architecture.graffle/image5.png
  doc/source/figures/intro_architecture.graffle/image6.png
  doc/source/figures/intro_architecture.png
  doc/source/figures/intro_arrays.graffle/data.plist
  doc/source/figures/intro_arrays.graffle/image7.gif
  doc/source/figures/intro_arrays.png
  doc/source/figures/quickstart_dense.graffle
  doc/source/figures/quickstart_dense.png
  doc/source/figures/quickstart_sparse.graffle
  doc/source/figures/quickstart_sparse.png
  doc/source/introduction.rst
  doc/source/quickstart.rst
  doc/source/quickstart_array.png
  examples/cpp_api/quickstart_dense.cc
  examples/cpp_api/quickstart_map.cc
  examples/cpp_api/quickstart_sparse.cc
Labels: docs

#717 Pass on Installation and Usage in docs
  doc/source/installation.rst
  doc/source/usage.rst
Labels: docs

#719 Handling array URIs ending with a slash character. Fixes #711
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/writer.cc
Labels: bug

#716 Update or add many C++ API function docs.
  test/src/unit-cppapi-config.cc
  test/src/unit-cppapi-schema.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/attribute.h
  tiledb/sm/cpp_api/compressor.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/context.h
  tiledb/sm/cpp_api/dimension.h
  tiledb/sm/cpp_api/domain.h
  tiledb/sm/cpp_api/exception.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/map_schema.h
  tiledb/sm/cpp_api/object.h
  tiledb/sm/cpp_api/object_iter.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/cpp_api/vfs.h
Labels: C++ API, docs

#721 Cache attribute URIs when FragmentMetadata objects are created.
  doc/source/quickstart.rst
  examples/cpp_api/quickstart_map.cc
  tiledb/sm/cpp_api/map.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
Labels: C++ API, docs, performance

#728 Finished pass on Multi-attribute Arrays and Variable-length Attributes in docs.
  doc/source/dense-arrays.rst
  doc/source/figures/multi_attribute.graffle
  doc/source/figures/multi_attribute.png
  doc/source/figures/variable_length.graffle
  doc/source/figures/variable_length.png
  doc/source/gensidebar.py
  doc/source/multi-attribute-arrays.rst
  doc/source/sparse-arrays.rst
  doc/source/tutorials/multi-attribute-arrays.rst
  doc/source/tutorials/variable-length-attributes.rst
  doc/source/variable-length-attributes.rst
  examples/cpp_api/multi_attribute.cc
  examples/cpp_api/variable_length.cc
  tiledb/sm/cpp_api/query.h
Labels: docs

#734 Blosc should not be a default compressor. Closes #733
  test/src/unit-capi-array_schema.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
Labels: disk format, internals

#735 Add cache_hit output parameter to TileIO::read().
  tiledb/sm/query/reader.cc
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: internals

#736 Add many new stats counters; add a summary to report.
  tiledb/sm/cache/lru_cache.cc
  tiledb/sm/compressors/blosc_compressor.cc
  tiledb/sm/compressors/bzip_compressor.cc
  tiledb/sm/compressors/dd_compressor.cc
  tiledb/sm/compressors/gzip_compressor.cc
  tiledb/sm/compressors/lz4_compressor.cc
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/compressors/zstd_compressor.cc
  tiledb/sm/misc/stats.cc
  tiledb/sm/misc/stats.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/tile/tile_io.cc
Labels: enhancement, internals

#737 Add Stats class to C++ API.
  HISTORY.md
  doc/source/c++-api.rst
  tiledb/CMakeLists.txt
  tiledb/sm/cpp_api/stats.h
  tiledb/sm/cpp_api/tiledb
Labels: API Addition, C++ API

#738 Added sections Tiling Dense Arrays and Tiling Sparse Arrays in docs
  doc/source/dense-arrays.rst
  doc/source/figures/tiling_dense_domain_expansion.graffle
  doc/source/figures/tiling_dense_domain_expansion.png
  doc/source/figures/tiling_dense_motivation_no_tiling.graffle
  doc/source/figures/tiling_dense_motivation_no_tiling.png
  doc/source/figures/tiling_dense_motivation_with_tiling.graffle
  doc/source/figures/tiling_dense_motivation_with_tiling.png
  doc/source/figures/tiling_dense_physical_cell_layout.graffle
  doc/source/figures/tiling_dense_physical_cell_layout.png
  doc/source/figures/tiling_dense_space_data_tiles.graffle
  doc/source/figures/tiling_dense_space_data_tiles.png
  doc/source/figures/tiling_dense_space_filling_curve.graffle
  doc/source/figures/tiling_dense_space_filling_curve.png
  doc/source/figures/tiling_dense_tile_cell_order.graffle
  doc/source/figures/tiling_dense_tile_cell_order.png
  doc/source/figures/tiling_sparse_data_tiles.graffle
  doc/source/figures/tiling_sparse_data_tiles.png
  doc/source/figures/tiling_sparse_mbr.graffle
  doc/source/figures/tiling_sparse_mbr.png
  doc/source/figures/tiling_sparse_mbr_shape.graffle
  doc/source/figures/tiling_sparse_mbr_shape.png
  doc/source/figures/tiling_sparse_physical_cell_layout.graffle
  doc/source/figures/tiling_sparse_physical_cell_layout.png
  doc/source/figures/tiling_sparse_space_tiling_problem.graffle
  doc/source/figures/tiling_sparse_space_tiling_problem.png
  doc/source/gensidebar.py
  doc/source/sparse-arrays.rst
  doc/source/tiling-dense.rst
  doc/source/tiling-sparse.rst
Labels: docs

#741 Added section Compression to the docs
  doc/source/compression.rst
  doc/source/dense-arrays.rst
  doc/source/futher-reading/basic-concepts.rst
  doc/source/futher-reading/compression.rst
  doc/source/futher-reading/physical-organization.rst
  doc/source/futher-reading/system-architecture.rst
  doc/source/futher-reading/writing/writing-dense-data.rst
  doc/source/futher-reading/writing/writing-sparse-data.rst
  doc/source/gensidebar.py
  doc/source/tiling-dense.rst
Labels: docs

#743 Fix ls on S3 when the number of objects is larger than 1000. Closes #739
  test/src/unit-capi-object_mgmt.cc
  tiledb/sm/filesystem/s3.cc
Labels: bug, s3

#744 Fix dense subarray reads with expanded domains. Closes #740.
  test/src/unit-cppapi-array.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/cpp_api/array.h
Labels: bug

#747 Writes expect cell values for all attributes to be written
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/query/writer.cc
Labels: bug, missing check

#749 Fixed bug in dense reads on empty areas. Closes #748.
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/reader.cc
Labels: bug

#752 Fixed bug in dense reads with sparse cells and empty areas. Closes #751
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/reader.cc
Labels: bug

#757 Add tutorial on real-world sparse data ingestion.
  doc/source/figures/us-zip-codes-all.png
  doc/source/figures/us-zip-codes-sliced.png
  doc/source/gensidebar.py
  doc/source/tutorials/sparse-data-ingestion.rst
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/vfs.h
Labels: docs

#756 #684 defer map item get, #687 disallow rvalue buffer set
  HISTORY.md
  examples/cpp_api/quickstart_map.cc
  tiledb/sm/cpp_api/map.h
Labels: C++ API

#763 Bug fix in dense reads with empty areas. Closes #762
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/reader.cc
Labels: bug

#766 Fix build error on GCC 7; fix TBB build warning.
  cmake/Modules/FindTBB_EP.cmake
  tiledb/sm/query/writer.cc
Labels: bug, build

#768 Fixed bug with dense multi-fragment reads. Closes #767
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/reader.cc
Labels: bug, internals

#772 Use uuid instead of tid in consolidated fragment names. Closes #771
  tiledb/sm/storage_manager/consolidator.cc
Labels: bug

#770 Added section Fragments and Consolidation to docs, cleaned up old docs, and fixed map example in quickstart
  doc/source/figures/fragments.graffle
  doc/source/figures/fragments.png
  doc/source/figures/fragments_consolidated.graffle
  doc/source/figures/fragments_consolidated.png
  doc/source/figures/fragments_delete.graffle
  doc/source/figures/fragments_delete.png
  doc/source/fragments-consolidation.rst
  doc/source/futher-reading/consolidation.rst
  doc/source/futher-reading/reading/Figure_16.png
  doc/source/futher-reading/reading/Figure_17.png
  doc/source/futher-reading/reading/Figure_18.png
  doc/source/futher-reading/reading/Figure_19.png
  doc/source/futher-reading/reading/Figure_20.png
  doc/source/futher-reading/reading/Figure_21.png
  doc/source/futher-reading/reading/handling-incomplete-queries.rst
  doc/source/futher-reading/reading/index.rst
  doc/source/futher-reading/reading/reading-dense-arrays.rst
  doc/source/futher-reading/reading/reading-sparse-arrays.rst
  doc/source/futher-reading/reading/utility-functions.rst
  doc/source/futher-reading/updating.rst
  doc/source/futher-reading/writing/Figure_10.png
  doc/source/futher-reading/writing/Figure_11.png
  doc/source/futher-reading/writing/Figure_12.png
  doc/source/futher-reading/writing/Figure_8.png
  doc/source/futher-reading/writing/Figure_9.png
  doc/source/futher-reading/writing/index.rst
  doc/source/futher-reading/writing/writing-dense-data.rst
  doc/source/futher-reading/writing/writing-sparse-data.rst
  doc/source/gensidebar.py
  doc/source/quickstart.rst
  examples/cpp_api/fragments_consolidation.cc
Labels: docs

#774 Add tutorial on using and interpreting the statistics.
  doc/source/gensidebar.py
  doc/source/tutorials/using-tiledb-statistics.rst
Labels: docs

#776 Add basic list of performance factors to tutorials.
  doc/source/gensidebar.py
  doc/source/tutorials/performance-factors.rst
Labels: docs

#778 Fixd bug in Domain::floor_to_tile. Closes #777
  tiledb/sm/array_schema/domain.cc
Labels: bug, internals

#780 Fixed bug in buffer size estimate. Closes #779
  tiledb/sm/storage_manager/storage_manager.cc
Labels: bug, enhancement, internals
