Repository TileDB-Inc/TileDB, pull requests merged in 2018-04, with the labels that each got.

#501 Refactored sparse reads. Closes #500.
  HISTORY.md
  examples/c_api/tiledb_sparse_read_subset.c
  examples/cpp_api/tiledb_sparse_read_subset.cc
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: enhancement

#503 Wait (until max attempts) for S3 buckets to be created.
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
Labels: backport, bug, s3

#516 A few minor docs tweaks.
  .readthedocs.yml
  cmake/TileDB-Superbuild.cmake
  doc/local-build.sh
  doc/source/c++-api.rst
  doc/source/conda-env.yml
  doc/source/conf.py
  doc/source/s3.rst
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/utils.h
Labels: docs

#528 Fix GlobalCmp comparator.
  tiledb/sm/misc/comparators.h
Labels: bug

#532 Refactored dense reads
  HISTORY.md
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/fragment/fragment.cc
  tiledb/sm/fragment/fragment.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/fragment/read_state.cc
  tiledb/sm/fragment/read_state.h
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/fragment/write_state.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/query/array_ordered_read_state.cc
  tiledb/sm/query/array_ordered_read_state.h
  tiledb/sm/query/array_read_state.cc
  tiledb/sm/query/array_read_state.h
  tiledb/sm/query/dense_cell_range_iter.cc
  tiledb/sm/query/dense_cell_range_iter.h
  tiledb/sm/query/pq_fragment_cell_range.cc
  tiledb/sm/query/pq_fragment_cell_range.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/smaller_pq_fragment_cell_range.cc
  tiledb/sm/query/smaller_pq_fragment_cell_range.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: enhancement, performance

#534 Fix Query::dedup_coords bug and add test.
  test/src/unit-capi-dense_vector.cc
  tiledb/sm/query/query.cc
Labels: bug

#543 Refactored dense ordered writes
  HISTORY.md
  test/src/unit-capi-dense_array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/buffer/const_buffer.cc
  tiledb/sm/buffer/const_buffer.h
  tiledb/sm/filesystem/posix_filesystem.cc
  tiledb/sm/query/dense_cell_range_iter.cc
  tiledb/sm/query/dense_cell_range_iter.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
Labels: enhancement

#545 Refactored unordered writes (for both dense and sparse arrays)
  HISTORY.md
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/fragment/write_state.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/query/array_ordered_write_state.cc
  tiledb/sm/query/array_ordered_write_state.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/storage_manager/consolidator.cc
Labels: enhancement

#547 Add Query::finalize to C++ API. Closes #541.
  HISTORY.md
  examples/cpp_api/tiledb_dense_read_global.cc
  examples/cpp_api/tiledb_dense_read_ordered_subarray.cc
  examples/cpp_api/tiledb_dense_read_subset_incomplete.cc
  examples/cpp_api/tiledb_dense_write_global_1.cc
  examples/cpp_api/tiledb_dense_write_global_2.cc
  examples/cpp_api/tiledb_dense_write_global_subarray.cc
  examples/cpp_api/tiledb_dense_write_ordered_subarray.cc
  examples/cpp_api/tiledb_dense_write_unordered.cc
  examples/cpp_api/tiledb_sparse_read_global.cc
  examples/cpp_api/tiledb_sparse_read_ordered_subarray.cc
  examples/cpp_api/tiledb_sparse_read_subset.cc
  examples/cpp_api/tiledb_sparse_write_global_1.cc
  examples/cpp_api/tiledb_sparse_write_global_2.cc
  examples/cpp_api/tiledb_sparse_write_unordered_1.cc
  examples/cpp_api/tiledb_sparse_write_unordered_1_again.cc
  examples/cpp_api/tiledb_sparse_write_unordered_2.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/deleter.cc
  tiledb/sm/cpp_api/query.cc
  tiledb/sm/cpp_api/query.h
Labels: API Addition, C++ API

#552 Refactored writes in global layout
  HISTORY.md
  examples/c_api/tiledb_dense_read_global.c
  examples/c_api/tiledb_sparse_read_global.c
  test/src/unit-buffer.cc
  test/src/unit-capi-kv.cc
  test/src/unit-cppapi-array.cc
  tiledb/CMakeLists.txt
  tiledb/sm/buffer/buffer.cc
  tiledb/sm/buffer/buffer.h
  tiledb/sm/filesystem/posix_filesystem.cc
  tiledb/sm/fragment/fragment.cc
  tiledb/sm/fragment/fragment.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/write_state.cc
  tiledb/sm/fragment/write_state.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
Labels: enhancement

#560 Fix libcurl EP not finding OpenSSL EP.
  CMakeLists.txt
  cmake/Modules/FindCurl_EP.cmake
  cmake/TileDB-Superbuild.cmake
  cmake/inputs/configure-curl.sh.in
Labels: build

#570 Clean up
  HISTORY.md
  examples/c_api/tiledb_dense_read_subset_incomplete.c
  examples/cpp_api/tiledb_dense_read_global.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/query.cc
  tiledb/sm/cpp_api/query.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Breakage, C API, C++ API, enhancement

#577 Split `Query` into `Reader` and `Writer`. Closes #576.
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: enhancement

#580 Consolidation fixes and added tests
  test/CMakeLists.txt
  test/src/unit-capi-async.cc
  test/src/unit-capi-consolidation.cc
  tiledb/sm/misc/uri.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: bug, tests

#578 Implement a task cancellation mechanism. Closes #569.
  HISTORY.md
  test/src/unit-capi-async.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-threadpool.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/context.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/global_state/global_state.cc
  tiledb/sm/global_state/global_state.h
  tiledb/sm/global_state/signal_handlers.cc
  tiledb/sm/global_state/signal_handlers.h
  tiledb/sm/global_state/watchdog.cc
  tiledb/sm/global_state/watchdog.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/thread_pool.cc
  tiledb/sm/misc/thread_pool.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/query_macros.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: C API, C++ API, enhancement
