Repository TileDB-Inc/TileDB, pull requests merged in 2018-09, with the labels that each got.

#927 Filter C API changes
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-filter.cc
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/enums/filter_option.h
  tiledb/sm/enums/filter_type.h
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/compression_filter.h
  tiledb/sm/filter/filter.cc
  tiledb/sm/filter/filter.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/noop_filter.cc
  tiledb/sm/filter/noop_filter.h
Labels: C API, filters

#928 Add bit width compression filter.
  HISTORY.md
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/filter/bit_width_reduction_filter.cc
  tiledb/sm/filter/bit_width_reduction_filter.h
  tiledb/sm/filter/filter.cc
Labels: filters

#929 Filter C API work
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-filter.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
Labels: C API, filters

#932 Attribute deserialize status check added. Closes #926
  tiledb/sm/array_schema/array_schema.cc
Labels: internals

#933 Allow reservered attribute additions to internal ArraySchema class. Closes #930
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
Labels: internals

#935 Bug fix in the way the maximum buffer sizes are estimated upon reading var-sized attributes. Closes #903
  test/CMakeLists.txt
  test/src/unit-cppapi-updates.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: bug

#936 Added note to var-length tutorial on read buffer sizes. Closes #934
  doc/source/tutorials/reading.rst
  doc/source/tutorials/variable-length-attributes.rst
Labels: docs

#938 Update filter pipeline metadata to allow for better filter composition.
  test/src/unit-filter-buffer.cc
  test/src/unit-filter-pipeline.cc
  tiledb/sm/filter/bit_width_reduction_filter.cc
  tiledb/sm/filter/bit_width_reduction_filter.h
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/compression_filter.h
  tiledb/sm/filter/filter.h
  tiledb/sm/filter/filter_buffer.cc
  tiledb/sm/filter/filter_buffer.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/filter/noop_filter.cc
  tiledb/sm/filter/noop_filter.h
Labels: filters

#941 Fix bits required calculation in bit width filter.
  test/src/unit-filter-pipeline.cc
  tiledb/sm/filter/bit_width_reduction_filter.cc
Labels: filters

#942 Make the KV comply with the consistency model of array. Closes #897
  HISTORY.md
  doc/source/c-api.rst
  doc/source/quickstart.rst
  doc/source/tutorials/kv.rst
  examples/c_api/kv.c
  examples/c_api/quickstart_kv.c
  examples/cpp_api/map.cc
  examples/cpp_api/quickstart_map.cc
  test/src/unit-capi-kv.cc
  test/src/unit-cppapi-map.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_iter.cc
Labels: API Breakage, consistency, key value

#943 Add bitshuffle filter.
  CMakeLists.txt
  cmake/Modules/CheckAVX2Support.cmake
  external/include/bitshuffle/LICENSE
  external/include/bitshuffle/bitshuffle_core.h
  external/include/bitshuffle/bitshuffle_internals.h
  external/include/bitshuffle/iochain.h
  external/src/bitshuffle/bitshuffle_core.cc
  external/src/bitshuffle/iochain.cc
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/filter/bitshuffle_filter.cc
  tiledb/sm/filter/bitshuffle_filter.h
  tiledb/sm/filter/filter.cc
Labels: filters

#946 Add byteshuffle filter.
  HISTORY.md
  cmake/Modules/CheckAVX2Support.cmake
  external/include/blosc/LICENSE
  external/include/blosc/blosc-common.h
  external/include/blosc/shuffle-avx2.h
  external/include/blosc/shuffle-generic.h
  external/include/blosc/shuffle-sse2.h
  external/include/blosc/shuffle.h
  external/src/blosc/shuffle-avx2.cc
  external/src/blosc/shuffle-generic.cc
  external/src/blosc/shuffle-sse2.cc
  external/src/blosc/shuffle.cc
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/filter/byteshuffle_filter.cc
  tiledb/sm/filter/byteshuffle_filter.h
  tiledb/sm/filter/filter.cc
Labels: filters

#947 Added C API function to get array URI. Closes #937
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/unit-capi-array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/query.h
Labels: C API

#954 Add AES-256-GCM "internal" filter.
  test/CMakeLists.txt
  test/src/unit-encryption.cc
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/encryption/encryption.cc
  tiledb/sm/encryption/encryption.h
  tiledb/sm/encryption/encryption_openssl.cc
  tiledb/sm/encryption/encryption_openssl.h
  tiledb/sm/encryption/encryption_win32.cc
  tiledb/sm/encryption/encryption_win32.h
  tiledb/sm/enums/filter_type.h
  tiledb/sm/filter/encryption_aes256gcm_filter.cc
  tiledb/sm/filter/encryption_aes256gcm_filter.h
  tiledb/sm/filter/filter.cc
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
Labels: encryption, filters

#955 Moving state from tiledb.cc to inner classes. Closes #881
  test/src/unit-capi-array.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/filesystem/vfs_file_handle.cc
  tiledb/sm/filesystem/vfs_file_handle.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/storage_manager/config_iter.cc
  tiledb/sm/storage_manager/config_iter.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/context.cc
  tiledb/sm/storage_manager/context.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: internals

#959 Added better handling of null URI. Also added missing break in Status::code_to_string switch case.
  test/src/unit-capi-array.cc
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/uri.cc
  tiledb/sm/misc/uri.h
Labels: internals, missing check

#961 Serialize filter pipeline in generic tile headers.
  tiledb/sm/filter/filter.h
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: filters, internals

#963 Fix segfault in error handling for invalid schemas.
  test/src/unit-capi-array_schema.cc
  tiledb/sm/storage_manager/open_array.cc
Labels: bug

#968 Add C API for encrypting arrays.
  test/src/unit-capi-array.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-filter-pipeline.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/encryption/encryption.h
  tiledb/sm/encryption/encryption_key.cc
  tiledb/sm/encryption/encryption_key.h
  tiledb/sm/encryption/encryption_key_validation.cc
  tiledb/sm/encryption/encryption_key_validation.h
  tiledb/sm/enums/encryption_type.h
  tiledb/sm/filter/encryption_aes256gcm_filter.cc
  tiledb/sm/filter/encryption_aes256gcm_filter.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: API Addition, C API, encryption

#970 Add encrypted KVs and encrypted consolidation.
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-kv.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile_io.cc
Labels: API Addition, C API, encryption

#972 Decouple format version number from library version number.
  test/src/unit-capi-version.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: disk format, internals
