Repository TileDB-Inc/TileDB, pull requests merged in 2018-12, with the labels that each got.

#1079 Bug fix in the case of dense reads in the presence of both dense and sparse fragments
  HISTORY.md
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: bug, internals

#1081 Add 'tiledb' CLI tool with two supported actions.
  CMakeLists.txt
  cmake/Modules/FindClipp_EP.cmake
  cmake/TileDB-Superbuild.cmake
  tools/CMakeLists.txt
  tools/README.md
  tools/src/commands/command.h
  tools/src/commands/help_command.cc
  tools/src/commands/help_command.h
  tools/src/commands/info_command.cc
  tools/src/commands/info_command.h
  tools/src/main/tiledb.cc
  tools/src/misc/common.h
Labels: cli

#1084 Lazily create S3 client instance on first request.
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
Labels: backport, performance, s3

#1087 Fix CMake error that resulted in omitting unit-s3 test.
  test/CMakeLists.txt
  test/src/unit-s3.cc
  test/src/unit-threadpool.cc
  tiledb/sm/misc/thread_pool.cc
Labels: s3, tests

#1091 Add linking ld for unit tests
  test/CMakeLists.txt
Labels: backport, build, tests

#1092 Re-enable HDFS unit test.
  test/CMakeLists.txt
  test/src/unit-hdfs-filesystem.cc
Labels: build, hadoop, tests

#1096 Fix two config parameters not being set properly.
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: backport, bug, config param

#1098 Add several small CLI info commands.
  tools/README.md
  tools/src/commands/info_command.cc
  tools/src/commands/info_command.h
Labels: cli

#1100 Fixed bug in sparse reads with real domain, located in the way the next subarray partition is computed
  HISTORY.md
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-sparse_real.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/misc/utils.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
Labels: bug, internals

#1101 Refactored and enhanced the consolidation algorithm
  HISTORY.md
  doc/source/figures/consolidatable.graffle
  doc/source/figures/consolidatable.png
  doc/source/figures/consolidation_ampl.graffle
  doc/source/figures/consolidation_ampl.png
  doc/source/figures/consolidation_clean_up.graffle
  doc/source/figures/consolidation_clean_up.png
  doc/source/figures/fragments_consolidated.graffle
  doc/source/figures/fragments_consolidated.png
  doc/source/gensidebar.py
  doc/source/performance/performance-factors.rst
  doc/source/tutorials/advanced-consolidation.rst
  doc/source/tutorials/config.rst
  doc/source/tutorials/fragments-consolidation.rst
  examples/c_api/fragments_consolidation.c
  test/src/unit-capi-config.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-kv.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile.cc
Labels: API Breakage, consolidation, enhancement, refactor
