Repository TileDB-Inc/TileDB, pull requests merged in 2018-05, with the labels that each got.

#581 Improve sparse read performance ~25%
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: performance

#583 Use std::vector instead of std::list for OverlappingCoordsList.
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: performance

#587 Add limits.h header for SSIZE_MAX
  tiledb/sm/filesystem/posix_filesystem.cc
Labels: bug, build

#595 [ci-skip] Two docs fixes. Closes #589.
  doc/source/c++-api.rst
  doc/source/c-api.rst
Labels: docs

#598 Add PreallocatedBuffer class and use in all decompressors.
  test/src/unit-compression-dd.cc
  test/src/unit-compression-rle.cc
  tiledb/CMakeLists.txt
  tiledb/sm/buffer/preallocated_buffer.cc
  tiledb/sm/buffer/preallocated_buffer.h
  tiledb/sm/compressors/blosc_compressor.cc
  tiledb/sm/compressors/blosc_compressor.h
  tiledb/sm/compressors/bzip_compressor.cc
  tiledb/sm/compressors/bzip_compressor.h
  tiledb/sm/compressors/dd_compressor.cc
  tiledb/sm/compressors/dd_compressor.h
  tiledb/sm/compressors/gzip_compressor.cc
  tiledb/sm/compressors/gzip_compressor.h
  tiledb/sm/compressors/lz4_compressor.cc
  tiledb/sm/compressors/lz4_compressor.h
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/compressors/rle_compressor.h
  tiledb/sm/compressors/zstd_compressor.cc
  tiledb/sm/compressors/zstd_compressor.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/tile/tile_io.cc
Labels: compressors

#599 Parallelize decompression and per-tile I/O.
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/parallel_functions.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: performance

#602 Change install directories to use GNUInstallDirs
  cmake/Modules/FindTBB_EP.cmake
  tiledb/CMakeLists.txt
Labels: build

#603 Improve cmake external project compatibility
  CMakeLists.txt
  cmake/TileDB-Superbuild.cmake
  examples/CMakeLists.txt
  examples/c_api/CMakeLists.txt
  examples/cpp_api/CMakeLists.txt
  test/CMakeLists.txt
  tiledb/CMakeLists.txt
Labels: build

#609 Return cell coordinates in dense reads if requested
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: enhancement

#611 Parallelize copy_fixed_cells.
  tiledb/sm/misc/stats.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
Labels: performance

#613 Added API for computing subarray partitions based on memory budget
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-dense_array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, enhancement

#623 Fixed bug in subarray partitioning. Fixes #622
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/query/reader.cc
Labels: bug

#624 Parallelize tile chunk compression and coordinate sorting.
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/writer.cc
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile_io.cc
  tiledb/sm/tile/tile_io.h
Labels: compressors, performance

#626 Parallelize write queries over attributes.
  tiledb/sm/query/writer.cc
Labels: performance

#628 Parallelize POSIX and Win32 write operations.
  HISTORY.md
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-uri.cc
  test/src/unit-win-filesystem.cc
  tiledb/CMakeLists.txt
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
  tiledb/sm/filesystem/posix_filesystem.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/filesystem/win.cc
  tiledb/sm/filesystem/win.h
  tiledb/sm/filesystem/win_filesystem.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/misc/uri.cc
Labels: performance, vfs

#627 Changing tiledb_*_free functions to return void and not take context as input. Also adding tiledb_kv_iter_finalize and tiledb_kv_free.
  HISTORY.md
  doc/source/c++-api.rst
  doc/source/c-api.rst
  examples/c_api/tiledb_array_schema.c
  examples/c_api/tiledb_config.c
  examples/c_api/tiledb_dense_create.c
  examples/c_api/tiledb_dense_read_async.c
  examples/c_api/tiledb_dense_read_global.c
  examples/c_api/tiledb_dense_read_ordered_subarray.c
  examples/c_api/tiledb_dense_read_subset_incomplete.c
  examples/c_api/tiledb_dense_write_async.c
  examples/c_api/tiledb_dense_write_global_1.c
  examples/c_api/tiledb_dense_write_global_2.c
  examples/c_api/tiledb_dense_write_global_subarray.c
  examples/c_api/tiledb_dense_write_ordered_subarray.c
  examples/c_api/tiledb_dense_write_unordered.c
  examples/c_api/tiledb_kv_create.c
  examples/c_api/tiledb_kv_iter.c
  examples/c_api/tiledb_kv_read.c
  examples/c_api/tiledb_kv_write.c
  examples/c_api/tiledb_sparse_create.c
  examples/c_api/tiledb_sparse_read_global.c
  examples/c_api/tiledb_sparse_read_ordered_subarray.c
  examples/c_api/tiledb_sparse_read_subset.c
  examples/c_api/tiledb_sparse_write_global_1.c
  examples/c_api/tiledb_sparse_write_global_2.c
  examples/c_api/tiledb_sparse_write_unordered_1.c
  examples/c_api/tiledb_sparse_write_unordered_2.c
  examples/c_api/tiledb_vfs.c
  examples/c_api/tiledb_vfs_read.c
  examples/c_api/tiledb_vfs_write.c
  examples/cpp_api/tiledb_map_read.cc
  examples/cpp_api/tiledb_map_write.cc
  test/src/unit-capi-any.cc
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-async.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-error.cc
  test/src/unit-capi-incomplete.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-string.cc
  test/src/unit-capi-uri.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-cppapi-map.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/attribute.h
  tiledb/sm/cpp_api/deleter.h
  tiledb/sm/cpp_api/dimension.h
  tiledb/sm/cpp_api/domain.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/cpp_api/schema_base.h
  tiledb/sm/cpp_api/vfs.h
Labels: API Addition, API Breakage, C API, C++ API

#630 Clean up parallel SM and VFS config params.
  HISTORY.md
  test/src/unit-capi-config.cc
  test/src/unit-capi-vfs.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/filesystem/win.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: config param

#635 Add sm.num_tbb_threads config parameter.
  HISTORY.md
  test/src/unit-capi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: config param

#637 Added checks for duplicate coordinates and option for coordinate deduplication
  HISTORY.md
  test/src/unit-capi-config.cc
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: config param, enhancement, missing check

#646 Add S3 proxy params; allow bucket creation outside of us-east-1.
  HISTORY.md
  test/src/unit-capi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: config param, s3

#651 Refactored the way the arrays are opened/closed. Closes #553
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-dense_array.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/locked_object.cc
  tiledb/sm/storage_manager/locked_object.h
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: enhancement

#652 Improve performance of object listing.
  doc/source/c++-api.rst
  tiledb/sm/cpp_api/object_iter.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: performance, s3

#655 Convenience build fixes for ExternalProject users.
  cmake/TileDB-Superbuild.cmake
  cmake/inputs/Config.cmake.in
Labels: build

#656 Disable setting lock callback for OpenSSL >= 1.1.0.
  tiledb/sm/global_state/openssl_state.cc
Labels: build

#663 Several build dependency fixes.
  CMakeLists.txt
  cmake/Modules/FindTBB_EP.cmake
  cmake/TileDB-Superbuild.cmake
Labels: build

#670 Set buffer for an individual attribute to the query
  HISTORY.md
  doc/source/c-api.rst
  examples/c_api/tiledb_dense_read_async.c
  examples/c_api/tiledb_dense_read_global.c
  examples/c_api/tiledb_dense_read_ordered_subarray.c
  examples/c_api/tiledb_dense_read_subset_incomplete.c
  examples/c_api/tiledb_dense_write_async.c
  examples/c_api/tiledb_dense_write_global_1.c
  examples/c_api/tiledb_dense_write_global_2.c
  examples/c_api/tiledb_dense_write_global_subarray.c
  examples/c_api/tiledb_dense_write_ordered_subarray.c
  examples/c_api/tiledb_dense_write_unordered.c
  examples/c_api/tiledb_sparse_read_global.c
  examples/c_api/tiledb_sparse_read_ordered_subarray.c
  examples/c_api/tiledb_sparse_read_subset.c
  examples/c_api/tiledb_sparse_write_global_1.c
  examples/c_api/tiledb_sparse_write_global_2.c
  examples/c_api/tiledb_sparse_write_unordered_1.c
  examples/c_api/tiledb_sparse_write_unordered_2.c
  test/src/unit-capi-any.cc
  test/src/unit-capi-async.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-incomplete.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-string.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/kv/kv_iter.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, API Breakage
