Repository TileDB-Inc/TileDB, pull requests merged in 2019-05, with the labels that each got.

#1219 Add support for single-step write to S3, instead of multi-part
  HISTORY.md
  doc/source/tutorials/working-with-s3.rst
  test/CMakeLists.txt
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-config.cc
  test/src/unit-s3-no-multipart.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: s3

#1240 Bump curl to v7.64.1
  cmake/Modules/FindAWSSDK_EP.cmake
  cmake/Modules/FindCurl_EP.cmake
Labels: build, s3

#1243 Add tiledb_buffer_t buffer get/set C API functions.
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-buffer.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
Labels: API Addition, C API, serialization

#1242 Work on SubarrayPartitioner
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-SubarrayPartitioner-dense.cc
  test/src/unit-SubarrayPartitioner-error.cc
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-capi-subarray_partitioner.cc
  test/src/unit-rtree.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/query/dense_cell_range_iter.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/subarray/subarray_partitioner.h
Labels: internals, tests

#1244 Minor bug in R-Tree unit test
  test/src/unit-rtree.cc
Labels: bug, tests

#1247 Fix memory leak in KV
  tiledb/sm/cpp_api/map.h
Labels: bug, key value

#1248 Fixed bug with sparse global order writes when the buffer sizes are zero
  HISTORY.md
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/query/writer.cc
Labels: backport, bug

#1252 Fix thread-safety issue when opening arrays.
  HISTORY.md
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
Labels: bug, internals, thread safety

#1256 Implemented a new cell slab iterator
  test/CMakeLists.txt
  test/src/unit-CellSlabIter.cc
  tiledb/CMakeLists.txt
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/subarray/cell_slab_iter.cc
  tiledb/sm/subarray/cell_slab_iter.h
Labels: enhancement, internals

#1262 Add serialization support
  CMakeLists.txt
  azure-pipelines.yml
  bootstrap
  cmake/Modules/FindCapnp_EP.cmake
  cmake/TileDB-Superbuild.cmake
  test/CMakeLists.txt
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-incomplete.cc
  test/src/unit-capi-rest-dense_array.cc
  test/src/unit-capi-serialized_queries.cc
  test/src/unit-uri.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/enums/filter_type.h
  tiledb/sm/enums/serialization_type.h
  tiledb/sm/global_state/global_state.cc
  tiledb/sm/global_state/libcurl_state.cc
  tiledb/sm/global_state/libcurl_state.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/stats_counters.h
  tiledb/sm/misc/status.cc
  tiledb/sm/misc/status.h
  tiledb/sm/misc/uri.cc
  tiledb/sm/misc/uri.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/capnp_utils.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, C API, serialization

#1270 Implement rule-of-5 for Buffer class
  test/src/unit-buffer.cc
  tiledb/sm/buffer/buffer.cc
  tiledb/sm/buffer/buffer.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/filter/filter_buffer.cc
  tiledb/sm/serialization/query.cc
Labels: internals

#1272 Update AWS SDK version to 1.7.108.
  cmake/Modules/FindAWSSDK_EP.cmake
Labels: s3

#1271 Add new tiledb_buffer_list_t datatype and API.
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/unit-bufferlist.cc
  tiledb/CMakeLists.txt
  tiledb/sm/buffer/buffer_list.cc
  tiledb/sm/buffer/buffer_list.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_struct_def.h
Labels: API Addition, C API

#1276 Disable HDFS tests in unit-capi-sparse_array.cc
  test/src/unit-capi-sparse_array.cc
Labels: CI, tests

#1273 Changes for zero-copy query serialization
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-incomplete.cc
  test/src/unit-capi-serialized_queries.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
Labels: C API, rest, serialization

#1275 Bug fix with amplification factor in consolidation. Closes #1274
  HISTORY.md
  test/src/unit-capi-consolidation.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: bug, consolidation

#1277 Implemented and thoroughly tested class ResultCellSlabIter
  scripts/azure-linux_mac.yml
  test/CMakeLists.txt
  test/src/unit-CellSlabIter.cc
  test/src/unit-Reader.cc
  test/src/unit-ResultCellSlabIter.cc
  test/src/unit-Subarray.cc
  test/src/unit-TileDomain.cc
  test/src/unit-capi-subarray.cc
  test/src/unit-cppapi-subarray.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/tile_domain.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/result_cell_slab.h
  tiledb/sm/query/result_cell_slab_iter.cc
  tiledb/sm/query/result_cell_slab_iter.h
  tiledb/sm/query/result_coords.h
  tiledb/sm/query/result_space_tile.h
  tiledb/sm/query/result_tile.h
  tiledb/sm/subarray/cell_slab.h
  tiledb/sm/subarray/cell_slab_iter.cc
  tiledb/sm/subarray/cell_slab_iter.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: enhancement, internals

#1279 Implement API and serialization of array max buffer sizes.
  test/src/unit-capi-rest-dense_array.cc
  tiledb/sm/array/array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
Labels: API Addition, C API, serialization

#1280 Automatically resubmit incomplete read queries to REST server
  test/src/unit-capi-rest-dense_array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: rest

#1281 Change serialization C APIs to allocate buffer objects
  test/src/unit-capi-array_schema.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_serialization.h
Labels: C API, serialization

#1283 Return libcurl error messages when possible.
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
Labels: error message, rest

#1284 Add C API for string conversion of enum values.
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-enum_values.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/enums/array_type.h
  tiledb/sm/enums/compressor.h
  tiledb/sm/enums/datatype.h
  tiledb/sm/enums/encryption_type.h
  tiledb/sm/enums/filesystem.h
  tiledb/sm/enums/filter_option.h
  tiledb/sm/enums/filter_type.h
  tiledb/sm/enums/layout.h
  tiledb/sm/enums/object_type.h
  tiledb/sm/enums/query_status.h
  tiledb/sm/enums/query_type.h
  tiledb/sm/enums/serialization_type.h
  tiledb/sm/enums/vfs_mode.h
  tiledb/sm/enums/walk_order.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
Labels: API Addition, C API

#1286 Add config param `vfs.file.enable_filelocks`.
  HISTORY.md
  doc/source/tutorials/config.rst
  test/src/unit-capi-array.cc
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
Labels: config param, vfs

#1288 Remove internal length limit on URIs.
  HISTORY.md
  test/src/unit-uri.cc
  test/src/unit-vfs.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/uri.cc
Labels: internals

#1289 Clamp filter chunk size to be minimum 1 cell.
  HISTORY.md
  test/src/unit-cppapi-array.cc
  tiledb/sm/filter/filter_pipeline.cc
Labels: backport, filters, internals

#1290 Allow disabling ssl validation for rest
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/rest/curl.cc
Labels: config param, rest
