Repository TileDB-Inc/TileDB, pull requests merged in 2019-11, with the labels that each got.

#1414 Doc fixes
  examples/c_api/async.c
  examples/c_api/config.c
  examples/c_api/encryption.c
  examples/c_api/errors.c
  examples/c_api/filters.c
  examples/c_api/fragments_consolidation.c
  examples/c_api/kv.c
  examples/c_api/multi_attribute.c
  examples/c_api/multi_range_subarray.c
  examples/c_api/object.c
  examples/c_api/quickstart_dense.c
  examples/c_api/quickstart_kv.c
  examples/c_api/quickstart_sparse.c
  examples/c_api/reading_dense_layouts.c
  examples/c_api/reading_incomplete.c
  examples/c_api/reading_sparse_layouts.c
  examples/c_api/using_tiledb_stats.c
  examples/c_api/variable_length.c
  examples/c_api/vfs.c
  examples/c_api/writing_dense_global.c
  examples/c_api/writing_dense_global_expansion.c
  examples/c_api/writing_dense_multiple.c
  examples/c_api/writing_dense_padding.c
  examples/c_api/writing_dense_sparse.c
  examples/c_api/writing_sparse_global.c
  examples/c_api/writing_sparse_multiple.c
  examples/cpp_api/async.cc
  examples/cpp_api/config.cc
  examples/cpp_api/encryption.cc
  examples/cpp_api/errors.cc
  examples/cpp_api/filters.cc
  examples/cpp_api/fragments_consolidation.cc
  examples/cpp_api/map.cc
  examples/cpp_api/multi_attribute.cc
  examples/cpp_api/multi_range_subarray.cc
  examples/cpp_api/object.cc
  examples/cpp_api/quickstart_dense.cc
  examples/cpp_api/quickstart_map.cc
  examples/cpp_api/quickstart_sparse.cc
  examples/cpp_api/reading_dense_layouts.cc
  examples/cpp_api/reading_incomplete.cc
  examples/cpp_api/reading_sparse_layouts.cc
  examples/cpp_api/using_tiledb_stats.cc
  examples/cpp_api/variable_length.cc
  examples/cpp_api/vfs.cc
  examples/cpp_api/writing_dense_global.cc
  examples/cpp_api/writing_dense_global_expansion.cc
  examples/cpp_api/writing_dense_multiple.cc
  examples/cpp_api/writing_dense_padding.cc
  examples/cpp_api/writing_dense_sparse.cc
  examples/cpp_api/writing_sparse_global.cc
  examples/cpp_api/writing_sparse_multiple.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/dimension.h
  tiledb/sm/cpp_api/query.h
Labels: docs

#1416 Allow zero-valued array metadata
  test/src/unit-capi-metadata.cc
  test/src/unit-cppapi-metadata.cc
  tiledb/sm/array/array.cc
  tiledb/sm/metadata/metadata.cc
Labels: internals

#1418 Fix query deserialization on buffers with offset != 0
  tiledb/sm/rest/rest_client.cc
Labels: rest, serialization

#1419 Add missing cases for datetime attr/dim serialization support.
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-rest-dense_array.cc
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/capnp_utils.h
Labels: rest, serialization

#1420 Add support for serialized global order reads
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-rest-dense_array.cc
  tiledb/sm/serialization/query.cc
Labels: rest, serialization

#1415 Removed KV (key-value) functionality
  HISTORY.md
  doc/source/c++-api.rst
  doc/source/c-api.rst
  examples/c_api/kv.c
  examples/c_api/object.c
  examples/c_api/quickstart_kv.c
  examples/cpp_api/map.cc
  examples/cpp_api/object.cc
  examples/cpp_api/quickstart_map.cc
  test/CMakeLists.txt
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-enum_values.cc
  test/src/unit-capi-kv.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-query_2.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-map.cc
  test/src/unit-cppapi-schema.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/map_schema.h
  tiledb/sm/cpp_api/object.h
  tiledb/sm/cpp_api/object_iter.h
  tiledb/sm/enums/object_type.h
  tiledb/sm/kv/kv.cc
  tiledb/sm/kv/kv.h
  tiledb/sm/kv/kv_item.cc
  tiledb/sm/kv/kv_item.h
  tiledb/sm/kv/kv_iter.cc
  tiledb/sm/kv/kv_iter.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Breakage, key value

#1421 Improve curl linkage and capnp compilation
  cmake/Modules/FindCapnp_EP.cmake
  tiledb/CMakeLists.txt
Labels: build, serialization

#1417 It should be ok to write to older-versioned arrays
  test/src/unit-backwards_compat.cc
  test/src/unit-capi-array.cc
  tiledb/sm/array/array.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: backwards-compatibility

#1423 Fix library soname on Linux.
  CMakeLists.txt
Labels: build

#1426 Remove incomplete check when resubmit_incomplete is true.
  tiledb/sm/rest/rest_client.cc
Labels: rest, serialization

#1427 Fix uninitialized variable warning.
  tiledb/sm/query/writer.cc
Labels: build

#1428 Update links in README.md.
  README.md
  doc/source/_static/tiledb-logo_color_@4x.png
  doc/source/conf.py
Labels: docs

#1430 Add logo with no margin.
  README.md
  doc/source/_static/tiledb-logo_color_no_margin_@4x.png
  doc/source/conf.py
Labels: docs

#1433 Improve REST retry logic, part 1
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
Labels: backport, rest, serialization

#1435 Update RTD API documentation pages
  doc/source/_static/favicon.ico
  doc/source/conf.py
  doc/source/gensidebar.py
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/introduction.rst
  doc/source/performance/introduction.rst
  doc/source/performance/performance-factors.rst
  doc/source/performance/using-tiledb-statistics.rst
  doc/source/quickstart.rst
  doc/source/real-world-examples/dense-image-data.rst
  doc/source/real-world-examples/sparse-geospatial-data.rst
  doc/source/tutorials/advanced-consolidation.rst
  doc/source/tutorials/array-metadata.rst
  doc/source/tutorials/async.rst
  doc/source/tutorials/compression.rst
  doc/source/tutorials/concurrency-consistency.rst
  doc/source/tutorials/config.rst
  doc/source/tutorials/datetimes.rst
  doc/source/tutorials/dense-arrays.rst
  doc/source/tutorials/encryption.rst
  doc/source/tutorials/errors.rst
  doc/source/tutorials/filters.rst
  doc/source/tutorials/format-description.rst
  doc/source/tutorials/fragments-consolidation.rst
  doc/source/tutorials/kv.rst
  doc/source/tutorials/multi-attribute-arrays.rst
  doc/source/tutorials/neg-real.rst
  doc/source/tutorials/object.rst
  doc/source/tutorials/parallelism.rst
  doc/source/tutorials/reading.rst
  doc/source/tutorials/sparse-arrays.rst
  doc/source/tutorials/tiling-dense.rst
  doc/source/tutorials/tiling-sparse.rst
  doc/source/tutorials/variable-length-attributes.rst
  doc/source/tutorials/vfs.rst
  doc/source/tutorials/working-with-hdfs.rst
  doc/source/tutorials/working-with-s3.rst
  doc/source/tutorials/writing-dense.rst
  doc/source/tutorials/writing-sparse.rst
  doc/source/usage.rst
Labels: backport, docs

#1434 Fix curl find_package: locate shared version first.
  cmake/Modules/FindCurl_EP.cmake
Labels: backport, build

#1438 Indicate empty metadata values by returning value_num == 1
  test/src/unit-capi-metadata.cc
  test/src/unit-cppapi-metadata.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/metadata/metadata.cc
Labels: C API, backport

#1440 CopyState double-free
  tiledb/sm/serialization/query.cc
Labels: backport, rest, serialization

#1439 Add tiledb_array_has_metadata_key function and C++ API
  HISTORY.md
  test/src/unit-capi-metadata.cc
  test/src/unit-cppapi-metadata.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
Labels: C API, backport

#1442 Consolidation bug with dense arrays and domains of non-integral space tiles
  HISTORY.md
  test/CMakeLists.txt
  test/src/unit-cppapi-array.cc
  test/src/unit-cppapi-consolidation.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/subarray_partitioner.cc
Labels: bug

#1443 Minor cleanup of the Writer class and some class renaming
  test/CMakeLists.txt
  test/src/unit-ReadCellSlabIter.cc
  tiledb/CMakeLists.txt
  tiledb/sm/misc/status.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/read_cell_slab_iter.cc
  tiledb/sm/query/read_cell_slab_iter.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/write_cell_slab_iter.cc
  tiledb/sm/query/write_cell_slab_iter.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: internals
