Repository TileDB-Inc/TileDB, pull requests merged in 2019-07, with the labels that each got.

#1328 Create versioned (soname) libtiledb on Linux
  CMakeLists.txt
  tiledb/CMakeLists.txt
Labels: build

#1329 Fix docs for `tiledb_dimension_alloc`.
  tiledb/sm/c_api/tiledb.h
Labels: docs

#1325 Mitigate S3::disconnect destructor slowdown path on Windows
  tiledb/sm/filesystem/s3.cc
Labels: s3

#1330 Track filelock fd in global count structure in order to release from any Ctx
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: process safety, vfs

#1332 Use context config in 'consolidate' by default
  HISTORY.md
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Breakage, C++ API

#1334 Improve query subarray bound checking error message
  tiledb/sm/query/query.h
Labels: error message

#1337 Missing spdlog include
  tiledb/sm/misc/logger.cc
Labels: build

#1335 No-op completed read query submissions
  tiledb/sm/query/query.cc
Labels: internals

#1341 Writes cannot be performed on arrays with a different version than the TileDB library
  test/src/unit-backwards_compat.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backwards-compatibility

#1340 Fix S3 windows build
  azure-pipelines.yml
  cmake/Modules/FindAWSSDK_EP.cmake
  scripts/azure-windows.yml
  scripts/install-minio.ps1
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-s3.cc
Labels: build, s3

#1342 Improve error message for invalid array URI
  tiledb/sm/misc/uri.cc
Labels: error message

#1350 Fix sign comparison error in posix.cc
  tiledb/sm/filesystem/posix.cc
Labels: build

#1355 Remove KV API usage from `impl::Deleter` class.
  HISTORY.md
  examples/cpp_api/map.cc
  examples/cpp_api/object.cc
  examples/cpp_api/quickstart_map.cc
  test/src/unit-cppapi-map.cc
  test/src/unit-cppapi-schema.cc
  tiledb/sm/cpp_api/deleter.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/map_schema.h
  tiledb/sm/cpp_api/tiledb
Labels: C++ API, deprecation, key value

#1352 Always build AWS SDK in release mode for gcc
  cmake/Modules/FindAWSSDK_EP.cmake
Labels: build

#1353 Add datetime dim support to test-backwards_compat
  test/src/unit-backwards_compat.cc
Labels: backwards-compatibility, tests

#1357 Fix tools build; add to CI
  azure-pipelines.yml
  bootstrap
  bootstrap.ps1
  scripts/azure-linux_mac.yml
  tools/CMakeLists.txt
  tools/src/commands/info_command.cc
Labels: CI, cli

#1358 Bug fix in incomplete query behavior
  HISTORY.md
  doc/source/tutorials/reading.rst
  examples/c_api/reading_incomplete.c
  examples/cpp_api/reading_incomplete.cc
  tiledb/sm/query/reader.cc
Labels: bug

#1359 Update history for 1.6.0 release
  HISTORY.md
Labels: backport

#1362 Fix two uninitialized variable warnings.
  tiledb/sm/filesystem/vfs.cc
Labels: backport, vfs
