Repository TileDB-Inc/TileDB, pull requests merged in 2019-04, with the labels that each got.

#1173 Disable 'S3ThreadPoolExecutor'
  tiledb/sm/filesystem/s3.cc
Labels: s3

#1170 Clean up after array-anon-attr test
  test/src/unit-cppapi-array.cc
Labels: tests

#1177 Two small docs-related fixes
  README.md
  scripts/install-clangformat.sh
  scripts/install-hadoop.sh
  scripts/install-minio.sh
  scripts/markdown-link-prs.sh
  scripts/run-hadoop.sh
  scripts/run-minio.sh
Labels: docs

#1174 Correct grammar in log message
  tiledb/sm/filesystem/vfs.cc
Labels: error message

#1179 Update HISTORY.md from a backlog of merged changes.
  HISTORY.md
Labels: docs

#1171 allow tiledb string types to typecheck against static char datatype
  test/src/unit-cppapi-type.cc
  tiledb/sm/cpp_api/exception.h
  tiledb/sm/cpp_api/type.h
Labels: C++ API

#1182 Fix infinite loop in S3::ls() when the 'delimiter' is empty
  HISTORY.md
  tiledb/sm/filesystem/s3.cc
Labels: bug, s3

#1190 Fix lambda-captured `uri` within VFS::read()
  tiledb/sm/filesystem/vfs.cc
Labels: backport, internals

#1191 Refactor 'cancel_all_tasks' out of 'ThreadPool'.
  test/src/unit-threadpool.cc
  tiledb/CMakeLists.txt
  tiledb/sm/filesystem/s3_thread_pool_executor.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/misc/cancelable_tasks.cc
  tiledb/sm/misc/cancelable_tasks.h
  tiledb/sm/misc/thread_pool.cc
  tiledb/sm/misc/thread_pool.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: internals

#1195 Add API functions to get the layout from a query.
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/unit-capi-query.cc
  test/src/unit-cppapi-query.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/query.h
Labels: API Addition, C API, C++ API

#1201 Fix std::string/Aws::String build issue
  tiledb/sm/filesystem/s3.cc
Labels: backport, build, s3

#1202 Add docs for s3 access/secret config settings
  doc/source/tutorials/config.rst
  doc/source/tutorials/working-with-s3.rst
Labels: docs

#1199 Remove conditional compilation on the '__cpu_model' in work_arounds.cc
  tiledb/sm/misc/work_arounds.cc
Labels: build, s3

#1208 Use *Ctx() methods for zstd compress/decompress.
  HISTORY.md
  tiledb/sm/compressors/zstd_compressor.cc
Labels: backport, bug, compressors

#1209 Better handling of C/CXXFLAGS and AVX2 flag setting.
  HISTORY.md
  bootstrap
  cmake/Modules/CheckAVX2Support.cmake
  cmake/Modules/FindZlib_EP.cmake
  cmake/Modules/FindZstd_EP.cmake
  cmake/TileDB-Superbuild.cmake
Labels: backport, build

#1210 Fix S3 debug build
  azure-pipelines.yml
  scripts/azure-linux_mac.yaml
  tiledb/sm/filesystem/s3_thread_pool_executor.cc
Labels: build, s3

#1213 Fix crash in consolidation due to accessing invalid/empty matrix entry
  HISTORY.md
  test/src/unit-cppapi-array.cc
  tiledb/sm/storage_manager/consolidator.cc
Labels: backport

#1215 Add tiledb_buffer_t C API.
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/unit-capi-buffer.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
Labels: API Addition, C API

#1216 Update python tutorial sections to remove Ctx uses
  doc/source/tutorials/advanced-consolidation.rst
  doc/source/tutorials/compression.rst
  doc/source/tutorials/concurrency-consistency.rst
  doc/source/tutorials/config.rst
  doc/source/tutorials/dense-arrays.rst
  doc/source/tutorials/filters.rst
  doc/source/tutorials/fragments-consolidation.rst
  doc/source/tutorials/kv.rst
  doc/source/tutorials/multi-attribute-arrays.rst
  doc/source/tutorials/neg-real.rst
  doc/source/tutorials/object.rst
  doc/source/tutorials/sparse-arrays.rst
  doc/source/tutorials/tiling-dense.rst
  doc/source/tutorials/vfs.rst
  doc/source/tutorials/writing-dense.rst
  doc/source/tutorials/writing-sparse.rst
Labels: backport, docs

#1218 Remove false assertion in S3::ls()
  tiledb/sm/filesystem/s3.cc
Labels: bug, s3

#1229 Optimize two functions in Domain class.
  HISTORY.md
  tiledb/sm/array_schema/domain.cc
Labels: internals, performance

#1233 Fix Windows build with S3 enabled
  cmake/Modules/FindAWSSDK_EP.cmake
  tiledb/CMakeLists.txt
Labels: Windows, build, s3

#1234 Refactor azure CI scripts; add Windows support
  .appveyor.yml
  README.md
  azure-pipelines.yml
  cmake/inputs/configure-curl.sh.in
  doc/local-build.sh
  scripts/azure-linux_mac.yaml
  scripts/azure-linux_mac.yml
  scripts/azure-windows.yml
  scripts/install-hadoop.sh
  scripts/install-minio.sh
  scripts/run-clang-format.sh
  scripts/run-hadoop.sh
  scripts/run-minio.sh
Labels: CI
