Repository TileDB-Inc/TileDB, pull requests merged in 2019-09, with the labels that each got.

#1377 Implement basic array metadata
  .gitignore
  HISTORY.md
  doc/source/c-api.rst
  doc/source/gensidebar.py
  doc/source/tutorials/array-metadata.rst
  doc/source/tutorials/dense-arrays.rst
  doc/source/tutorials/format-description.rst
  doc/source/tutorials/fragments-consolidation.rst
  doc/source/tutorials/multi-attribute-arrays.rst
  doc/source/tutorials/sparse-arrays.rst
  doc/source/tutorials/variable-length-attributes.rst
  doc/source/tutorials/writing-dense.rst
  doc/source/tutorials/writing-sparse.rst
  examples/c_api/array_metadata.c
  examples/cpp_api/array_metadata.cc
  test/CMakeLists.txt
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-Consolidator.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-metadata.cc
  test/src/unit-cppapi-array.cc
  test/src/unit-cppapi-metadata.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/tile/tile_io.cc
Labels: API Addition, new_feature

#1378 Bug fix in metadata overwrites and patch in consolidation
  test/src/unit-capi-metadata.cc
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/storage_manager/consolidator.cc
Labels: bug

#1385 Fix several unused variable warnings in unit tests.
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-vfs.cc
Labels: backport, tests

#1386 Set default rest server address
  test/src/unit-capi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: rest
