Repository TileDB-Inc/TileDB, pull requests merged in 2019-10, with the labels that each got.

#1391 Fix missing virtual destructor in c++ schema base
  tiledb/sm/cpp_api/schema_base.h
Labels: C++ API, build

#1392 Refactored Config and ConfigIter
  test/src/unit-SubarrayPartitioner-dense.cc
  test/src/unit-SubarrayPartitioner-error.cc
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-capi-config.cc
  test/src/unit-filter-pipeline.cc
  test/src/unit-hdfs-filesystem.cc
  test/src/unit-s3-no-multipart.cc
  test/src/unit-s3.cc
  test/src/unit-uuid.cc
  test/src/unit-vfs.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/config/config_iter.cc
  tiledb/sm/config/config_iter.h
  tiledb/sm/filesystem/hdfs_filesystem.cc
  tiledb/sm/filesystem/hdfs_filesystem.h
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/filesystem/win.cc
  tiledb/sm/filesystem/win.h
  tiledb/sm/global_state/global_state.cc
  tiledb/sm/global_state/global_state.h
  tiledb/sm/global_state/tbb_state.cc
  tiledb/sm/global_state/tbb_state.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/status.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/reader.cc
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/query.cc
  tiledb/sm/storage_manager/config.cc
  tiledb/sm/storage_manager/config.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/subarray/subarray_partitioner.h
Labels: enhancement, internals

#1394 Fix build with Apple Clang 11
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/filter.h
  tiledb/sm/cpp_api/filter_list.h
Labels: C++ API, build

#1393 Add runtime detection for CA Certs on Linux
  tiledb/sm/config/config.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/global_state/global_state.cc
  tiledb/sm/global_state/global_state.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: s3

#1395 Read optimization
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
Labels: enhancement, internals, performance

#1396 Added API functions to get information about the fragments written by a WRITE query.
  HISTORY.md
  doc/source/c-api.rst
  test/src/unit-capi-query_2.cc
  test/src/unit-cppapi-query.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/fragment/written_fragment_info.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: API Addition

#1399 Add TILEDB_LOG_OUTPUT_ON_FAILURE variable to improve CI debugging
  cmake/Modules/FindAWSSDK_EP.cmake
  cmake/Modules/FindBzip2_EP.cmake
  cmake/Modules/FindCapnp_EP.cmake
  cmake/Modules/FindCatch_EP.cmake
  cmake/Modules/FindClipp_EP.cmake
  cmake/Modules/FindCurl_EP.cmake
  cmake/Modules/FindLZ4_EP.cmake
  cmake/Modules/FindOpenSSL_EP.cmake
  cmake/Modules/FindSpdlog_EP.cmake
  cmake/Modules/FindTBB_EP.cmake
  cmake/Modules/FindZlib_EP.cmake
  cmake/Modules/FindZstd_EP.cmake
Labels: build

#1398 Use major.minor for SOVERSION instead of full major.minor.rev
  tiledb/CMakeLists.txt
Labels: build

#1401 Fix assertion failures in S3 tests; allow 'run-minio.sh' to be sourced
  scripts/run-minio.sh
  test/src/unit-s3-no-multipart.cc
  test/src/unit-s3.cc
Labels: build, tests

#1407 Bump Hadoop CI version to 3.1.3.
  scripts/install-hadoop.sh
Labels: CI, build, hadoop

#1406 Add ctx_set_tag C and C++ API functions.
  HISTORY.md
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/unit-ctx.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/context.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: API Addition, C API, C++ API

#1409 Set all context tags as headers on all REST requests.
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: rest

#1410 Prepend `X-` to default context tags.
  test/src/unit-ctx.cc
  tiledb/sm/cpp_api/context.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: rest

#1412 Fix metadata bug on GCC 4.8 w/ consecutive same-length keys
  tiledb/sm/metadata/metadata.cc
Labels: bug
