Repository TileDB-Inc/TileDB, pull requests merged in 2019-03, with the labels that each got.

#1141 Remove need to pre-allocate memory before checking for cache hit.
  test/src/unit-lru_cache.cc
  tiledb/sm/cache/lru_cache.cc
  tiledb/sm/cache/lru_cache.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: internals

#1151 Remove use of tile cache from TileIO class.
  tiledb/sm/tile/tile_io.cc
Labels: internals

#1153 Fix non-virtual destructors in C++ API.
  test/src/unit-cppapi-schema.cc
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/map_schema.h
Labels: C++ API, bug

#1156 Add various C++ API overloads to allow for `std::string` encryption keys
  HISTORY.md
  test/src/unit-cppapi-array.cc
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/map.h
  tiledb/sm/cpp_api/map_schema.h
Labels: API Addition, C++ API, docs

#1157 Add untyped C++ API overloads for Query::set_buffer.
  HISTORY.md
  tiledb/sm/cpp_api/query.h
Labels: API Addition, C++ API

#1160 doc: several small fixes
  doc/source/introduction.rst
  doc/source/quickstart.rst
  doc/source/tutorials/dense-arrays.rst
  doc/source/tutorials/writing-sparse.rst
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/query/query.h
Labels: docs

#1165 Add zlib dependency to awssdk
  cmake/Modules/FindAWSSDK_EP.cmake
Labels: build

#1159 Unblock 'S3::vfs_thread_pool_' worker threads for multipart upload requests
  tiledb/CMakeLists.txt
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/s3_thread_pool_executor.cc
  tiledb/sm/filesystem/s3_thread_pool_executor.h
Labels: internals, s3

#1166 Abort pending S3 multipart uploads on error path
  test/src/unit-s3.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/global_state/unit_test_config.h
  tiledb/sm/misc/macros.h
Labels: internals, s3
