Repository TileDB-Inc/TileDB, pull requests merged in 2019-12, with the labels that each got.

#1448 Several internal Metadata class tweaks:
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
Labels: backport, internals

#1449 Add support for getting/setting array metadata via REST.
  test/src/unit-capi-rest-dense_array.cc
  tiledb/sm/array/array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
Labels: backport, rest, serialization

#1452 Fix CURL cert file path override for REST
  tiledb/sm/rest/curl.cc
Labels: backport, rest

#1454 Towards splitting coordinates in separate buffers and files
  test/src/unit-capi-dense_array.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/types.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/tile/tile.cc
Labels: enhancement, internals

#1458 Set separate coordinate buffers to write queries
  HISTORY.md
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-CellSlabIter.cc
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-Reader.cc
  test/src/unit-Subarray.cc
  test/src/unit-SubarrayPartitioner-dense.cc
  test/src/unit-SubarrayPartitioner-error.cc
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-capi-async.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-dense_array_2.cc
  test/src/unit-capi-incomplete-2.cc
  test/src/unit-capi-incomplete.cc
  test/src/unit-capi-metadata.cc
  test/src/unit-capi-query_2.cc
  test/src/unit-capi-serialized_queries.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-string.cc
  test/src/unit-cppapi-metadata.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/types.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/query.cc
Labels: enhancement, internals

#1462 Split coordinates file into multiple files, one per dimension
  HISTORY.md
  test/src/unit-backwards_compat.cc
  test/src/unit-capi-consolidation.cc
  test/src/unit-cppapi-array.cc
  test/src/unit-cppapi-schema.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: disk format, enhancement, internals
