Repository TileDB-Inc/TileDB, pull requests merged in 2020-04, with the labels that each got.

#1579 Added string dimensions support
  HISTORY.md
  test/CMakeLists.txt
  test/src/helpers.cc
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-query_2.cc
  test/src/unit-capi-sparse_heter.cc
  test/src/unit-capi-string_dims.cc
  test/src/unit-cppapi-array.cc
  test/src/unit-rtree.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/types.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/result_coords.h
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
  tiledb/sm/query/writer.cc
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/rtree/rtree.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/capnp_utils.h
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray_partitioner.cc
Labels: API Addition, new_feature

#1586 Changed default thread configs
  test/src/unit-capi-config.cc
  tiledb/sm/config/config.cc
Labels: config param

#1589 Fixed bug with estimator in the presence of multi-range queries
  test/src/helpers.cc
  test/src/unit-SubarrayPartitioner-sparse.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray_partitioner.cc
Labels: bug, internals

#1588 Added consolidation test for internal domain expansion of dense arrays
  test/src/unit-cppapi-consolidation.cc
Labels: consolidation, missing test

#1590 Thread-safe Catch2 Macros:
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-rest-dense_array.cc
  test/src/unit-uuid.cc
Labels: bug, internals, tests

#1593 Add missing doc signatures
  doc/source/c-api.rst
  doc/source/conf.py
Labels: docs

#1594 Refactored stats, perf improvements and bug fixes
  test/CMakeLists.txt
  test/src/unit-capi-stats.cc
  test/src/unit-capi-string_dims.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-vfs.cc
  test/src/unit-win-filesystem.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/cache/lru_cache.cc
  tiledb/sm/compressors/bzip_compressor.cc
  tiledb/sm/compressors/dd_compressor.cc
  tiledb/sm/compressors/gzip_compressor.cc
  tiledb/sm/compressors/lz4_compressor.cc
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/compressors/zstd_compressor.cc
  tiledb/sm/crypto/crypto.cc
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/win.cc
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/misc/stats.cc
  tiledb/sm/misc/stats.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/query.cc
  tiledb/sm/stats/stats.cc
  tiledb/sm/stats/stats.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/tile/tile_io.cc
Labels: bug, performance, stats

#1596 Fixed bug in tile order computation for col-major tile orders
  test/src/unit-cppapi-array.cc
  tiledb/sm/array_schema/domain.cc
Labels: bug

#1597 Add range values to error msg for lower>upper
  tiledb/sm/array_schema/dimension.h
Labels: error message

#1601 Performance improvements and a bug fix with maximum memory budget calculation
  test/src/unit-SubarrayPartitioner-sparse.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/utils.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
  tiledb/sm/stats/stats.cc
  tiledb/sm/stats/stats.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/subarray_partitioner.cc
Labels: bug, performance

#1604 Added format specification description
  format_spec/FORMAT_SPEC.md
  format_spec/array_file_hierarchy.md
  format_spec/array_metadata.md
  format_spec/array_schema.md
  format_spec/consolidated_fragment_metadata_file.md
  format_spec/filter_pipeline.md
  format_spec/fragment.md
  format_spec/generic_tile.md
  format_spec/group_file_hierarchy.md
  format_spec/tile.md
  format_spec/vacuum_file.md
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/domain.cc
Labels: disk format

#1605 Performance improvement
  tiledb/sm/query/reader.cc
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
Labels: performance

#1606 Bug fix in reads due to latest refactoring
  tiledb/sm/query/result_tile.cc
Labels: bug, refactor

#1609 Added missing stats and some fixes
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/stats/stats.cc
  tiledb/sm/stats/stats.h
Labels: stats
