Repository TileDB-Inc/TileDB, pull requests merged in 2020-11, with the labels that each got.

#1880 Hilbert order, improvements and bug fixes
  HISTORY.md
  test/CMakeLists.txt
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-string_dims.cc
  test/src/unit-cppapi-hilbert.cc
  test/src/unit-dimension.cc
  test/src/unit-hilbert.cc
  test/src/unit-utils.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/dimension.h
  tiledb/sm/enums/layout.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/hilbert.h
  tiledb/sm/misc/types.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/result_coords.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/stats/stats.cc
  tiledb/sm/stats/stats.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/subarray/subarray_partitioner.h
Labels: bug, new_feature, performance

#1899 Bump AWS SDK dot-release
  HISTORY.md
  cmake/Modules/FindAWSSDK_EP.cmake
Labels: backport release-2.1

#1900 Added C and C++ APIs for retrieving detailed information about the fragments of an array
  HISTORY.md
  doc/source/c++-api.rst
  doc/source/c-api.rst
  test/CMakeLists.txt
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-capi-fragment_info.cc
  test/src/unit-cppapi-config.cc
  test/src/unit-cppapi-fragment_info.cc
  tiledb/CMakeLists.txt
  tiledb/common/status.cc
  tiledb/common/status.h
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/cpp_api/attribute.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/context.h
  tiledb/sm/cpp_api/core_interface.h
  tiledb/sm/cpp_api/deleter.h
  tiledb/sm/cpp_api/dimension.h
  tiledb/sm/cpp_api/domain.h
  tiledb/sm/cpp_api/exception.h
  tiledb/sm/cpp_api/fragment_info.h
  tiledb/sm/cpp_api/group.h
  tiledb/sm/cpp_api/object.h
  tiledb/sm/cpp_api/object_iter.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/cpp_api/schema_base.h
  tiledb/sm/cpp_api/tiledb
  tiledb/sm/cpp_api/type.h
  tiledb/sm/cpp_api/utils.h
  tiledb/sm/cpp_api/version.h
  tiledb/sm/cpp_api/vfs.h
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/fragment/single_fragment_info.h
  tiledb/sm/misc/types.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: new_feature

#1905 Fix narrowing conversion in Dimension::split_range and Dimension::ceil_to_tile
  HISTORY.md
  tiledb/sm/array_schema/dimension.cc
Labels: backport release-2.1

#1913 Fixes and documentation for config parameters
  HISTORY.md
  test/src/unit-capi-config.cc
  test/src/unit-capi-vfs.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/config/config.cc
  tiledb/sm/cpp_api/config.h
Labels: config param, docs

#1915 Disable more curl build options that we don't want
  cmake/Modules/FindCurl_EP.cmake
Labels: backport release-2.1, build, cmake

#1925 Calibrate the current partition in SubarrayPartitioner::split_current
  tiledb/sm/subarray/subarray_partitioner.cc
Labels: backport release-2.1

#1927 Using our OpenSSL from superbuild requires pkg-config
  cmake/Modules/FindCurl_EP.cmake
Labels: build
