Repository TileDB-Inc/TileDB, pull requests merged in 2020-01, with the labels that each got.

#1461 Don't re-export symbols from static libraries on Linux
  tiledb/CMakeLists.txt
Labels: build

#1466 Lazy array metadata fetching
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: backport, enhancement, internals

#1465 Refactoring towards splitting coordinates
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-Reader.cc
  test/src/unit-capi-sparse_array.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/read_cell_slab_iter.cc
  tiledb/sm/query/read_cell_slab_iter.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/result_cell_slab.h
  tiledb/sm/query/result_coords.h
  tiledb/sm/query/result_space_tile.h
  tiledb/sm/query/result_tile.h
  tiledb/sm/query/writer.cc
Labels: internals

#1463 Fix forward declarations on array and array schema
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-Tile.cc
  test/src/unit-filter-pipeline.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/array_schema/tile_domain.h
  tiledb/sm/filter/bitshuffle_filter.cc
  tiledb/sm/filter/byteshuffle_filter.cc
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/query/query.h
  tiledb/sm/query/read_cell_slab_iter.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/subarray/cell_slab_iter.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/tile/tile.cc
Labels: internals

#1479 Add support for http compression of REST requests
  cmake/Modules/FindCurl_EP.cmake
  cmake/Modules/FindZlib_EP.cmake
  test/src/unit-capi-config.cc
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/rest/curl.cc
Labels: backport, rest

#1481 Reader now works without zipping the coordinates
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-Reader.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
Labels: internals, refactor

#1485 Avoid unused serialization of array metadata
  tiledb/sm/array/array.cc
Labels: metadata
