Repository TileDB-Inc/TileDB, pull requests merged in 2020-12, with the labels that each got.

#1963 Optimize ResultTile::compute_results_sparse<char>
  tiledb/sm/query/reader.cc
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
Labels: backport release-2.1

#1966 Fix GCS read-ahead
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-capi-vfs.cc
  test/src/unit-gcs.cc
  test/src/unit-vfs.cc
  test/src/vfs_helpers.cc
  test/src/vfs_helpers.h
  tiledb/sm/filesystem/gcs.cc
Labels: backport release-2.1

#1969 Fix segfault in optimized compute_results_sparse
  HISTORY.md
  tiledb/sm/query/result_tile.cc
Labels: backport release-2.1

#1975 Optimize consolidated fragment metadata loading
  HISTORY.md
  tiledb/sm/fragment/fragment_metadata.cc
Labels: backport release-2.1, consolidation

#1976 Optimize Reader::load_tile_offsets for only relevant fragments
  HISTORY.md
  tiledb/sm/query/reader.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: backport release-2.1, internals

#1979 Optimize FragmentMetadata::load_tile_offsets and FragmentMetadata::load_tile_var_offsets
  HISTORY.md
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
Labels: backport release-2.1, internals

#1981 Fix segfault in ResultTile::str_coord_intersects
  HISTORY.md
  tiledb/sm/query/result_tile.cc
Labels: backport release-2.1, internals

#1985 Limit CI runs of backwards compatibility checks
  azure-pipelines.yml
  scripts/azure-linux_mac.yml
  scripts/azure-windows.yml
Labels: CI, backport release-2.1

#1984 Exit early in copy_attribute_values when empty res
  HISTORY.md
  tiledb/sm/query/reader.cc
Labels: backport release-2.1, internals

#1983 use SubarrayPartitioner->current() for load_tile_offsets
  HISTORY.md
  tiledb/sm/query/reader.cc
Labels: backport release-2.1, internals
