Repository TileDB-Inc/TileDB, pull requests merged in 2020-07, with the labels that each got.

#1710 Add new config option `vfs.file.posix_permissions`
  HISTORY.md
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
Labels: backport release-2.0.6, vfs

#1712 Source built curl only need HTTP support
  HISTORY.md
  cmake/Modules/FindCurl_EP.cmake
Labels: build

#1715 Only install docker if it does not exist for CI
  scripts/install-minio.sh
Labels: CI, backport release-2.0.6

#1714 Check ENV for config values with config_iter
  HISTORY.md
  test/src/unit-cppapi-config.cc
  tiledb/sm/config/config_iter.cc
  tiledb/sm/config/config_iter.h
Labels: backport release-2.0.6, config param

#1719 Split folder and directory posix permission config
  HISTORY.md
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
Labels: vfs

#1732 Fix compute_mbr for var-sized dimensions
  HISTORY.md
  tiledb/sm/array_schema/dimension.cc
Labels: backport release-2.0.7, bug

#1736 Sort cell slab ranges for ND arrays
  HISTORY.md
  tiledb/sm/query/reader.cc
Labels: backport release-2.0.7

#1733 Fix detection of system installs of Catch2
  HISTORY.md
  cmake/Modules/FindCatch_EP.cmake
Labels: backport release-2.0.7, bug, build

#1741 Use TileDB-detected CA cert file for GCS
  HISTORY.md
  tiledb/sm/filesystem/gcs.cc
Labels: backport release-2.0.7

#1739 Fix size_t 8-byte assumption
  tiledb/sm/filter/filter_pipeline.cc
Labels: backport release-2.0.7, bug

#1740 GCC 10.1 now includes avx intrinsics
  HISTORY.md
  external/src/blosc/shuffle-avx2.cc
Labels: backport release-2.0.7, build

#1748 Fix undefined behavior within load_tile_var_sizes
  HISTORY.md
  tiledb/sm/subarray/subarray.cc
Labels: TBB, backport release-2.0.7, bug, thread safety

#1752 Improve initialization safety for GCS and VFS
  HISTORY.md
  tiledb/sm/filesystem/gcs.cc
  tiledb/sm/filesystem/gcs.h
Labels: backport release-2.0.8
