Repository TileDB-Inc/TileDB, pull requests merged in 2020-10, with the labels that each got.

#1841 consolidate_metadata bug fix
  tiledb/sm/cpp_api/array.h
Labels: C++ API, backport release-2.1

#1844 Fix C++ API consolidate_metadata incorrect config
  HISTORY.md
  tiledb/sm/cpp_api/array.h
Labels: C++ API, backport release-2.1

#1849 Ensure non-zero estimates can contain at least one cell
  HISTORY.md
  test/src/unit-capi-query_2.cc
  test/src/unit-cppapi-subarray.cc
  tiledb/sm/subarray/subarray.cc
Labels: backport release-2.1

#1857 Pin CI Python to v3.8.
  scripts/azure-linux_mac.yml
  scripts/azure-windows.yml
Labels: backport release-2.1

#1856 Set the AWS SDK HttpOptions::installSigPipeHandler.
  tiledb/sm/filesystem/s3.cc
Labels: backport release-2.1

#1860 Writer should serialize Subarray object
  HISTORY.md
  test/src/unit-capi-serialized_queries.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
Labels: backport release-2.1, rest, serialization

#1868 Adjust fill in value support for issue with REST
  HISTORY.md
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/attribute.h
Labels: backport release-2.1

#1871 LRUCache::insert() bugs
  HISTORY.md
  tiledb/sm/cache/lru_cache.h
Labels: backport release-2.1
