Repository TileDB-Inc/TileDB, pull requests merged in 2020-02, with the labels that each got.

#1486 Post metadata to REST only if metadata exists
  tiledb/sm/array/array.cc
Labels: backport, metadata, rest

#1504 Added support for enabling coordinate duplicates for sparse arrays
  HISTORY.md
  test/CMakeLists.txt
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-capi-array_schema.cc
  test/src/unit-cppapi-schema.cc
  test/src/unit-duplicates.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array_schema.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
  tiledb/sm/subarray/subarray.cc
Labels: API Addition, enhancement, new_feature

#1507 Adds support for writing at a timestamp. Closes #1490
  HISTORY.md
  test/src/unit-capi-array.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/array/array.cc
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: enhancement, time travel

#1509 Refactoring towards addressing #93
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-Reader.cc
  test/src/unit-TileDomain.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/array_schema/tile_domain.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/types.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/read_cell_slab_iter.cc
  tiledb/sm/query/read_cell_slab_iter.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/result_space_tile.h
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: internals

#1514 Refactored R-Tree towards addressing #93
  test/src/unit-rtree.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/rtree/rtree.cc
  tiledb/sm/rtree/rtree.h
  tiledb/sm/subarray/subarray.cc
  tools/src/commands/info_command.cc
  tools/src/commands/info_command.h
Labels: internals, refactor

#1516 Refactored Consolidator towards addressing #93
  test/src/unit-capi-consolidation.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/misc/utils.cc
  tiledb/sm/misc/utils.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: internals, refactor

#1518 Refactored Subarray and SubarrayPartitioner towards addressing #93
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/misc/types.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/subarray/subarray_partitioner.h
Labels: internals, refactor
