Repository TileDB-Inc/TileDB, pull requests merged in 2021-01, with the labels that each got.

#1992 Fix [ch3077]: cannot read empty var-length cells at 2D tile boundary
  test/CMakeLists.txt
  test/src/unit-empty-var-length.cc
  tiledb/sm/tile/chunked_buffer.cc
Labels: backport release-2.1

#1994 Fix thread-pool deadlock
  test/src/unit-threadpool.cc
  tiledb/common/thread_pool.cc
  tiledb/common/thread_pool.h
Labels: backport release-2.1

#1999 Update HISTORY.md for #1994
  HISTORY.md
Labels: backport release-2.1

#2007 Bump patch version to 2.2.2
  doc/source/conf.py
  tiledb/sm/c_api/tiledb_version.h
Labels: backport release-2.2

#2011 Fix nullable fill value example in c-api
  tiledb/sm/c_api/tiledb.h
Labels: backport release-2.2

#2015 Add TILEDB_EXPORT to C API tiledb_query_add_range_by_name
  tiledb/sm/c_api/tiledb.h
Labels: backport release-2.2

#1919 Cache cloud service redirection URIs
  HISTORY.md
  test/CMakeLists.txt
  test/src/unit-capi-rest-dense_array.cc
  test/src/unit-curl.cc
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
Labels: backport release-2.2

#2025 Add support for REST header for credential name
  HISTORY.md
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/rest/rest_client.cc
Labels: backport release-2.2

#2028 Move sm/misc/macros.h to common/macros.h
  tiledb/common/macros.h
  tiledb/common/thread_pool.h
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/cache/lru_cache.h
  tiledb/sm/filesystem/mem_filesystem.cc
  tiledb/sm/filesystem/mem_filesystem.h
  tiledb/sm/filesystem/s3_thread_pool_executor.h
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/global_state/libcurl_state.cc
  tiledb/sm/global_state/tbb_state.cc
  tiledb/sm/global_state/unit_test_config.h
  tiledb/sm/query/query_buffer.h
  tiledb/sm/query/validity_vector.h
  tiledb/sm/subarray/subarray_partitioner.cc
Labels: backport release-2.2

#2033 Fix serializing nullable attribute
  tiledb/sm/serialization/array_schema.cc
Labels: backport release-2.2

#2037 ArrowAdapter updates
  HISTORY.md
  test/CMakeLists.txt
  test/src/unit-arrow.cc
  tiledb/sm/cpp_api/arrow_io_impl.h
Labels: backport release-2.2

#2040 [Arrow] fix ArrowAdapter format selection with TILEDB_CHAR for var of…
  HISTORY.md
  test/src/unit-arrow.cc
  test/src/unit_arrow.py
  tiledb/sm/cpp_api/arrow_io_impl.h
Labels: backport release-2.2

#2045 Bump patch version to 2.2.3
  doc/source/conf.py
  tiledb/sm/c_api/tiledb_version.h
Labels: backport release-2.2

#2048 Parallelize closing of files on write
  HISTORY.md
  tiledb/sm/query/writer.cc
Labels: backport release-2.2, internals

#2053 Fix race in timer stats
  tiledb/sm/stats/timer_stat.cc
  tiledb/sm/stats/timer_stat.h
Labels: backport release-2.2

#2050 Remove is_dir from `FragmentMetadata::store`
  HISTORY.md
  tiledb/sm/fragment/fragment_metadata.cc
Labels: backport release-2.2, internals, s3

#2061 Load ArraySchema in parallel to listing fragments
  HISTORY.md
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.2, internals

#2060 Add support for REST http requests to retry
  HISTORY.md
  test/src/unit-capi-config.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/misc/utils.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
  tiledb/sm/stats/stats.cc
  tiledb/sm/stats/stats.h
Labels: backport release-2.2, rest

#2066 Update HISTORY for 2.2.3 release
  HISTORY.md
Labels: backport release-2.2
