Repository TileDB-Inc/TileDB, pull requests merged in 2021-11, with the labels that each got.

#2581 Add tiledb_fragment_info_get_schema_name
  test/src/unit-capi-fragment_info.cc
  test/src/unit-cppapi-fragment_info.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/fragment_info.h
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/fragment_info.h
Labels: backport release-2.5

#2579 Remove deprecate tiledb_array_max_buffer_size
  doc/source/c-api.rst
  examples/png_ingestion/src/main.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
Labels: backport release-2.5

#2582 Set github release to use ubuntu-latest
  azure-pipelines.yml
Labels: backport release-2.5

#2591 Enable CMake AVX2 check
  cmake/Modules/CheckAVX2Support.cmake
Labels: backport release-2.5

#2589 Run github actions on all branches, not just PRs
  .github/workflows/build-macOS10.14-GCS.yml
  .github/workflows/build-macOS10.14-S3.yml
  .github/workflows/build-ubuntu16.04-HDFS.yml
  .github/workflows/build-ubuntu20.04-AZURE.yml
  .github/workflows/build-ubuntu20.04-GCS.yml
  .github/workflows/build-ubuntu20.04-S3.yml
  .github/workflows/build-ubuntu20.04-SERIALIZATION.yml
Labels: backport release-2.5

#2551 Use ROW_MAJOR read paths for unordered reads of Hilbert layout array
  test/src/unit-cppapi-hilbert.cc
  tiledb/sm/subarray/subarray.cc
Labels: backport release-2.4, backport release-2.5

#2596 Revert "Run github actions on all branches, not just PRs"
  .github/workflows/build-macOS10.14-GCS.yml
  .github/workflows/build-macOS10.14-S3.yml
  .github/workflows/build-ubuntu16.04-HDFS.yml
  .github/workflows/build-ubuntu20.04-AZURE.yml
  .github/workflows/build-ubuntu20.04-GCS.yml
  .github/workflows/build-ubuntu20.04-S3.yml
  .github/workflows/build-ubuntu20.04-SERIALIZATION.yml
Labels: backport release-2.5

#2611 Fix handling schema evolution for v1/v2 fragments
  test/src/unit-capi-array_schema.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.5

#2614 Disable AVX2 on MSys2 builds (which are only for CRAN)
  .github/workflows/mingw-w64-tiledb/PKGBUILD
Labels: backport release-2.5

#2608 Unordered reads should be allowed for dense arrays
  tiledb/sm/query/query.cc
Labels: backport release-2.5

#2609 Add cpp api for Context::last_error()
  examples/cpp_api/errors.cc
  tiledb/CMakeLists.txt
  tiledb/sm/cpp_api/deleter.h
  tiledb/sm/cpp_api/error.h
  tiledb/sm/cpp_api/tiledb
Labels: backport release-2.5

#2580 Clarify error messages for set_data_buffer and set_offset_buffer
  tiledb/sm/query/query.cc
Labels: backport release-2.5

#2625 Fix logger creation on context to be threadsafe
  tiledb/sm/storage_manager/context.cc
  tiledb/sm/storage_manager/context.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: backport release-2.5

#2645 Sparse global order reader: memory management unit tests.
  test/CMakeLists.txt
  test/src/unit-cppapi-subarray.cc
  test/src/unit-sparse-global-order-reader.cc
  tiledb/sm/query/sparse_global_order_reader.cc
  tiledb/sm/query/sparse_global_order_reader.h
Labels: backport release-2.5

#2643 Sparse refactored readers: better parallelization for tile bitmaps.
  tiledb/sm/query/query.cc
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
  tiledb/sm/query/sparse_global_order_reader.cc
  tiledb/sm/query/sparse_index_reader_base.cc
  tiledb/sm/query/sparse_index_reader_base.h
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.5

#2649 Generalize linux build to current default plus a new no-avx2 build
  azure-pipelines.yml
  scripts/azure-linux_mac-release.yml
Labels: backport release-2.5

#2658 Error out when setting multiple ranges for global layout
  test/src/unit-capi-dense_array_2.cc
  test/src/unit-cppapi-subarray.cc
  tiledb/sm/subarray/subarray.cc
Labels: backport release-2.5

#2613 Always load array schemas during opening
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-backwards_compat.cc
  test/src/unit-capi-sparse_array.cc
  tiledb/common/status.h
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/query/dense_tiler.cc
  tiledb/sm/query/dense_tiler.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/read_cell_slab_iter.cc
  tiledb/sm/query/strategy_base.cc
  tiledb/sm/query/writer.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema_evolution.h
  tiledb/sm/serialization/capnp_utils.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/open_array.cc
  tiledb/sm/storage_manager/open_array.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
  tiledb/sm/subarray/cell_slab_iter.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/subarray_partitioner.cc
  tools/src/commands/info_command.cc
Labels: backport release-2.5

#2667 Fix handling checking config for refactored reader
  tiledb/sm/query/query.cc
  tiledb/sm/serialization/config.cc
Labels: backport release-2.5, backport release-2.6
