Repository TileDB-Inc/TileDB, pull requests merged in 2021-04, with the labels that each got.

#2167 Add c/c++ api for getting config from query
  HISTORY.md
  test/src/unit-capi-query_2.cc
  test/src/unit-cppapi-var-offsets.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
Labels: C API, C++ API, backport release-2.2

#2162 Add config option to bound read ranges to domain
  HISTORY.md
  test/src/helpers.cc
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-subarray.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/reader.cc
  tiledb/sm/query/reader.h
  tiledb/sm/query/writer.cc
  tiledb/sm/query/writer.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: backport release-2.2

#2164 Add support for config serialization
  HISTORY.md
  test/src/unit-cppapi-config.cc
  tiledb/CMakeLists.txt
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/serialization/capnp_utils.h
  tiledb/sm/serialization/config.cc
  tiledb/sm/serialization/config.h
  tiledb/sm/serialization/tiledb-rest.capnp
Labels: backport release-2.2, serialization

#2179 Fix various memory leaks in unit tests
  HISTORY.md
  test/src/unit-SubarrayPartitioner-sparse.cc
  test/src/unit-bufferlist.cc
  test/src/unit-capi-array.cc
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-async.cc
  test/src/unit-capi-attributes.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-dense_neg.cc
  test/src/unit-capi-dense_vector.cc
  test/src/unit-capi-metadata.cc
  test/src/unit-capi-nullable.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-query.cc
  test/src/unit-capi-query_2.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-capi-sparse_neg.cc
  test/src/unit-capi-sparse_neg_2.cc
  test/src/unit-capi-sparse_real.cc
  test/src/unit-capi-sparse_real_2.cc
  test/src/unit-capi-string_dims.cc
  test/src/unit-empty-var-length.cc
  test/src/unit-filter-pipeline.cc
  test/src/vfs_helpers.cc
Labels: tests

#2178 C-API error path leak in tiledb_config_alloc
  HISTORY.md
  tiledb/sm/c_api/tiledb.cc
Labels: C API, backport release-2.2

#2183 Misc. mem leaks
  HISTORY.md
  test/src/unit-ChunkedBuffer.cc
  test/src/unit-Tile.cc
  test/src/unit-filter-pipeline.cc
Labels: backport release-2.2

#2196 Consolidate supports nullable attributes
  HISTORY.md
  tiledb/sm/query/reader.cc
  tiledb/sm/storage_manager/consolidator.cc
Labels: backport release-2.2

#2185 Fix memory leak in filter pipeline
  HISTORY.md
  tiledb/sm/filter/filter_pipeline.cc
Labels: backport release-2.2, internals

#2189 Fix leak in S3 VFS read
  tiledb/sm/filesystem/s3.cc
Labels: backport release-2.2, s3

#2177 Add config to query serialization
  tiledb/sm/serialization/config.cc
  tiledb/sm/serialization/config.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/tiledb-rest.capnp
Labels: backport release-2.2, serialization

#2216 Optimize `Subarray::compute_relevant_fragments`
  test/src/unit-Subarray.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: backport release-2.2

#2228 Support TILEDB_DATETIME_{SEC,MS,US,NS} in arrow_io_impl.h
  tiledb/sm/cpp_api/arrow_io_impl.h
Labels: backport release-2.2
