Repository TileDB-Inc/TileDB, pull requests merged in 2022-10, with the labels that each got.

#3550 add c_api tiledb_group_get_is_relative_uri_by_name()
  test/src/unit-capi-group.cc
  test/src/unit-cppapi-group.cc
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/c_api/tiledb_group.cc
  tiledb/sm/cpp_api/group_experimental.h
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
Labels: backport release-2.12

#3477 Class VFS C.41 compliance, Part 1
  test/src/unit-vfs.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/test/compile_vfs_main.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: pending-2.13

#3554 Misc CI fixes
  .github/workflows/ci-linux_mac.yml
  .github/workflows/full-ci-dummy.yml
  .github/workflows/full-ci.yml
Labels: backport release-2.12

#3530 Fragment info serialization support
  test/src/serialization_wrappers.cc
  test/src/serialization_wrappers.h
  test/src/unit-backwards_compat.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-fragment_info.cc
  test/src/unit-cppapi-array.cc
  test/src/unit-cppapi-fragment_info.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array_directory.cc
  tiledb/sm/array/array_directory.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/consolidator/array_meta_consolidator.cc
  tiledb/sm/consolidator/commits_consolidator.cc
  tiledb/sm/consolidator/consolidator.cc
  tiledb/sm/consolidator/consolidator.h
  tiledb/sm/consolidator/fragment_consolidator.cc
  tiledb/sm/consolidator/fragment_meta_consolidator.cc
  tiledb/sm/consolidator/group_meta_consolidator.cc
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/fragment_info.h
  tiledb/sm/enums/serialization_type.h
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/fragment/single_fragment_info.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/array.h
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/fragment_info.cc
  tiledb/sm/serialization/fragment_info.h
  tiledb/sm/serialization/fragment_metadata.cc
  tiledb/sm/serialization/fragment_metadata.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: backport release-2.12

#3565 Remove stale declarations from query
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
Labels: backport release-2.12

#3572 CI fixes for release builds and cURL
  .github/workflows/full-ci-dummy.yml
  .github/workflows/full-ci.yml
  cmake/Modules/FindCurl_EP.cmake
Labels: backport release-2.12

#3557 Global order writes should send relative uris over serialization
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/query/writers/global_order_writer.cc
  tiledb/sm/query/writers/global_order_writer.h
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/fragment_info.cc
  tiledb/sm/serialization/fragment_metadata.cc
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.12

#3504 update to catch2 ver3
  CMakeLists.txt
  cmake/Modules/FindCatch_EP.cmake
  test/CMakeLists.txt
  test/ci/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/performance/msys_handle_leakage/unit-cppapi-consolidation-with-timestamps.cc
  test/performance/msys_handle_leakage/unit.cc
  test/regression/CMakeLists.txt
  test/src/unit-azure.cc
  test/src/unit-capi-array_schema.cc
  test/src/unit-capi-error.cc
  test/src/unit-capi-object_mgmt.cc
  test/src/unit-capi-update-queries.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-cppapi-array-deletes.cc
  test/src/unit-cppapi-array.cc
  test/src/unit-cppapi-xor-filter.cc
  test/src/unit-filter-serialization.cc
  test/src/unit-status.cc
  test/src/unit.cc
  test/src/vfs_helpers.h
  test/support/tdb_catch.h
  tiledb/api/c_api/config/test/CMakeLists.txt
  tiledb/api/c_api/config/test/unit_capi_config.cc
  tiledb/api/c_api/error/test/CMakeLists.txt
  tiledb/api/c_api/error/test/unit_capi_error.cc
  tiledb/api/c_api_support/handle/test/CMakeLists.txt
  tiledb/common/CMakeLists.txt
  tiledb/common/dynamic_memory/CMakeLists.txt
  tiledb/common/exception/CMakeLists.txt
  tiledb/common/governor/CMakeLists.txt
  tiledb/common/interval/CMakeLists.txt
  tiledb/common/interval/test/unit_interval.h
  tiledb/common/thread_pool/CMakeLists.txt
  tiledb/common/types/CMakeLists.txt
  tiledb/sm/array/test/CMakeLists.txt
  tiledb/sm/array/test/unit_consistency.cc
  tiledb/sm/array_schema/CMakeLists.txt
  tiledb/sm/array_schema/test/unit_array_schema.cc
  tiledb/sm/array_schema/test/unit_dimension_label_reference.cc
  tiledb/sm/buffer/test/CMakeLists.txt
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/compressors/CMakeLists.txt
  tiledb/sm/config/test/CMakeLists.txt
  tiledb/sm/cpp_api/type.h
  tiledb/sm/filesystem/CMakeLists.txt
  tiledb/sm/filter/CMakeLists.txt
  tiledb/sm/metadata/CMakeLists.txt
  tiledb/sm/misc/CMakeLists.txt
  tiledb/sm/query/CMakeLists.txt
  tiledb/sm/query/ast/CMakeLists.txt
  tiledb/sm/query/deletes_and_updates/CMakeLists.txt
  tiledb/sm/subarray/test/unit_range_subset.cc
  tiledb/storage_format/serialization/CMakeLists.txt
  tiledb/storage_format/serialization/test/main.cc
  tiledb/storage_format/serialization/test/unit_serializers.cc
  tiledb/type/range/test/CMakeLists.txt
  tiledb/type/range/test/unit_range.cc
  tiledb/type/range/test/unit_range_str.cc
Labels: in progress, pending-2.13

#3580 Add `tiledb_status_code`
  tiledb/api/c_api/api_external_common.h
  tiledb/sm/c_api/tiledb.cc
Labels: backport release-2.12

#3591 Fix duplicate logger instantiations when using libtiledbsoma with tiledb-py
  tiledb/common/logger.cc
  tiledb/common/logger.h
  tiledb/sm/storage_manager/context.cc
  tiledb/sm/storage_manager/context.h
Labels: backport release-2.12

#3593 Sparse readers: adding relevant cells stats.
  tiledb/sm/query/readers/sparse_global_order_reader.cc
  tiledb/sm/query/readers/sparse_index_reader_base.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.12

#3492 Read tiles: refactor tile creation code.
  test/src/unit-DenseTiler.cc
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-Tile.cc
  test/src/unit-filter-pipeline.cc
  test/src/unit-result-coords.cc
  test/src/unit-result-tile.cc
  test/src/unit-tile-metadata-generator.cc
  test/src/unit-vfs.cc
  tiledb/common/common-std.h
  tiledb/sm/array/array_directory.cc
  tiledb/sm/array/array_directory.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/dimension_label/dimension_label.cc
  tiledb/sm/filter/compression_filter.h
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/fragment/single_fragment_info.h
  tiledb/sm/group/group_directory.cc
  tiledb/sm/group/group_directory.h
  tiledb/sm/group/group_member_v1.h
  tiledb/sm/group/group_v1.cc
  tiledb/sm/group/group_v1.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/readers/ordered_dim_label_reader.cc
  tiledb/sm/query/readers/reader_base.cc
  tiledb/sm/query/readers/reader_base.h
  tiledb/sm/query/readers/result_tile.cc
  tiledb/sm/query/readers/result_tile.h
  tiledb/sm/query/readers/sparse_global_order_reader.cc
  tiledb/sm/query/readers/sparse_global_order_reader.h
  tiledb/sm/query/readers/sparse_index_reader_base.cc
  tiledb/sm/query/readers/sparse_index_reader_base.h
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.h
  tiledb/sm/query/test/unit_query_condition.cc
  tiledb/sm/query/writers/dense_tiler.cc
  tiledb/sm/query/writers/global_order_writer.cc
  tiledb/sm/query/writers/ordered_writer.cc
  tiledb/sm/query/writers/unordered_writer.cc
  tiledb/sm/query/writers/writer_base.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/tile/generic_tile_io.cc
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/sm/tile/writer_tile.cc
  tiledb/sm/tile/writer_tile.h
  tiledb/storage_format/uri/generate_uri.cc
  tiledb/storage_format/uri/generate_uri.h
  tools/src/commands/info_command.cc
Labels: pending-2.13
