Repository TileDB-Inc/TileDB, pull requests merged in 2022-05, with the labels that each got.

#3127 varying_size_datum_at: fixing comparison error.
  tiledb/sm/query/query_buffer.h
Labels: backport release-2.9

#3135 Dimension::dimension_ptr, part 1
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/domain_buffer.h
Labels: backport release-2.9

#3122 adjust assert for problematic var_size_ Range usage after earlier changes
  tiledb/type/range/range.h
Labels: backport release-2.9

#3149 Filter pipeline: fixing empty pipeline, multi chunk, refactored queries.
  tiledb/sm/filter/filter_pipeline.cc
Labels: backport release-2.7, backport release-2.8, backport release-2.9

#3150 Sparse global order reader: prevent dims from being unfiltered twice.
  tiledb/sm/query/sparse_global_order_reader.cc
Labels: backport release-2.9

#3099 Anticipatory version of C++23 `std::unreachable()`
  tiledb/common/unreachable.h
Labels: ready-to-merge

#3158 Changes test_assert path used to locate try_assert
  test/ci/CMakeLists.txt
  test/ci/test_assert.cc
Labels: ready-to-merge

#3161 Unordered writer: fixing segfault for empty writes.
  test/src/unit-cppapi-updates.cc
  tiledb/sm/query/global_order_writer.cc
  tiledb/sm/query/unordered_writer.cc
Labels: backport release-2.9

#3173 Sparse global order reader: refactor merge algorithm.
  test/CMakeLists.txt
  test/src/unit-result-coords.cc
  test/src/unit-result-tile.cc
  test/src/unit-sparse-global-order-reader.cc
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/hilbert_order.cc
  tiledb/sm/query/hilbert_order.h
  tiledb/sm/query/result_coords.h
  tiledb/sm/query/result_tile.h
  tiledb/sm/query/sparse_global_order_reader.cc
  tiledb/sm/query/sparse_global_order_reader.h
  tiledb/sm/query/sparse_index_reader_base.cc
  tiledb/sm/query/sparse_index_reader_base.h
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
  tiledb/sm/query/sparse_unordered_with_dups_reader.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: backport release-2.9

#3181 Sparse unordered w/ dups reader: fixing overflow on int value.
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.8, backport release-2.9

#3179 relocate magic_mgc_gzipped.bin for build
  tiledb/CMakeLists.txt
Labels: backport release-2.9

#3170 Sparse global order reader: Check correct incomplete reason in case of too small user buffer
  test/src/unit-capi-incomplete.cc
  test/src/unit-capi-string_dims.cc
  test/src/unit-sparse-global-order-reader.cc
  tiledb/sm/enums/query_status_details.h
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.9
