Repository TileDB-Inc/TileDB, pull requests merged in 2022-06, with the labels that each got.

#3216 Special case tiledb cloud uris to use row_major writes
  tiledb/sm/c_api/tiledb_filestore.cc
Labels: backport release-2.9

#3236 Apply TILEDB_NO_API_DEPRECATION_WARNINGS to C++ API
  tiledb/sm/cpp_api/tiledb
Labels: backport release-2.9

#3250 Support TILEDB_BLOB in tiledb::sm::utils::parse::to_str
  tiledb/sm/misc/parse_argument.cc
Labels: backport release-2.10, backport release-2.9

#3083 QueryCondition OR support: Implement serialization support of the AST
  test/CMakeLists.txt
  test/src/ast_helpers.cc
  test/src/ast_helpers.h
  test/src/unit-QueryCondition-serialization.cc
  test/src/unit-capi-smoke-test.cc
  tiledb/CMakeLists.txt
  tiledb/sm/enums/query_condition_combination_op.h
  tiledb/sm/enums/query_condition_op.h
  tiledb/sm/query/dense_reader.cc
  tiledb/sm/query/query_condition.cc
  tiledb/sm/query/query_condition.h
  tiledb/sm/query/test/unit_query_condition.cc
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: pending-2.10

#3256 Add missing filters to switch case for Filter serialization
  tiledb/sm/serialization/array_schema.cc
Labels: backport release-2.10, backport release-2.9

#3207 Use sparse global ordered reader for unordered queries with no dups.
  test/src/helpers.cc
  test/src/helpers.h
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-hilbert.cc
  test/src/unit-cppapi-subarray.cc
  test/src/unit-result-coords.cc
  test/src/unit-sparse-global-order-reader.cc
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/hilbert_order.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/result_coords.h
  tiledb/sm/query/result_tile.h
  tiledb/sm/query/sparse_global_order_reader.cc
  tiledb/sm/query/sparse_global_order_reader.h
  tiledb/sm/serialization/query.cc
Labels: pending-2.11

#3205 Dense reader: improving parallelization.
  tiledb/CMakeLists.txt
  tiledb/sm/query/dense_reader.cc
  tiledb/sm/query/dense_reader.h
  tiledb/sm/query/read_cell_slab_iter.cc
  tiledb/sm/query/result_space_tile.h
  tiledb/sm/subarray/cell_slab_iter.cc
  tiledb/sm/subarray/cell_slab_iter.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/tile_cell_slab_iter.cc
  tiledb/sm/subarray/tile_cell_slab_iter.h
  tiledb/type/range/range.h
Labels: pending-2.11

#3222 C API rewrite for filter and filter list
  test/src/unit-capi-filter.cc
  tiledb/common/exception/exception.h
  tiledb/common/logger.cc
  tiledb/common/logger_public.h
  tiledb/sm/c_api/api_argument_validator.cc
  tiledb/sm/c_api/api_argument_validator.h
  tiledb/sm/c_api/api_exception_safety.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/filter/filter_create.cc
  tiledb/sm/storage_manager/context.cc
  tiledb/sm/storage_manager/context.h
Labels: pending-2.11

#3263 Optimize compute_results_count_sparse_string.
  test/src/unit-result-tile.cc
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
Labels: backport release-2.10

#3220 Fix error reporting in tiledb_subarray_alloc
  tiledb/sm/c_api/api_argument_validator.h
  tiledb/sm/c_api/tiledb.cc
Labels: backport release-2.10, pending-2.11

#3240 Produce a TileDBConfigVersion.cmake file
  .github/workflows/build-windows.yml
  examples/cmake_project/CMakeLists.txt
  examples/png_ingestion/CMakeLists.txt
  test/packaging/CMakeLists.txt
  tiledb/CMakeLists.txt
Labels: backport release-2.10

#3264 QueryCondition OR support broke overlapping ranges
  test/src/unit-cppapi-consolidation-with-timestamps.cc
  tiledb/sm/query/ast/query_ast.h
  tiledb/sm/query/query_condition.cc
  tiledb/sm/query/test/unit_query_condition.cc
Labels: backport release-2.10, pending-2.11

#3273 Remove incorrect noexcept annotations from C API implementations in t…
  tiledb/sm/c_api/tiledb_filestore.cc
Labels: backport release-2.10

#3215 Writer: implement WriterTileVector.
  test/src/unit-DenseTiler.cc
  test/src/unit-tile-metadata-generator.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/query/dense_tiler.cc
  tiledb/sm/query/dense_tiler.h
  tiledb/sm/query/global_order_writer.cc
  tiledb/sm/query/global_order_writer.h
  tiledb/sm/query/ordered_writer.cc
  tiledb/sm/query/ordered_writer.h
  tiledb/sm/query/unordered_writer.cc
  tiledb/sm/query/unordered_writer.h
  tiledb/sm/query/writer_base.cc
  tiledb/sm/query/writer_base.h
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/sm/tile/tile_metadata_generator.cc
  tiledb/sm/tile/tile_metadata_generator.h
  tiledb/sm/tile/writer_tile.cc
  tiledb/sm/tile/writer_tile.h
Labels: pending-2.11

#3284 Fix ByteshuffleFilter in filter_constructor
  tiledb/sm/serialization/array_schema.cc
Labels: backport release-2.10, backport release-2.9

#3280 Bump libmagic/file-windows SHA to 37762ed878a741ff717b03d0f68d7742968e91a6 to …
  cmake/Modules/FindMagic_EP.cmake
Labels: backport release-2.10

#3057 augment logged error messages with more information
  tiledb/sm/filesystem/win.cc
Labels: pending-2.11

#3298 Remove unnecessary static storage duration on GCS internal variables
  tiledb/sm/filesystem/gcs.cc
Labels: backport release-2.10

#3292 fix timestamp_no_ms() for 32bit
  tiledb/sm/misc/tdb_time.cc
Labels: pending-2.11

#3310 Add backward compatibility arrays to CI matrix for 2.8 and 2.9
  .github/workflows/build-ubuntu20.04-backwards-compatibility.yml
Labels: backport release-2.10

#3314 compute_results_count_sparse_string: using cached ranges properly.
  tiledb/sm/query/readers/result_tile.cc
Labels: backport release-2.10

#3301 fix example compilation errors, augment CI running them
  .github/workflows/build-macOS11-GCS.yml
  .github/workflows/build-macOS11-S3.yml
  .github/workflows/build-ubuntu16.04-HDFS.yml
  .github/workflows/build-ubuntu20.04-AZURE.yml
  .github/workflows/build-ubuntu20.04-GCS.yml
  .github/workflows/build-ubuntu20.04-SERIALIZATION.yml
  .github/workflows/build-ubuntu22.04-S3.yml
  .github/workflows/build-windows.yml
  examples/CMakeLists.txt
  examples/c_api/CMakeLists.txt
  scripts/run-nix-examples.sh
Labels: pending-2.11
