Repository TileDB-Inc/TileDB, pull requests merged in 2022-07, with the labels that each got.

#3335 Correct typo in argument string
  tiledb/sm/config/config.cc
Labels: backport release-2.10

#3347 Sparse without dups unordered uses indexreader
  tiledb/sm/serialization/query.cc
Labels: backport release-2.10

#3308 Bug Fix: Wrong results when using OR condition with nullable attributes
  test/regression/CMakeLists.txt
  test/regression/targets/sc-18836.cc
  tiledb/sm/query/query_condition.cc
  tiledb/sm/query/query_condition.h
  tiledb/sm/query/test/unit_query_condition.cc
Labels: backport release-2.10, pending-2.11, backport release-2.11

#3332 Result tile with bitmaps: make attributes private.
  test/src/unit-result-coords.cc
  test/src/unit-result-tile.cc
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/sm/query/legacy/reader.cc
  tiledb/sm/query/query_condition.cc
  tiledb/sm/query/query_condition.h
  tiledb/sm/query/readers/result_coords.h
  tiledb/sm/query/readers/result_tile.h
  tiledb/sm/query/readers/sparse_global_order_reader.cc
  tiledb/sm/query/readers/sparse_global_order_reader.h
  tiledb/sm/query/readers/sparse_index_reader_base.cc
  tiledb/sm/query/readers/sparse_index_reader_base.h
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.h
  tiledb/sm/query/test/unit_query_condition.cc
Labels: pending-2.12

#3331 Sparse global order reader: merge algorithm optimization.
  test/src/unit-result-coords.cc
  tiledb/sm/query/readers/result_coords.h
Labels: pending-2.12

#3359 Fix SC-19287: segfault due to deref nonexistent filestore key
  test/src/unit-capi-filestore.cc
  tiledb/sm/c_api/tiledb_filestore.cc
Labels: backport release-2.10, backport release-2.11

#3375 Use zlib from tiledb-deps-mirror with fallback
  cmake/Modules/FindZlib_EP.cmake
Labels: backport release-2.10, backport release-2.11

#3357 Azure: parallelize remove_dir.
  tiledb/sm/filesystem/azure.cc
Labels: pending-2.12

#3362 Demonstrating mingw handle leakage (tiledb_unit extract)
  .github/workflows/mingw-w64-tiledb/PKGBUILD
  test/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/performance/msys_handle_leakage/notes.txt
  test/performance/msys_handle_leakage/trials.bat
  test/performance/msys_handle_leakage/trials.sh
  test/performance/msys_handle_leakage/unit-cppapi-consolidation-with-timestamps.cc
  test/performance/msys_handle_leakage/unit.cc
Labels: pending-2.12

#3218 array_schema_from_capnp C.41 conversion
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/enums/array_type.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
Labels: pending-2.12

#3364 Experimental build format version validation
  test/inputs/arrays/experimental_array_vUINT32_MAX/__fragments/__1657562300109_1657562300109_8dc3a927a28e445080d5dfd288825e1d_4294967295.ok
  test/inputs/arrays/experimental_array_vUINT32_MAX/__fragments/__1657562300109_1657562300109_8dc3a927a28e445080d5dfd288825e1d_4294967295/__fragment_metadata.tdb
  test/inputs/arrays/experimental_array_vUINT32_MAX/__fragments/__1657562300109_1657562300109_8dc3a927a28e445080d5dfd288825e1d_4294967295/a0.tdb
  test/inputs/arrays/experimental_array_vUINT32_MAX/__schema/__1657562300107_1657562300107_634feb310ce6426796198decd5dbddbf
  test/src/unit-cppapi-array.cc
  tiledb/sm/misc/CMakeLists.txt
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: pending-2.12

#3360 Fix and regression test for SC-19240
  test/regression/CMakeLists.txt
  test/regression/targets/sc-19240_cppapi-vfs-exception.cc
  test/src/unit-capi-filestore.cc
  tiledb/sm/cpp_api/vfs.h
Labels: pending-2.12

#3378 Deletes: adding support for commits consolidation.
  format_spec/consolidated_commits_file.md
  test/src/unit-cppapi-deletes.cc
  tiledb/sm/array/array_directory.cc
  tiledb/sm/array/array_directory.h
  tiledb/sm/consolidator/commits_consolidator.cc
Labels: pending-2.12

#3294 Float Scaling Filter Serialization
  test/CMakeLists.txt
  test/src/unit-cppapi-float-scaling-filter.cc
  test/src/unit-filter-serialization.cc
  tiledb/sm/filter/filter_create.cc
  tiledb/sm/filter/float_scaling_filter.cc
  tiledb/sm/filter/float_scaling_filter.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: pending-2.11, backport release-2.11

#3394 Sparse refactored readers, mark empty fragments as fully loaded early.
  tiledb/sm/query/readers/sparse_index_reader_base.cc
Labels: backport release-2.10, backport release-2.11

#3379 Serialization: improvements around query serialization/deserialization.
  tiledb/sm/serialization/query.cc
Labels: pending-2.12
