Repository TileDB-Inc/TileDB, pull requests merged in 2022-11, with the labels that each got.

#3539 Implement delete_array API
  test/CMakeLists.txt
  test/src/unit-cppapi-array-deletes.cc
  test/src/unit-cppapi-deletes.cc
  test/support/src/helpers.cc
  test/support/src/helpers.h
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager_canonical.h
Labels: pending-2.13

#3620 Sparse global order reader: fixing incomplete reason for rest queries.
  tiledb/sm/query/readers/sparse_global_order_reader.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.11, backport release-2.12

#3631 move return statement back after C.41 fix
  tiledb/sm/serialization/array_schema.cc
Labels: backport release-2.12

#3635 Dense consolidation: set correct non-empty domain.
  test/src/unit-capi-fragment_info.cc
  tiledb/sm/consolidator/fragment_consolidator.cc
  tiledb/sm/query/writers/global_order_writer.cc
  tiledb/sm/query/writers/writer_base.cc
Labels: backport release-2.12

#3645 Dense arrays: var size metadata not loaded on read
  test/src/unit-tile-metadata.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/query/readers/dense_reader.cc
Labels: backport release-2.12, backport release-2.13

#3646 Updates dimension label C-API
  test/CMakeLists.txt
  test/src/experimental_helpers.cc
  test/src/experimental_helpers.h
  test/src/test-capi-array-many-dimension-labels.cc
  test/src/test-capi-dense-array-dimension-label-var.cc
  test/src/test-capi-dense-array-dimension-label.cc
  test/src/test-capi-dimension_labels.cc
  test/src/test-capi-sparse-array-dimension-label.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/dimension_label_reference.h
  tiledb/sm/array_schema/test/unit_array_schema.cc
  tiledb/sm/c_api/experimental/api_exception_safety.h
  tiledb/sm/c_api/experimental/tiledb_dimension_label.cc
  tiledb/sm/c_api/experimental/tiledb_dimension_label.h
  tiledb/sm/c_api/experimental/tiledb_struct_def.h
Labels: pending-2.14

#3611 Adds dimension labels and data order to file format
  format_spec/FORMAT_SPEC.md
  format_spec/array_schema.md
  test/CMakeLists.txt
  test/src/experimental_helpers.cc
  test/src/experimental_helpers.h
  test/src/test-capi-array-many-dimension-labels.cc
  test/src/test-capi-dense-array-dimension-label-var.cc
  test/src/test-capi-dense-array-dimension-label.cc
  test/src/test-capi-dimension_labels.cc
  test/src/test-capi-sparse-array-dimension-label.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/array_schema/dimension_label_reference.cc
  tiledb/sm/array_schema/dimension_label_reference.h
  tiledb/sm/array_schema/dimension_label_schema.cc
  tiledb/sm/array_schema/dimension_label_schema.h
  tiledb/sm/array_schema/test/unit_array_schema.cc
  tiledb/sm/array_schema/test/unit_array_schema_helper.h
  tiledb/sm/array_schema/test/unit_dimension_label_reference.cc
  tiledb/sm/array_schema/test/unit_dimension_label_schema.cc
  tiledb/sm/c_api/experimental/api_exception_safety.h
  tiledb/sm/c_api/experimental/tiledb_dimension_label.cc
  tiledb/sm/c_api/experimental/tiledb_dimension_label.h
  tiledb/sm/c_api/experimental/tiledb_enum_experimental.h
  tiledb/sm/c_api/experimental/tiledb_struct_def.h
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/dimension_label/dimension_label.cc
  tiledb/sm/dimension_label/dimension_label.h
  tiledb/sm/enums/data_order.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/dimension_label/array_dimension_label_queries.cc
  tiledb/sm/query/dimension_label/dimension_label_query.cc
  tiledb/sm/subarray/subarray.cc
Labels: pending-2.14

#3674 Sparse global order reader: fix tile cleanup when ending an iteration.
  tiledb/sm/query/readers/sparse_global_order_reader.cc
Labels: backport release-2.11, backport release-2.12, backport release-2.13

#3610 Add deprecation policy; announce upcoming removal of deprecated functions in 2.15
  .github/workflows/build-docs.yml
  .github/workflows/full-ci-dummy.yml
  .github/workflows/full-ci.yml
  .readthedocs.yml
  HISTORY.md
  cmake/TileDB-Superbuild.cmake
  doc/README.md
  doc/policy/api_changes.md
  doc/source/conda-env.yml
  scripts/ci/build_docs.sh
  scripts/prepare_release.py
  tiledb/doxygen/Doxyfile.mk
  tiledb/doxygen/README.md
  tiledb/doxygen/local-build.sh
  tiledb/doxygen/mainpage.dox
  tiledb/doxygen/source/_static/custom.css
  tiledb/doxygen/source/_static/custom.js
  tiledb/doxygen/source/_static/favicon.ico
  tiledb/doxygen/source/_static/tileDB_uppercase_600_112.png
  tiledb/doxygen/source/_static/tileDB_uppercase_white_600_141.png
  tiledb/doxygen/source/_static/tiledb-logo_color_@4x.png
  tiledb/doxygen/source/_static/tiledb-logo_color_no_margin_@4x.png
  tiledb/doxygen/source/c++-api.rst
  tiledb/doxygen/source/c-api.rst
  tiledb/doxygen/source/conf.py
  tiledb/doxygen/source/figures/Scarlet-Macaw-small.png
  tiledb/doxygen/source/gensidebar.py
  tiledb/doxygen/source/index.rst
  tiledb/doxygen/source/requirements.txt
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_experimental.h
Labels: backport release-2.13

#3681 Disable LIBSSH2 in curl build
  cmake/Modules/FindCurl_EP.cmake
Labels: backport release-2.13
