Repository TileDB-Inc/TileDB, pull requests merged in 2022-03, with the labels that each got.

#2930 Global order writer: initialize last_var_offsets_.
  tiledb/sm/query/global_order_writer.cc
Labels: backport release-2.7

#2924 Sparse unordered w/ dups reader: fixing memory management for tiles.
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/sm/query/reader_base.cc
  tiledb/sm/query/reader_base.h
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
  tiledb/sm/query/sparse_unordered_with_dups_reader.h
Labels: backport release-2.7

#2945 Update Location of Zlib Download URL
  cmake/Modules/FindZlib_EP.cmake
Labels: backport release-2.6, backport release-2.7

#2953 Tile medatada: treating TILEDB_CHAR as TILEDB_STRING_ASCII.
  test/src/unit-tile-metadata-generator.cc
  tiledb/sm/tile/tile_metadata_generator.cc
  tiledb/sm/tile/tile_metadata_generator.h
Labels: backport release-2.7

#2799 Convert filterpipeline deserialize to factory
  CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/filter/CMakeLists.txt
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/filter/test/unit_filter_pipeline.cc
  tiledb/sm/tile/generic_tile_io.cc
Labels: pending-2.9

#2784 Convert metadata deserialize to factory
  CMakeLists.txt
  tiledb/sm/array_schema/test/unit_dimension.cc
  tiledb/sm/filesystem/CMakeLists.txt
  tiledb/sm/metadata/CMakeLists.txt
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
  tiledb/sm/metadata/test/main.cc
  tiledb/sm/metadata/test/unit_metadata.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: pending-2.9

#2942 Remove `class StatusCode`
  tiledb/CMakeLists.txt
  tiledb/common/CMakeLists.txt
  tiledb/common/status.cc
  tiledb/common/status.h
  tiledb/common/status_code.cc
  tiledb/common/status_code.h
Labels: pending-2.9

#2944 lums/new thread pool three
  .github/workflows/unit-test-runs.yml
  CMakeLists.txt
  bootstrap
  cmake/TileDB-Superbuild.cmake
  test/CMakeLists.txt
  test/src/unit-threadpool.cc
  tiledb/CMakeLists.txt
  tiledb/common/status.h
  tiledb/common/thread_pool.h
  tiledb/common/thread_pool/CMakeLists.txt
  tiledb/common/thread_pool/legacy_thread_pool.cc
  tiledb/common/thread_pool/legacy_thread_pool.h
  tiledb/common/thread_pool/producer_consumer_queue.h
  tiledb/common/thread_pool/test/unit_thread_pool.cc
  tiledb/common/thread_pool/thread_pool.cc
  tiledb/common/thread_pool/thread_pool.h
  tiledb/sm/filesystem/azure.cc
  tiledb/sm/misc/CMakeLists.txt
  tiledb/sm/query/reader.cc
  tiledb/sm/subarray/subarray.cc
Labels: pending-2.9

#2963 Global order writer: fixing multi writes for var size attributes.
  test/src/unit-capi-string_dims.cc
  tiledb/sm/query/global_order_writer.cc
Labels: backport release-2.8

#2948 Smart pointer conversion: ArraySchema Domain
  test/src/unit-QueryCondition.cc
  test/src/unit-ReadCellSlabIter.cc
  test/src/unit-Reader.cc
  test/src/unit-filter-pipeline.cc
  test/src/unit-rtree.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/fragment_info.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/misc/comparators.h
  tiledb/sm/query/dense_reader.cc
  tiledb/sm/query/dense_reader.h
  tiledb/sm/query/read_cell_slab_iter.h
  tiledb/sm/query/result_tile.cc
  tiledb/sm/query/result_tile.h
  tiledb/sm/rtree/rtree.cc
  tiledb/sm/rtree/rtree.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/query.cc
  tiledb/sm/storage_manager/consolidator.cc
  tiledb/sm/storage_manager/consolidator.h
  tools/src/commands/info_command.cc
  tools/src/commands/info_command.h
Labels: pending-2.9

#2961 Declare all C API functions noexcept.
  tiledb/sm/c_api/api_exception_safety.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/cpp_api/core_interface.h
  tiledb/sm/enums/datatype.h
Labels: pending-2.9

#2937 Refactor tiledb::sm::serialization::attribute_from_capnp (C41)
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema_evolution.cc
  tiledb/sm/serialization/capnp_utils.h
Labels: pending-2.9

#2981 Fixing build errors using MacOSX12.3.sdk.
  tiledb/sm/cpp_api/deleter.h
  tiledb/sm/filesystem/vfs.cc
Labels: backport release-2.8

#2983 Fixing compute_results_count_sparse_string for multiple range threads.
  tiledb/sm/query/result_tile.cc
Labels: backport release-2.6, backport release-2.7, backport release-2.8

#2979 Update backwards compatibility array for TileDB 2.7.0
  .github/workflows/build-ubuntu20.04-backwards-compatibility.yml
Labels: backport release-2.8

#2993 Global writes: fixing OOM on write continuation.
  tiledb/sm/fragment/fragment_metadata.cc
Labels: backport release-2.7, backport release-2.8

#2969 Do not store offsets when RLE is used on string dimensions
  test/src/unit-capi-fragment_info.cc
  test/src/unit-compression-rle.cc
  test/src/unit-cppapi-fragment_info.cc
  test/src/unit-cppapi-string-dims.cc
  test/src/unit-filter-pipeline.cc
  tiledb/sm/compressors/rle_compressor.h
  tiledb/sm/filter/bit_width_reduction_filter.cc
  tiledb/sm/filter/bit_width_reduction_filter.h
  tiledb/sm/filter/bitshuffle_filter.cc
  tiledb/sm/filter/bitshuffle_filter.h
  tiledb/sm/filter/byteshuffle_filter.cc
  tiledb/sm/filter/byteshuffle_filter.h
  tiledb/sm/filter/checksum_md5_filter.cc
  tiledb/sm/filter/checksum_md5_filter.h
  tiledb/sm/filter/checksum_sha256_filter.cc
  tiledb/sm/filter/checksum_sha256_filter.h
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/compression_filter.h
  tiledb/sm/filter/encryption_aes256gcm_filter.cc
  tiledb/sm/filter/encryption_aes256gcm_filter.h
  tiledb/sm/filter/filter.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/filter/noop_filter.cc
  tiledb/sm/filter/noop_filter.h
  tiledb/sm/filter/positive_delta_filter.cc
  tiledb/sm/filter/positive_delta_filter.h
  tiledb/sm/query/reader_base.cc
  tiledb/sm/query/writer_base.cc
  tiledb/sm/tile/generic_tile_io.cc
Labels: backport release-2.8

#2984 Replace hardcoded bytesizes in RLE for strings with dynamically inferred
  test/src/unit-compression-rle.cc
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/compressors/rle_compressor.h
  tiledb/sm/filter/compression_filter.cc
Labels: backport release-2.8

#2926 Smart pointer conversion: ArraySchema Dimension
  test/src/unit-QueryCondition.cc
  test/src/unit-Reader.cc
  test/src/unit-filter-pipeline.cc
  test/src/unit-rtree.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/subarray/subarray.cc
Labels: pending-2.9

#2943 Refactor tiledb::sm::serialization::filter_pipeline_from_capnp (C41)
  tiledb/sm/serialization/array_schema.cc
Labels: pending-2.9

#2977 Add FragmentInfo::get_fragment_name API
  examples/c_api/fragment_info.c
  examples/cpp_api/fragment_info.cc
  test/src/unit-capi-fragment_info.cc
  test/src/unit-cppapi-fragment_info.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/fragment_info.h
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/fragment_info.h
Labels: pending-2.9

#2800 Convert domain deserialize to factory
  test/CMakeLists.txt
  test/src/unit-domain.cc
  test/src/unit-rtree.cc
  tiledb/sm/array_schema/CMakeLists.txt
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
Labels: pending-2.9

#3002 Dense reader: fix user buffer offset computation for multi-index queries.
  test/src/unit-capi-dense_array.cc
  tiledb/sm/query/dense_reader.cc
  tiledb/sm/query/dense_reader.h
Labels: backport release-2.7, backport release-2.8

#3024 More tests for string RLE
  test/src/unit-compression-rle.cc
  test/src/unit-cppapi-filter.cc
  test/src/unit-cppapi-string-dims.cc
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/filter/test/unit_filter_pipeline.cc
Labels: backport release-2.8

#3023 Sparse unordered w/ dups reader: coord tiles management fix.
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.8
