Repository TileDB-Inc/TileDB, pull requests merged in 2022-08, with the labels that each got.

#3382 Reduce the number of requests in dir_size
  tiledb/common/filesystem/directory_entry.h
  tiledb/sm/filesystem/azure.cc
  tiledb/sm/filesystem/gcs.cc
  tiledb/sm/filesystem/hdfs_filesystem.cc
  tiledb/sm/filesystem/mem_filesystem.cc
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/win.cc
Labels: pending-2.12, backport release-2.11

#3403 Fix generated capnp c++ file for posix
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
Labels: backport release-2.11

#3434 Dense reader: adding num tiles to stats.
  tiledb/sm/query/readers/dense_reader.cc
Labels: backport release-2.11

#3432 Opt-in core-to-REST-server instrumentation
  tiledb/sm/config/config.h
  tiledb/sm/rest/curl.cc
  tiledb/sm/rest/curl.h
Labels: backport release-2.11

#3461 [build] Update libmagic tag (fix for arm64 mac in conda-forge feedstock)
  cmake/Modules/FindMagic_EP.cmake
Labels: backport release-2.11

#3473 Clear orphan stats when deserializing.
  tiledb/sm/query/query.cc
Labels: backport release-2.11

#3431 Bugfix for preparation of magic.mgc data (#3430)
  tiledb/CMakeLists.txt
Labels: backport release-2.11

#3326 Add C API doc for tiledb_array_upgrade_version
  doc/source/c++-api.rst
  doc/source/c-api.rst
  doc/source/conf.py
  tiledb/sm/c_api/tiledb_experimental.h
Labels: pending-2.12

#3488 Adjust dockerfile so layers can be cached better
  examples/Dockerfile/Dockerfile
Labels: backport release-2.11

#3351 Updates: adding update value APIs.
  test/CMakeLists.txt
  test/src/unit-capi-config.cc
  test/src/unit-capi-update-queries.cc
  test/src/unit-cppapi-update-queries.cc
  tiledb/CMakeLists.txt
  tiledb/common/exception/status.h
  tiledb/sm/array/array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/cpp_api/query.h
  tiledb/sm/cpp_api/query_experimental.h
  tiledb/sm/enums/query_type.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/update_value.cc
  tiledb/sm/query/update_value.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/storage_manager/storage_manager.h
Labels: pending-2.12
