Repository TileDB-Inc/TileDB, pull requests merged in 2022-04, with the labels that each got.

#3015 Incorrect validity result count in REST query
  tiledb/sm/rest/rest_client.cc
Labels: backport release-2.8

#2971 Add virtual filesystem ls_with_sizes
  test/src/unit-azure.cc
  test/src/unit-gcs.cc
  test/src/unit-hdfs-filesystem.cc
  test/src/unit-s3.cc
  test/src/unit-vfs.cc
  tiledb/common/filesystem/directory_entry.h
  tiledb/common/filesystem/path.h
  tiledb/sm/filesystem/azure.cc
  tiledb/sm/filesystem/azure.h
  tiledb/sm/filesystem/gcs.cc
  tiledb/sm/filesystem/gcs.h
  tiledb/sm/filesystem/hdfs_filesystem.cc
  tiledb/sm/filesystem/hdfs_filesystem.h
  tiledb/sm/filesystem/mem_filesystem.cc
  tiledb/sm/filesystem/mem_filesystem.h
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/filesystem/win.cc
  tiledb/sm/filesystem/win.h
Labels: pending-2.9

#3062 Global writer: fixing write continuation for fixed sized attributes.
  tiledb/sm/query/global_order_writer.cc
Labels: backport release-2.8

#3065 tiledb_serialize_array_metadata should load metadata
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_group.cc
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/group.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.8

#3068 Add support for group members to have names
  examples/c_api/groups.c
  examples/cpp_api/groups.cc
  test/src/serialization_wrappers.cc
  test/src/unit-capi-group.cc
  test/src/unit-cppapi-group.cc
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/c_api/tiledb_group.cc
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/cpp_api/group_experimental.h
  tiledb/sm/cpp_api/object.h
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
  tiledb/sm/group/group_member.cc
  tiledb/sm/group/group_member.h
  tiledb/sm/group/group_member_v1.cc
  tiledb/sm/group/group_member_v1.h
  tiledb/sm/serialization/group.cc
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: backport release-2.8

#2932 avoid some currently invalid vector references
  test/src/unit-rtree.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/query/dense_reader.cc
  tiledb/sm/query/dense_tiler.cc
  tiledb/sm/query/global_order_writer.cc
  tiledb/sm/query/result_tile.cc
  tiledb/sm/storage_manager/storage_manager.cc
  tiledb/sm/subarray/range_subset.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray_partitioner.cc
  tiledb/sm/subarray/test/unit_range_subset.cc
  tiledb/type/range/range.h
Labels: pending-2.9, needs-update

#3089 Add golang annotation to capnp spec file
  tiledb/sm/serialization/tiledb-rest.capnp
Labels: backport release-2.8

#3091 Reset group metadata only based on end timestamp
  tiledb/sm/group/group.cc
Labels: backport release-2.8

#3082 C++ API function to check if Config contains a parameter
  test/src/unit-cppapi-config.cc
  tiledb/sm/cpp_api/config.h
Labels: backport release-2.10

#3095 Update group post from rest to use group_metadata_serialize over config_serialize
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/array.cc
Labels: backport release-2.8

#3012 ArraySchema::deserialize factory conversion
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/enums/array_type.h
  tiledb/sm/enums/layout.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.9

#3104 Sparse unordered w/ dups reader: fix incomplete reason for cloud reads.
  tiledb/sm/query/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.8, backport release-2.9

#3120 Remove msys2 from workflows, reduce rtools40 matrix to ucrt
  .github/workflows/msys2.yml
  .github/workflows/rtools40.yml
Labels: backport release-2.9
