Repository TileDB-Inc/TileDB, pull requests merged in 2023-03, with the labels that each got.

#3897 add .rc file containing version info to windows build
  cmake/inputs/tiledb_win32_verinfo.rc.in
  tiledb/CMakeLists.txt
Labels: pending-2.16

#3924 Update ArraySchema Cap'n Proto serialization to include dimension labels
  test/src/test-capi-dense-array-dimension-label-var.cc
  test/src/test-capi-dense-array-dimension-label.cc
  test/src/test-capi-dimension-label.cc
  test/src/test-capi-sparse-array-dimension-label.cc
  test/support/src/vfs_helpers.cc
  test/support/src/vfs_helpers.h
  tiledb/sm/array_schema/dimension_label.cc
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/test/CMakeLists.txt
  tiledb/sm/serialization/test/unit_capnp_array_schema.cc
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: pending-2.16

#3844 Query Condition NOT support
  test/src/cpp-integration-query-condition.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/query_condition.h
  tiledb/sm/query/query_condition.cc
  tiledb/sm/query/query_condition.h
  tiledb/sm/query/test/unit_query_condition.cc
Labels: pending-2.16

#3937 Sparse global order reader: fix read progress update for duplicates.
  test/src/unit-sparse-global-order-reader.cc
  tiledb/sm/query/readers/sparse_global_order_reader.cc
Labels: backport release-2.13, backport release-2.14, backport release-2.15

#3785 Simplify the Win32 VFS code.
  test/src/unit-win-filesystem.cc
  tiledb/sm/filesystem/win.cc
Labels: pending-2.16

#3938 Fix support for empty strings for Dictionary and RLE encodings
  test/src/unit-compression-rle.cc
  test/src/unit-cppapi-filter.cc
  tiledb/sm/compressors/dict_compressor.cc
  tiledb/sm/compressors/dict_compressor.h
  tiledb/sm/compressors/rle_compressor.cc
  tiledb/sm/compressors/rle_compressor.h
Labels: backport release-2.14, backport release-2.15

#3963 Sparse unordered w/ dups: fix error on double var size overflow.
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.h
Labels: backport release-2.13, backport release-2.14, backport release-2.15

#3970 Dense reader: fix copies for schema evolution.
  test/src/unit-dense-reader.cc
  tiledb/sm/query/readers/dense_reader.cc
Labels: backport release-2.15

#3947 C API dimension handle
  CMakeLists.txt
  test/src/unit-Reader.cc
  test/src/unit-capi-array.cc
  test/src/unit-filter-pipeline.cc
  tiledb/api/c_api/CMakeLists.txt
  tiledb/api/c_api/dimension/CMakeLists.txt
  tiledb/api/c_api/dimension/dimension_api.cc
  tiledb/api/c_api/dimension/dimension_api_external.h
  tiledb/api/c_api/dimension/dimension_api_internal.h
  tiledb/api/c_api/dimension/test/CMakeLists.txt
  tiledb/api/c_api/dimension/test/compile_capi_dimension_stub_main.cc
  tiledb/api/c_api/dimension/test/unit_capi_dimension.cc
  tiledb/api/c_api_support/handle/handle.h
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/api_argument_validator.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_dimension_label.cc
  tiledb/sm/c_api/tiledb_filestore.cc
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/consolidator/test/unit_fragment_consolidator.cc
  tiledb/sm/query/test/unit_query_condition.cc
  tiledb/sm/serialization/test/unit_capnp_utils.cc
Labels: pending-2.16

#3985 Sparse unordered w/ dups: overflow fix shouldn't include empty tile.
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/sm/query/readers/result_tile.h
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.11, backport release-2.13, backport release-2.14, backport release-2.15

#3878 Error out no-op set_config calls: Group
  tiledb/api/c_api/group/group_api.cc
  tiledb/api/c_api/group/group_api_external_experimental.h
  tiledb/sm/cpp_api/group_experimental.h
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
  tiledb/sm/serialization/group.cc
Labels: pending-2.16

#3965 Dense reader: read next batch of tiles as other get processed.
  test/src/unit-capi-config.cc
  test/src/unit-dense-reader.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/common/thread_pool/test/unit_thread_pool.cc
  tiledb/common/thread_pool/thread_pool.cc
  tiledb/common/thread_pool/thread_pool.h
  tiledb/sm/config/config.cc
  tiledb/sm/cpp_api/config.h
  tiledb/sm/query/readers/dense_reader.cc
  tiledb/sm/query/readers/dense_reader.h
Labels: pending-2.16
