Repository TileDB-Inc/TileDB, pull requests merged in 2023-06, with the labels that each got.

#4108 Fix bug loading var sized tiles in dense_reader
  test/regression/CMakeLists.txt
  test/regression/targets/sc-29682.cc
  tiledb/sm/query/readers/dense_reader.cc
Labels: backport release-2.15

#4120 Remove `TILEDB_EXPORT` from private C API functions.
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_filestore.cc
Labels: pending-2.16

#4135 Fix REST client curl buffer management
  tiledb/sm/rest/rest_client.cc
Labels: backport release-2.15

#4081 Deletes: Ensure objects cannot be reopened
  test/src/unit-cppapi-deletes.cc
  tiledb/sm/cpp_api/array.h
  tiledb/sm/cpp_api/group_experimental.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: pending-2.16

#4088 Check subarray is within domain bounds for dense reads.
  test/src/unit-cppapi-subarray.cc
  tiledb/sm/query/legacy/reader.cc
  tiledb/sm/query/legacy/reader.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/readers/dense_reader.cc
  tiledb/sm/query/readers/dense_reader.h
  tiledb/sm/query/readers/reader_base.cc
  tiledb/sm/query/readers/reader_base.h
  tiledb/sm/subarray/range_subset.cc
  tiledb/sm/subarray/range_subset.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: pending-2.16

#4105 UnorderedWriter fragment metadata deserialization fix
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/serialization/query.cc
Labels: pending-2.16

#4144 Patch the AWS SDK to disable -Werror
  ports/aws-sdk-cpp/008-disable-werror.patch
  ports/aws-sdk-cpp/portfile.cmake
Labels: backport release-2.16
