Repository TileDB-Inc/TileDB, pull requests merged in 2023-11, with the labels that each got.

#4472 Fix serialization of empty enumerations
  test/src/unit-enumerations.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/serialization/enumeration.cc
Labels: backport release-2.17, backport release-2.18

#4501 Free query fields in set buffer cpp api after use.
  tiledb/sm/cpp_api/query.h
Labels: backport release-2.18

#4378 Refactor the group code.
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
  tiledb/sm/group/group_details.cc
  tiledb/sm/group/group_details.h
  tiledb/sm/group/group_details_v1.cc
  tiledb/sm/group/group_details_v1.h
  tiledb/sm/group/group_details_v2.cc
  tiledb/sm/group/group_details_v2.h
  tiledb/sm/serialization/group.cc
  tiledb/sm/storage_manager/storage_manager.cc
Labels: pending-2.19

#4541 Fix delta filter deserialization for format ver 19.
  tiledb/sm/filter/filter_create.cc
Labels: backport release-2.18
