Repository TileDB-Inc/TileDB, pull requests merged in 2023-01, with the labels that each got.

#3788 Override config default if AWS_{DEFAULT_}REGION environment variable …
  tiledb/sm/config/config.cc
  tiledb/sm/filesystem/s3.cc
Labels: backport release-2.14

#3791 FragmentInfo::get_fragment_name - fix bug but deprecate API
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/cpp_api/fragment_info.h
  tiledb/sm/fragment/fragment_info.cc
  tiledb/sm/fragment/single_fragment_info.h
Labels: backport release-2.14

#3795 Include coordinates for multipart remote queries
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.14

#3808 Enable RLE and Dictionary encoding on UTF-8 attrs
  test/src/unit-cppapi-filter.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/compressors/test/unit_dict_compressor.cc
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/filter_pipeline.cc
Labels: backport release-2.14

#3802 Deprecate tiledb_query_submit_async
  doc/policy/api_changes.md
  tiledb/sm/c_api/tiledb.h
Labels: backport release-2.14

#3822 Fix ASAN-detected UAF in sparse reader
  tiledb/sm/query/readers/sparse_global_order_reader.cc
Labels: asan

#3821 Tile metadata generator: fix buffer overflow on string comparison.
  tiledb/sm/tile/tile_metadata_generator.cc
Labels: backport release-2.14, asan

#3836 Sync history from 2.13.2
  HISTORY.md
Labels: backport release-2.14
