Repository TileDB-Inc/TileDB, pull requests merged in 2023-09, with the labels that each got.

#4305 Fix QueryCondition set conditions for Enumerations
  test/src/unit-cppapi-query-condition-sets.cc
  tiledb/sm/cpp_api/query_condition_experimental.h
  tiledb/sm/query/ast/query_ast.cc
Labels: blocks-2.17

#4325 Fix missing installation of WebP::sharpyuv
  cmake/Modules/FindWebp_EP.cmake
Labels: backport release-2.17

#4335 Fix re-loading enumerations from the REST server
  tiledb/sm/array/array.cc
Labels: backport release-2.17

#4338 Add missing space
  tiledb/api/c_api/domain/domain_api.cc
Labels: backport release-2.17

#4339 Improve missing enumeration value error message
  test/src/unit-cppapi-enumerations.cc
  tiledb/sm/query/ast/query_ast.cc
Labels: backport release-2.17

#4336 Fix static linking failures and build `ExampleExe_static` on Windows.
  .github/workflows/build-windows.yml
  cmake/Modules/FindMagic_EP.cmake
  cmake/Modules/FindWebp_EP.cmake
  examples/cmake_project/CMakeLists.txt
  ports/libmagic/CMakeLists.txt
  ports/pcre2/fix-cmake.patch
  ports/pcre2/portfile.cmake
  ports/pcre2/usage
  ports/pcre2/vcpkg.json
  tiledb/CMakeLists.txt
Labels: backport release-2.17

#4347 tiledb_vfs_open is not reporting error correctly
  test/src/unit-capi-vfs.cc
  tiledb/api/c_api/vfs/test/unit_capi_vfs.cc
  tiledb/api/c_api/vfs/vfs_api.cc
  tiledb/api/c_api/vfs/vfs_api_internal.h
Labels: backport release-2.17

#4355 Compilation fix for GCC 9.4 of Ubuntu 20.04
  tiledb/sm/cpp_api/type.h
Labels: backport release-2.17

#4369 Avoid empty HTTP requests to load Enumerations
  tiledb/sm/array/array.cc
  tiledb/sm/array/array_directory.cc
  tiledb/sm/rest/rest_client.cc
Labels: pending 2.18

#4380 Fix the format specification for group members.
  format_spec/group.md
  tiledb/sm/group/group_member_v2.cc
Labels: pending 2.18

#3964 Remove parallel file I/O.
  test/src/unit-capi-config.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-cppapi-config.cc
  test/src/unit-win-filesystem.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/win.cc
  tiledb/sm/filesystem/win.h
Labels: decision, pending 2.18

#4368 C.41 compliance: S3 factory constructor
  test/src/unit-s3-no-multipart.cc
  test/src/unit-s3.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
Labels: pending-2.18

#3847 Small change to loop in int Domain::cell_order_cmp_impl<char>
  tiledb/sm/array_schema/domain.cc
Labels: pending-2.18

#3923 Add REST client support for delete_fragments and delete_fragments_list
  test/regression/targets/sc-25116.cc
  test/src/unit-capi-array.cc
  test/src/unit-cppapi-deletes.cc
  tiledb/CMakeLists.txt
  tiledb/sm/array/array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_serialization.h
  tiledb/sm/cpp_api/array.h
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/array.h
  tiledb/sm/serialization/fragments.cc
  tiledb/sm/serialization/fragments.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: pending-2.18
