Repository TileDB-Inc/TileDB, pull requests merged in 2023-08, with the labels that each got.

#3982 C API attribute handle
  CMakeLists.txt
  test/regression/targets/sc-23712.cc
  test/src/unit-cppapi-schema-evolution.cc
  test/src/unit-enumerations.cc
  test/src/unit-filter-pipeline.cc
  test/src/unit-tile-metadata-generator.cc
  tiledb/api/c_api/CMakeLists.txt
  tiledb/api/c_api/attribute/CMakeLists.txt
  tiledb/api/c_api/attribute/attribute_api.cc
  tiledb/api/c_api/attribute/attribute_api_external.h
  tiledb/api/c_api/attribute/attribute_api_external_experimental.h
  tiledb/api/c_api/attribute/attribute_api_internal.h
  tiledb/api/c_api/attribute/test/CMakeLists.txt
  tiledb/api/c_api/attribute/test/compile_capi_attribute_stub_main.cc
  tiledb/api/c_api/attribute/test/unit_capi_attribute.cc
  tiledb/api/c_api/dimension/test/unit_capi_dimension.cc
  tiledb/api/c_api_test_support/testsupport_capi_datatype.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/array_schema_evolution.cc
  tiledb/sm/array_schema/array_schema_evolution.h
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/attribute.h
  tiledb/sm/c_api/api_argument_validator.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_dimension_label.cc
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/c_api/tiledb_filestore.cc
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/consolidator/test/unit_fragment_consolidator.cc
  tiledb/sm/cpp_api/attribute_experimental.h
  tiledb/sm/query/test/unit_query_condition.cc
  tiledb/sm/serialization/array_schema_evolution.cc
Labels: pending-2.17

#4072 Add C APIs for dimension label REST support
  test/src/test-capi-dimension-label.cc
  tiledb/sm/c_api/tiledb_dimension_label.cc
  tiledb/sm/c_api/tiledb_dimension_label_experimental.h
Labels: pending-2.17

#4229 Add support for serialization of vacuum and consolidation requests (#3902)
  tiledb/CMakeLists.txt
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/consolidation.cc
  tiledb/sm/serialization/consolidation.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/vacuum.cc
  tiledb/sm/serialization/vacuum.h
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.16

#4084 Dimension label rest support
  examples/cpp_api/quickstart_dimension_labels.cc
  test/src/test-capi-dense-array-dimension-label.cc
  test/src/test-capi-dimension-label.cc
  test/src/unit-ordered-dim-label-reader.cc
  test/support/src/helpers.cc
  test/support/src/helpers.h
  tiledb/sm/array/array.cc
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/query/dimension_label/array_dimension_label_queries.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/readers/attribute_order_validator.h
  tiledb/sm/query/readers/ordered_dim_label_reader.cc
  tiledb/sm/query/readers/ordered_dim_label_reader.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
  tiledb/sm/subarray/subarray.cc
Labels: pending-2.17

#4216 Update VFS S3 to ListObjectsV2
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
Labels: pending-2.17

#4232 Export `Azure::azure-storage-blobs` on install when vcpkg is enabled.
  tiledb/CMakeLists.txt
Labels: backport release-2.16

#4184 Merge overlapping ranges on sparse reads
  test/src/unit-capi-config.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-consolidation-with-timestamps.cc
  test/src/unit-cppapi-hilbert.cc
  test/src/unit-cppapi-schema-evolution.cc
  test/src/unit-cppapi-subarray.cc
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/subarray/range_subset.cc
  tiledb/sm/subarray/range_subset.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
  tiledb/sm/subarray/test/unit_range_subset.cc
  tiledb/type/range/range.h
Labels: pending-2.17

#4246 Unordered writes: fix deserialization for older clients.
  tiledb/sm/serialization/query.cc
Labels: backport release-2.16

#4245 Patch the AWS SDK external project to disable -Werror
  cmake/Modules/FindAWSSDK_EP.cmake
  cmake/inputs/patches/ep_awssdk/disable-werror.patch
Labels: backport release-2.16

#4256 Make generic tile decompression single threaded.
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/tile/generic_tile_io.cc
Labels: pending-2.17, backport release-2.16

#4258 Fix casing of `LibXml2`.
  tiledb/CMakeLists.txt
Labels: backport release-2.16

#4263 Fix importing Win32 static dependencies for S3 and Azure.
  cmake/Modules/FindAWSSDK_EP.cmake
  tiledb/CMakeLists.txt
Labels: backport release-2.16

#4264 fix serialization of var-size property for nonempty domains
  tiledb/sm/serialization/capnp_utils.h
  tiledb/sm/serialization/test/CMakeLists.txt
  tiledb/sm/serialization/test/unit_capnp_nonempty_domain.cc
Labels: backport release-2.16

#4267 Clear pending changes during group delete
  tiledb/sm/group/group.cc
Labels: backport release-2.16

#4233 Update filter checks for accepted datatypes
  tiledb/sm/filter/bit_width_reduction_filter.cc
  tiledb/sm/filter/positive_delta_filter.cc
Labels: pending-2.17

#4281 LibXML2 needs to be linked after Azure libraries
  tiledb/CMakeLists.txt
Labels: backport release-2.16

#4287 Optimize capnp traversal size usage
  test/src/unit-capi-config.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/fragment_info.cc
  tiledb/sm/serialization/fragment_metadata.cc
  tiledb/sm/serialization/fragment_metadata.h
  tiledb/sm/serialization/query.cc
Labels: backport release-2.16

#4164 Support set membership tests for query conditions.
  test/CMakeLists.txt
  test/src/unit-cppapi-query-condition-sets.cc
  test/src/unit-enumerations.cc
  test/support/src/ast_helpers.cc
  test/support/src/serialization_wrappers.h
  test/support/src/vfs_helpers.cc
  test/support/src/vfs_helpers.h
  tiledb/sm/array_schema/enumeration.cc
  tiledb/sm/array_schema/enumeration.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_enum.h
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/cpp_api/query_condition_experimental.h
  tiledb/sm/enums/query_condition_op.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/ast/query_ast.cc
  tiledb/sm/query/ast/query_ast.h
  tiledb/sm/query/deletes_and_updates/serialization.cc
  tiledb/sm/query/query_condition.cc
  tiledb/sm/query/query_condition.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: pending-2.17, blocks-2.17
