Repository TileDB-Inc/TileDB, pull requests merged in 2023-04, with the labels that each got.

#4024 Fix vac files to include relative file names.
  tiledb/sm/array/array_directory.cc
  tiledb/sm/array/array_directory.h
  tiledb/sm/array/test/unit_array_directory.cc
  tiledb/sm/consolidator/array_meta_consolidator.cc
  tiledb/sm/consolidator/fragment_consolidator.cc
  tiledb/sm/consolidator/fragment_consolidator.h
  tiledb/sm/misc/constants.cc
Labels: pending-2.16

#3438 Add MemFS context isolation test, and use memfs in quickstart dense example.
  examples/cpp_api/quickstart_dense.cc
  test/src/unit-cppapi-array.cc
  tiledb/sm/filesystem/mem_filesystem.h
Labels: blocked

#3961 Update Subarray Cap'n Proto serialization to include label ranges
  test/src/test-capi-dense-array-dimension-label.cc
  test/src/test-capi-sparse-array-dimension-label.cc
  test/src/unit-ordered-dim-label-reader.cc
  test/support/src/serialization_wrappers.cc
  test/support/src/serialization_wrappers.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
  tiledb/sm/subarray/subarray.cc
  tiledb/sm/subarray/subarray.h
Labels: pending-2.17

#4022 Make sure metadata are deleted when they got added in the same operation.
  test/src/unit-capi-group.cc
  tiledb/sm/metadata/metadata.cc
Labels: pending-2.16

#4046 Fix Query Conditions for Boolean Attributes
  test/src/cpp-integration-query-condition.cc
  tiledb/sm/cpp_api/type.h
  tiledb/sm/query/query_condition.cc
Labels: pending-2.16

#3910 Use the new Azure SDK for C++.
  .dockerignore
  .github/workflows/build-windows.yml
  cmake/Modules/FindAzureSDK_EP.cmake
  cmake/Options/TileDBToolchain.cmake
  cmake/TileDB-Superbuild.cmake
  cmake/inputs/patches/README.md
  cmake/inputs/patches/ep_azuresdk/base64.cpp.patch
  cmake/inputs/patches/ep_azuresdk/v0.3.0-patchset.patch
  cmake/inputs/patches/ep_azuresdk/v0.3.0.CMakeLists.txt.md5mitigation
  examples/Dockerfile/Dockerfile
  ports/azure-storage-cpplite/001-CMakeLists.patch
  ports/azure-storage-cpplite/002-base64.cpp.patch
  ports/azure-storage-cpplite/003-misc.patch
  ports/azure-storage-cpplite/portfile.cmake
  ports/azure-storage-cpplite/vcpkg.json
  ports/spdlog/portfile.cmake
  scripts/azure-linux_mac.yml
  scripts/install-azurite.sh
  test/src/unit-azure.cc
  test/src/unit-capi-config.cc
  test/src/unit-capi-dense_array.cc
  test/src/unit-capi-vfs.cc
  test/src/unit-cppapi-config.cc
  test/src/unit-vfs.cc
  test/support/src/helpers.cc
  test/support/src/vfs_helpers.cc
  tiledb/CMakeLists.txt
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/azure.cc
  tiledb/sm/filesystem/azure.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  vcpkg.json
Labels: pending-2.16
