Repository TileDB-Inc/TileDB, pull requests merged in 2023-10, with the labels that each got.

#4071 Remove `ValidityVector::init_bytemap`.
  tiledb/common/exception/status.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/test/unit_validity_vector.cc
  tiledb/sm/query/validity_vector.h
Labels: pending-2.18

#3996 Add group backwards compatibility tests
  test/src/unit-backwards_compat.cc
Labels: pending-2.18

#4012 Remove statuses from the Metadata code.
  test/src/unit-capi-array.cc
  tiledb/api/c_api/group/group_api.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array/array.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
  tiledb/sm/metadata/metadata.cc
  tiledb/sm/metadata/metadata.h
  tiledb/sm/metadata/test/unit_metadata.cc
  tiledb/sm/serialization/array.cc
Labels: pending-2.18

#4397 Update `clang-format` to version 16.
  .clang-format
  cmake/Modules/FindClangTools.cmake
  cmake/TileDB-Superbuild.cmake
  examples/png_ingestion/src/main.cc
  experimental/tiledb/common/dag/execution/test/unit_frugal.cc
  experimental/tiledb/common/dag/execution/test/unit_tasks.cc
  experimental/tiledb/common/dag/nodes/detail/segmented/function.h
  scripts/ci/check_formatting_linux.sh
  scripts/install-clangformat.sh
  test/src/unit-capi-query_2.cc
  tiledb/sm/filter/test/compile_all_filters_main.cc
  tiledb/sm/stats/test/unit_stats.cc
Labels: pending-2.18

#4031 Update the GCS SDK to its latest version.
  cmake/Modules/FindGCSSDK_EP.cmake
  cmake/TileDB-Superbuild.cmake
  ports/abseil/fix-32-bit-arm.patch
  ports/abseil/fix-cxx-standard.patch
  ports/abseil/portfile.cmake
  ports/abseil/vcpkg.json
  ports/google-cloud-cpp/portfile.cmake
  ports/google-cloud-cpp/support_absl_cxx17.patch
  ports/google-cloud-cpp/vcpkg.json
  tiledb/CMakeLists.txt
  tiledb/sm/filesystem/gcs.cc
  vcpkg.json
Labels: pending-2.18

#4052 Global order writer: don't try to delete the current fragment if it had failed to be created.
  tiledb/sm/query/writers/global_order_writer.cc
Labels: pending-2.18

#4393 Remove `class Status` from exception handler.
  CMakeLists.txt
  tiledb/api/c_api/context/context_api.cc
  tiledb/api/c_api/context/context_api_internal.h
  tiledb/api/c_api/data_order/CMakeLists.txt
  tiledb/api/c_api/datatype/CMakeLists.txt
  tiledb/api/c_api/error/CMakeLists.txt
  tiledb/api/c_api/error/error_api.cc
  tiledb/api/c_api/error/error_api_internal.h
  tiledb/api/c_api/error/test/CMakeLists.txt
  tiledb/api/c_api/filesystem/CMakeLists.txt
  tiledb/api/c_api/object/CMakeLists.txt
  tiledb/api/c_api/object/test/CMakeLists.txt
  tiledb/api/c_api/query/CMakeLists.txt
  tiledb/api/c_api/string/CMakeLists.txt
  tiledb/api/c_api_support/argument_validation.h
  tiledb/api/c_api_support/exception_wrapper/CMakeLists.txt
  tiledb/api/c_api_support/exception_wrapper/exception_wrapper.cc
  tiledb/api/c_api_support/exception_wrapper/exception_wrapper.h
  tiledb/api/c_api_support/exception_wrapper/test/CMakeLists.txt
  tiledb/api/c_api_support/exception_wrapper/test/compile_exception_wrapper_main.cc
  tiledb/api/c_api_support/exception_wrapper/test/unit_capi_error_tree.cc
  tiledb/api/c_api_support/exception_wrapper/test/unit_capi_exception_wrapper.cc
  tiledb/api/c_api_support/handle/handle.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/storage_manager/context.cc
  tiledb/sm/storage_manager/context.h
Labels: pending-2.18

#4400 Add custom headers in s3
  test/src/unit-cppapi-config.cc
  test/src/unit-s3-no-multipart.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
Labels: pending-2.18

#4418 Prepend a question mark to the Azure Storage SAS token if it does not begin with one.
  test/src/unit-azure.cc
  tiledb/sm/filesystem/azure.cc
  tiledb/sm/filesystem/azure.h
Labels: backport release-2.17

#4385 Query field C API
  CMakeLists.txt
  tiledb/api/c_api/CMakeLists.txt
  tiledb/api/c_api/query_aggregate/query_aggregate_api.cc
  tiledb/api/c_api/query_aggregate/query_aggregate_api_internal.h
  tiledb/api/c_api/query_field/CMakeLists.txt
  tiledb/api/c_api/query_field/query_field_api.cc
  tiledb/api/c_api/query_field/query_field_api_external_experimental.h
  tiledb/api/c_api/query_field/query_field_api_internal.h
  tiledb/api/c_api/query_field/test/CMakeLists.txt
  tiledb/api/c_api/query_field/test/compile_capi_query_field_main.cc
  tiledb/api/c_api/query_field/test/unit_capi_query_field.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/readers/aggregators/count_aggregator.h
  tiledb/sm/query/readers/aggregators/iaggregator.h
  tiledb/sm/query/readers/aggregators/mean_aggregator.h
  tiledb/sm/query/readers/aggregators/min_max_aggregator.h
  tiledb/sm/query/readers/aggregators/sum_aggregator.h
  tiledb/sm/query/readers/aggregators/sum_type.h
  tiledb/sm/query/readers/aggregators/test/unit_aggregators.cc
Labels: pending-2.18

#4138 Support GCS on Windows.
  .github/workflows/build-windows.yml
  bootstrap.ps1
  scripts/install-run-gcs-emu.ps1
  test/src/unit-gcs.cc
  test/src/unit-gs.cc
  tiledb/CMakeLists.txt
  tiledb/sm/filesystem/gcs.cc
  tiledb/sm/filesystem/gcs.h
Labels: pending-2.18

#4391 Update `tiledb_group_remove_member` to remove members by name first.
  test/src/unit-capi-group.cc
  test/src/unit-cppapi-group.cc
  tiledb/api/c_api/group/group_api.cc
  tiledb/api/c_api/group/group_api_external_experimental.h
  tiledb/sm/cpp_api/group_experimental.h
  tiledb/sm/group/group.cc
  tiledb/sm/group/group.h
  tiledb/sm/group/group_details.cc
  tiledb/sm/group/group_details.h
  tiledb/sm/group/group_details_v1.cc
  tiledb/sm/group/group_details_v2.cc
  tiledb/sm/group/group_member.h
Labels: pending-2.18

#4439 Fix the release workflow and enable GCS in the Windows binaries.
  .github/workflows/build-windows.yml
  .github/workflows/ci-linux_mac.yml
  azure-pipelines.yml
  scripts/azure-linux_mac-release.yml
  scripts/azure-windows-release.yml
  scripts/ci/patch_vcpkg_triplets.py
  scripts/ci/posix/patch_vcpkg_triplets.sh
Labels: pending-2.19

#3863 Commit test program for S3 write caching
  experimental/experimental_examples/cpp_api/global_order_write_s3_buffering.cc
Labels: pending-2.19

#4047 Improve experience when performing too large GCS direct uploads.
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-config.cc
  test/src/unit-gcs.cc
  test/src/unit-gs.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/filesystem/gcs.cc
Labels: pending-2.19

#3763 Refactor filestore API so that it uses internal TileDB library calls.
  tiledb/sm/c_api/tiledb_filestore.cc
Labels: pending-2.19

#3147 Group metadata doesn't get serialized
  test/src/unit-capi-group.cc
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/serialization/group.cc
  tiledb/sm/serialization/group.h
Labels: pending-2.19

#3987 Encode Win32 error messages in UTF-8.
  test/CMakeLists.txt
  test/src/unit-win-filesystem.cc
  tiledb/sm/filesystem/win.cc
Labels: pending-2.19

#4460 Convert C API interface functions to CAPI_INTERFACE
  tiledb/api/c_api/attribute/attribute_api.cc
  tiledb/api/c_api/buffer/buffer_api.cc
  tiledb/api/c_api/buffer_list/buffer_list_api.cc
  tiledb/api/c_api/data_order/data_order_api.cc
  tiledb/api/c_api/datatype/datatype_api.cc
  tiledb/api/c_api/dimension/dimension_api.cc
  tiledb/api/c_api/dimension_label/dimension_label_api.cc
  tiledb/api/c_api/domain/domain_api.cc
  tiledb/api/c_api/enumeration/enumeration_api.cc
  tiledb/api/c_api/filesystem/filesystem_api.cc
  tiledb/api/c_api/filter/filter_api.cc
  tiledb/api/c_api/filter_list/filter_list_api.cc
  tiledb/api/c_api/group/group_api.cc
  tiledb/api/c_api/object/object_api.cc
  tiledb/api/c_api/query/query_api.cc
  tiledb/api/c_api/query_aggregate/query_aggregate_api.cc
  tiledb/api/c_api/query_field/query_field_api.cc
  tiledb/api/c_api/query_plan/query_plan_api.cc
  tiledb/api/c_api/string/string_api.cc
  tiledb/api/c_api/vfs/vfs_api.cc
  tiledb/api/c_api_support/exception_wrapper/capi_definition.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb_dimension_label.cc
  tiledb/sm/c_api/tiledb_experimental.h
  tiledb/sm/c_api/tiledb_filestore.cc
Labels: backport release-2.18
