Repository TileDB-Inc/TileDB, pull requests merged in 2023-02, with the labels that each got.

#3859 Bug fix: allow reopening a remote array with Consistency Controller
  tiledb/sm/array/array.cc
Labels: backport release-2.14

#3609 Implement S3 buffering support for remote global order writes
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
  tiledb/sm/filesystem/uri.cc
  tiledb/sm/filesystem/uri.h
  tiledb/sm/filesystem/vfs.cc
  tiledb/sm/filesystem/vfs.h
  tiledb/sm/misc/constants.cc
  tiledb/sm/misc/constants.h
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
  tiledb/sm/query/writers/writer_base.cc
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
Labels: backport release-2.13

#3866 Return underlying error in Win::remove_dir
  tiledb/sm/filesystem/win.cc
Labels: pending-2.15

#3868 RLE and dictionary filter only enabled for UTF8 since format version 17.
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/query/readers/reader_base.cc
Labels: backport release-2.14

#3851 Fix buffer size error in deserializing query
  test/src/unit-capi-serialized_queries.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
  tiledb/sm/serialization/query.cc
Labels: backport release-2.13, backport release-2.14, pending-2.15

#3877 Fragment consolidation: using correct buffer weights.
  test/src/unit-capi-consolidation.cc
  tiledb/sm/consolidator/fragment_consolidator.cc
  tiledb/sm/consolidator/test/unit_fragment_consolidator.cc
Labels: backport release-2.14

#3891 Support building against external, updated google-cloud-cpp install
  cmake/Modules/FindGCSSDK_EP.cmake
Labels: pending-2.15

#3895 Fix bug when setting var sized dimension buffers
  test/regression/CMakeLists.txt
  test/regression/targets/sc-25116.cc
  tiledb/sm/query/query.cc
Labels: backport release-2.15

#3903 Fix check during remote unordered write finalization.
  tiledb/sm/query/writers/unordered_writer.cc
Labels: backport release-2.15

#3857 Filter pipeline: make chunk range path default and remove other.
  test/src/unit-filter-pipeline.cc
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/query/readers/reader_base.cc
  tiledb/sm/query/readers/reader_base.h
  tiledb/sm/tile/generic_tile_io.cc
  tiledb/sm/tile/tile.cc
  tiledb/sm/tile/tile.h
  tiledb/storage_format/serialization/test/unit_serializers.cc
Labels: pending-2.16

#3901 Prevent query conditions with dimension labels
  test/src/test-capi-dense-array-dimension-label.cc
  tiledb/sm/query/dimension_label/array_dimension_label_queries.cc
  tiledb/sm/query/query.cc
  tiledb/sm/query/query.h
Labels: backport release-2.15

#3908 Install pkg-config for MacOS release CI
  scripts/azure-linux_mac-release.yml
Labels: backport release-2.13, backport release-2.14, backport release-2.15

#3902 Add support for serialization of vacuum and consolidation requests
  tiledb/CMakeLists.txt
  tiledb/sm/rest/rest_client.cc
  tiledb/sm/rest/rest_client.h
  tiledb/sm/serialization/consolidation.cc
  tiledb/sm/serialization/consolidation.h
  tiledb/sm/serialization/posix/tiledb-rest.capnp.c++
  tiledb/sm/serialization/posix/tiledb-rest.capnp.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/vacuum.cc
  tiledb/sm/serialization/vacuum.h
  tiledb/sm/serialization/win32/tiledb-rest.capnp.c++
  tiledb/sm/serialization/win32/tiledb-rest.capnp.h
  tiledb/sm/storage_manager/storage_manager.cc
Labels: backport release-2.15

#3918 Dense reader: adjust memory configuration parameters.
  test/src/unit-capi-config.cc
  test/src/unit-dense-reader.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/cpp_api/config.h
  tiledb/sm/query/readers/dense_reader.cc
  tiledb/sm/query/readers/dense_reader.h
Labels: backport release-2.15

#3849 Refactor the POSIX VFS and improve error messages.
  tiledb/sm/filesystem/posix.cc
  tiledb/sm/filesystem/posix.h
Labels: pending-2.16
