Repository TileDB-Inc/TileDB, pull requests merged in 2023-07, with the labels that each got.

#4142 Support var length dimension labels from Python
  test/src/test-cppapi-dense-array-dimension-label.cc
  tiledb/sm/cpp_api/query_experimental.h
  tiledb/sm/query/dimension_label/array_dimension_label_queries.cc
  tiledb/sm/query/dimension_label/array_dimension_label_queries.h
Labels: pending-2.16, backport release-2.16

#4154 Fix VFS is_empty_bucket cpp api
  test/src/unit-cppapi-vfs.cc
  tiledb/sm/cpp_api/vfs.h
Labels: backport release-2.16

#4148 Reset QueryStatus after QueryStrategy deserialization
  tiledb/sm/serialization/query.cc
Labels: backport release-2.16

#4153 Support new Azure SDK in superbuild
  CMakeLists.txt
  cmake/Modules/FindAzureCore_EP.cmake
  cmake/Modules/FindAzureStorageBlobs_EP.cmake
  cmake/Modules/FindAzureStorageCommon_EP.cmake
  cmake/Modules/FindWIL_EP.cmake
  cmake/TileDB-Superbuild.cmake
  external/blosc/CMakeLists.txt
  tiledb/CMakeLists.txt
Labels: backport release-2.16

#4152 Rename result_buffer_elements_labels and update doxygen
  test/src/test-cppapi-dense-array-dimension-label.cc
  tiledb/sm/cpp_api/query_experimental.h
  tiledb/sm/query/dimension_label/array_dimension_label_queries.h
Labels: backport release-2.16

#4161 Add space in aws-sdk-cpp 0008 patch to support Windows
  ports/aws-sdk-cpp/008-disable-werror.patch
Labels: backport release-2.16

#4171 Fix order of azure static library linking
  tiledb/CMakeLists.txt
Labels: backport release-2.16

#4119 Support acquiring libmagic from vcpkg.
  .github/workflows/build-windows.yml
  cmake/Modules/FindMagic_EP.cmake
  cmake/TileDB-Superbuild.cmake
  ports/libmagic/0001-Use-pcre2.patch
  ports/libmagic/0002-Change-zlib-lib-name-to-match-CMake-output.patch
  ports/libmagic/0003-Fix-WIN32-macro-checks.patch
  ports/libmagic/0012-Convert-MSYS2-paths-to-Windows-paths.patch
  ports/libmagic/0013-Check-for-backslash-in-argv-0-on-Windows.patch
  ports/libmagic/CMakeLists.txt
  ports/libmagic/config.h
  ports/libmagic/magic.def
  ports/libmagic/portfile.cmake
  ports/libmagic/unofficial-libmagic-config.cmake.in
  ports/libmagic/usage
  ports/libmagic/vcpkg.json
  ports/pcre2/cmake-fix.patch
  ports/pcre2/no-static-suffix.patch
  ports/pcre2/pcre2-10.35_fix-uwp.patch
  ports/pcre2/portfile.cmake
  ports/pcre2/usage
  ports/pcre2/vcpkg.json
  scripts/azure-linux_mac-release.yml
  vcpkg.json
Labels: pending-2.17

#4104 Increase verbosity of error messages
  test/src/unit-cppapi-array.cc
  tiledb/sm/array/array.cc
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/dimension.cc
Labels: pending-2.17

#4174 Dense reader: fix nullable string values when reading with qc.
  test/src/cpp-integration-query-condition.cc
  tiledb/sm/query/readers/dense_reader.cc
Labels: pending-2.17, backport release-2.16

#4053 C API domain handle
  CMakeLists.txt
  cmake/accumulator.cmake
  test/src/unit-Reader.cc
  test/src/unit-filter-pipeline.cc
  tiledb/api/c_api/CMakeLists.txt
  tiledb/api/c_api/dimension/dimension_api.cc
  tiledb/api/c_api/dimension/dimension_api_external.h
  tiledb/api/c_api/dimension/dimension_api_internal.h
  tiledb/api/c_api/domain/CMakeLists.txt
  tiledb/api/c_api/domain/domain_api.cc
  tiledb/api/c_api/domain/domain_api_external.h
  tiledb/api/c_api/domain/domain_api_internal.h
  tiledb/api/c_api/domain/test/CMakeLists.txt
  tiledb/api/c_api/domain/test/compile_capi_domain_stub_main.cc
  tiledb/api/c_api/domain/test/unit_capi_domain.cc
  tiledb/api/c_api_test_support/testsupport_capi_context.h
  tiledb/sm/array_schema/array_schema.h
  tiledb/sm/array_schema/domain.cc
  tiledb/sm/array_schema/domain.h
  tiledb/sm/c_api/api_argument_validator.h
  tiledb/sm/c_api/tiledb.cc
  tiledb/sm/c_api/tiledb.h
  tiledb/sm/c_api/tiledb_struct_def.h
  tiledb/sm/consolidator/test/unit_fragment_consolidator.cc
  tiledb/sm/query/test/unit_query_condition.cc
  tiledb/sm/rtree/test/unit_rtree.cc
  tiledb/sm/serialization/array_schema.cc
Labels: pending-2.17

#4200 Sparse unordered w/ dups reader: adding ignored tiles.
  test/src/unit-sparse-global-order-reader.cc
  test/src/unit-sparse-unordered-with-dups-reader.cc
  tiledb/sm/query/readers/sparse_unordered_with_dups_reader.cc
Labels: backport release-2.16

#4202 Allow Subarray::get_est_result_size_nullable on remote arrays
  tiledb/sm/subarray/subarray.cc
Labels: backport release-2.16

#4201 Bump catch2 to 3.3.2 in vcpkg
  ports/catch2/fix-install-path.patch
  ports/catch2/portfile.cmake
  ports/catch2/vcpkg.json
Labels: backport release-2.16

#4034 C++20
  .github/workflows/full-ci.yml
  CMakeLists.txt
  experimental/experimental_examples/cpp_api/taskgraph_filtering.cc
  experimental/experimental_examples/cpp_api/taskgraph_inmemory_filtering.cc
  experimental/tiledb/common/dag/execution/CMakeLists.txt
  experimental/tiledb/common/dag/execution/duffs.h
  experimental/tiledb/common/dag/execution/jthread/condition_variable_any2.hpp
  experimental/tiledb/common/dag/execution/jthread/jthread.hpp
  experimental/tiledb/common/dag/execution/jthread/stop_token.hpp
  experimental/tiledb/common/dag/execution/stop_token.cc
  experimental/tiledb/common/dag/execution/test/CMakeLists.txt
  experimental/tiledb/common/dag/execution/test/compile_stop_token_main.cc
  experimental/tiledb/common/dag/execution/test/unit_frugal.cc
  experimental/tiledb/common/dag/execution/test/unit_scheduler.cc
  experimental/tiledb/common/dag/execution/test/unit_stop_token.cc
  experimental/tiledb/common/dag/execution/test/unit_stop_token.h
  experimental/tiledb/common/dag/execution/test/unit_tasks.cc
  experimental/tiledb/common/dag/graph/taskgraph.h
  experimental/tiledb/common/dag/nodes/detail/segmented/mimo.h
  experimental/tiledb/common/dag/nodes/detail/segmented/producer.h
  experimental/tiledb/common/dag/nodes/detail/simple/mimo.h
  experimental/tiledb/common/dag/nodes/detail/simple/producer.h
  experimental/tiledb/common/dag/nodes/detail/simple/simple_base.h
  experimental/tiledb/common/dag/nodes/generators.h
  experimental/tiledb/common/dag/nodes/test/unit_stop_source.cc
  tiledb/common/logger.cc
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/serialization/test/unit_capnp_array_schema.cc
  tiledb/sm/serialization/test/unit_capnp_utils.cc
Labels: pending-2.17

#4087 Unify ca_path and ca_file configuration parameters
  scripts/ci/posix/build-services-stop.sh
  scripts/run-azurite.sh
  scripts/run-gcs-emu.sh
  scripts/run-ssl-proxy.py
  test/CMakeLists.txt
  test/src/unit-capi-config.cc
  test/src/unit-cppapi-config.cc
  test/src/unit-ssl-config.cc
  tiledb/CMakeLists.txt
  tiledb/sm/config/config.cc
  tiledb/sm/config/config.h
  tiledb/sm/filesystem/azure.cc
  tiledb/sm/filesystem/gcs.cc
  tiledb/sm/filesystem/gcs.h
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/ssl_config.cc
  tiledb/sm/filesystem/ssl_config.h
  tiledb/sm/rest/curl.cc
Labels: pending-2.17

#4165 Typed filter pipeline
  format_spec/filter_pipeline.md
  test/regression/targets/sc-24079.cc
  test/src/unit-capi-sparse_array.cc
  test/src/unit-cppapi-webp-filter.cc
  test/src/unit-filter-pipeline.cc
  tiledb/api/c_api/dimension/dimension_api_internal.h
  tiledb/sm/array_schema/array_schema.cc
  tiledb/sm/array_schema/attribute.cc
  tiledb/sm/array_schema/dimension.cc
  tiledb/sm/array_schema/dimension.h
  tiledb/sm/compressors/delta_compressor.cc
  tiledb/sm/compressors/delta_compressor.h
  tiledb/sm/compressors/test/unit_delta_compressor.cc
  tiledb/sm/filter/bit_width_reduction_filter.cc
  tiledb/sm/filter/bit_width_reduction_filter.h
  tiledb/sm/filter/bitshuffle_filter.cc
  tiledb/sm/filter/bitshuffle_filter.h
  tiledb/sm/filter/byteshuffle_filter.cc
  tiledb/sm/filter/byteshuffle_filter.h
  tiledb/sm/filter/checksum_md5_filter.cc
  tiledb/sm/filter/checksum_md5_filter.h
  tiledb/sm/filter/checksum_sha256_filter.cc
  tiledb/sm/filter/checksum_sha256_filter.h
  tiledb/sm/filter/compression_filter.cc
  tiledb/sm/filter/compression_filter.h
  tiledb/sm/filter/encryption_aes256gcm_filter.cc
  tiledb/sm/filter/encryption_aes256gcm_filter.h
  tiledb/sm/filter/filter.cc
  tiledb/sm/filter/filter.h
  tiledb/sm/filter/filter_create.cc
  tiledb/sm/filter/filter_create.h
  tiledb/sm/filter/filter_pipeline.cc
  tiledb/sm/filter/filter_pipeline.h
  tiledb/sm/filter/float_scaling_filter.cc
  tiledb/sm/filter/float_scaling_filter.h
  tiledb/sm/filter/noop_filter.cc
  tiledb/sm/filter/noop_filter.h
  tiledb/sm/filter/positive_delta_filter.cc
  tiledb/sm/filter/positive_delta_filter.h
  tiledb/sm/filter/test/compile_all_filters_main.cc
  tiledb/sm/filter/test/compile_webp_filter_main.cc
  tiledb/sm/filter/test/unit_filter_create.cc
  tiledb/sm/filter/test/unit_filter_pipeline.cc
  tiledb/sm/filter/test/unit_float_scale_input_validation.cc
  tiledb/sm/filter/webp_filter.cc
  tiledb/sm/filter/webp_filter.h
  tiledb/sm/filter/xor_filter.cc
  tiledb/sm/filter/xor_filter.h
  tiledb/sm/serialization/array_schema.cc
  tiledb/sm/serialization/array_schema.h
  tiledb/sm/serialization/test/unit_capnp_utils.cc
  tiledb/sm/tile/generic_tile_io.cc
Labels: pending-2.17

#4067 Remove `work_arounds.cc`.
  tiledb/CMakeLists.txt
  tiledb/sm/misc/work_arounds.cc
Labels: pending-2.17
