Repository TileDB-Inc/TileDB, pull requests merged in 2024-07, with the labels that each got.

#5147 Downgrade Node.js version for manylinux jobs.
  .github/workflows/ci-linux_mac.yml
  .github/workflows/release.yml
Labels: backport release-2.23, backport release-2.24

#5154 Fix serialization issue with schema evolution for query v3.
  test/src/unit-cppapi-schema-evolution.cc
  tiledb/sm/fragment/fragment_metadata.cc
  tiledb/sm/fragment/fragment_metadata.h
  tiledb/sm/serialization/array.cc
  tiledb/sm/serialization/fragment_metadata.cc
  tiledb/sm/serialization/fragment_metadata.h
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
Labels: backport release-2.24

#5155 Unpin the manylinux image in the Release workflow.
  .github/workflows/release.yml
Labels: backport release-2.23, backport release-2.24

#5116 Warn users using dense arrays with sparse fragments.
  tiledb/sm/query/query.cc
Labels: backport release-2.25

#5195 Increase default capnp traversal limit to 2Gb.
  test/src/unit-capi-config.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/cpp_api/config.h
Labels: backport release-2.25

#5207 Enable array open v2 and query v3 by default.
  test/src/unit-capi-config.cc
  tiledb/api/c_api/config/config_api_external.h
  tiledb/sm/config/config.cc
  tiledb/sm/cpp_api/config.h
Labels: backport release-2.25
