Repository TileDB-Inc/TileDB, pull requests merged in 2024-01, with the labels that each got.

#4616 Pass AWS client config when creating `STSAssumeRoleCredentialsProvider`.
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3.h
Labels: backport release-2.19

#4641 Pass AWS client configuration to `STSProfileWithWebIdentityCredentialsProvider`.
  tiledb/sm/filesystem/s3.cc
  tiledb/sm/filesystem/s3/STSProfileWithWebIdentityCredentialsProvider.cc
  tiledb/sm/filesystem/s3/STSProfileWithWebIdentityCredentialsProvider.h
Labels: backport release-2.18, backport release-2.19

#4633 Add more fields to Query Plan capnp and other improvements.
  tiledb/sm/filesystem/uri.cc
  tiledb/sm/query_plan/query_plan.cc
  tiledb/sm/query_plan/query_plan.h
  tiledb/sm/serialization/array_directory.cc
  tiledb/sm/serialization/query.cc
  tiledb/sm/serialization/query.h
  tiledb/sm/serialization/query_plan.cc
  tiledb/sm/serialization/tiledb-rest.capnp
  tiledb/sm/serialization/tiledb-rest.capnp.c++
  tiledb/sm/serialization/tiledb-rest.capnp.h
Labels: backport release-2.20
